/* Generated by Nim Compiler v0.1.0-dev.20827 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ;
typedef struct tyTuple__kN8up2W6YKc5YA9avn5mV5w tyTuple__kN8up2W6YKc5YA9avn5mV5w;
typedef struct tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q;
typedef struct tyObject_Report__45JukV4U6A1QELeWVCpPkg tyObject_Report__45JukV4U6A1QELeWVCpPkg;
typedef struct tyObject_LexerReport__L2hPDucTxxu4gZoisMeavg tyObject_LexerReport__L2hPDucTxxu4gZoisMeavg;
typedef struct tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_Option__cTvgZv9bZQKykpX2neAdNPw tyObject_Option__cTvgZv9bZQKykpX2neAdNPw;
typedef struct tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw;
typedef struct tyObject_SemReport__9cs8ebwB0HslUeq6PUmVoSA tyObject_SemReport__9cs8ebwB0HslUeq6PUmVoSA;
typedef struct tyObject_SemishReportBase__NyQlpRjyRMr12ZU4MnrKvg tyObject_SemishReportBase__NyQlpRjyRMr12ZU4MnrKvg;
typedef struct tySequence__manAeKYtb7xtYd9cz4tqm7Q tySequence__manAeKYtb7xtYd9cz4tqm7Q;
typedef struct tySequence__manAeKYtb7xtYd9cz4tqm7Q_Content tySequence__manAeKYtb7xtYd9cz4tqm7Q_Content;
typedef struct tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ;
typedef struct tyObject_TSym__RjHO5eqpy8QqcomFydmCag tyObject_TSym__RjHO5eqpy8QqcomFydmCag;
typedef struct tySequence__rsh9bSgfYxIqIMIhkaVEzeA tySequence__rsh9bSgfYxIqIMIhkaVEzeA;
typedef struct tySequence__rsh9bSgfYxIqIMIhkaVEzeA_Content tySequence__rsh9bSgfYxIqIMIhkaVEzeA_Content;
typedef struct tyTuple__PnC4UDvgAKpIJAQzHfgaQw tyTuple__PnC4UDvgAKpIJAQzHfgaQw;
typedef struct tySequence__XrT6wRHqo12fVwXeGBWNEw tySequence__XrT6wRHqo12fVwXeGBWNEw;
typedef struct tySequence__XrT6wRHqo12fVwXeGBWNEw_Content tySequence__XrT6wRHqo12fVwXeGBWNEw_Content;
typedef struct tyTuple__2Ffi2d9cS9cU3rIY5BeTYZTQ tyTuple__2Ffi2d9cS9cU3rIY5BeTYZTQ;
typedef struct tyTuple__OZxYMNBWbABSgGMxK14Krw tyTuple__OZxYMNBWbABSgGMxK14Krw;
typedef struct tySequence__TfSakS9c2WdlxOD8UIMHqRw tySequence__TfSakS9c2WdlxOD8UIMHqRw;
typedef struct tySequence__TfSakS9c2WdlxOD8UIMHqRw_Content tySequence__TfSakS9c2WdlxOD8UIMHqRw_Content;
typedef struct tyTuple__fJqtP9bt2rKczv9aqA9bUtIng tyTuple__fJqtP9bt2rKczv9aqA9bUtIng;
typedef struct tySequence__RwrnB9cL5qmp0eCG0TsP9baA tySequence__RwrnB9cL5qmp0eCG0TsP9baA;
typedef struct tySequence__RwrnB9cL5qmp0eCG0TsP9baA_Content tySequence__RwrnB9cL5qmp0eCG0TsP9baA_Content;
typedef struct tyTuple__ssCWuzKGoCzXuz2w3ziHXw tyTuple__ssCWuzKGoCzXuz2w3ziHXw;
typedef struct tySequence__qlSKCH4HqXlnS9caj9cYs4Pw tySequence__qlSKCH4HqXlnS9caj9cYs4Pw;
typedef struct tySequence__qlSKCH4HqXlnS9caj9cYs4Pw_Content tySequence__qlSKCH4HqXlnS9caj9cYs4Pw_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_Int128__9a9axPfb75jdWY25AamJewkA tyObject_Int128__9a9axPfb75jdWY25AamJewkA;
typedef struct tyTuple__WwoBvm9bnG5PwCLNd06V1Sw tyTuple__WwoBvm9bnG5PwCLNd06V1Sw;
typedef struct tySequence__uAVKDgsmtx5N16UbHJVmFg tySequence__uAVKDgsmtx5N16UbHJVmFg;
typedef struct tySequence__uAVKDgsmtx5N16UbHJVmFg_Content tySequence__uAVKDgsmtx5N16UbHJVmFg_Content;
typedef struct tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ;
typedef struct tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content;
typedef struct tyTuple__Wqzt8z13TyGtS1eBzBTVpw tyTuple__Wqzt8z13TyGtS1eBzBTVpw;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tySequence__OTmPSHM89cLVA6xqOdNc6Xw tySequence__OTmPSHM89cLVA6xqOdNc6Xw;
typedef struct tySequence__OTmPSHM89cLVA6xqOdNc6Xw_Content tySequence__OTmPSHM89cLVA6xqOdNc6Xw_Content;
typedef struct tyTuple__NK2MDVZxbBTjAtkh7j9amSg tyTuple__NK2MDVZxbBTjAtkh7j9amSg;
typedef struct tySequence__ccXmQYnpQYp8hJNFNWKgOw tySequence__ccXmQYnpQYp8hJNFNWKgOw;
typedef struct tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content;
typedef struct tyTuple__meXz8KXqaXZn6NTp4CbtiA tyTuple__meXz8KXqaXZn6NTp4CbtiA;
typedef struct tyTuple__IaPXXipNNRxneL9bElofXaw tyTuple__IaPXXipNNRxneL9bElofXaw;
typedef struct tyObject_SemDiagnostics__s9cjkgaAXwJ2A4T2ma8ybVQ tyObject_SemDiagnostics__s9cjkgaAXwJ2A4T2ma8ybVQ;
typedef struct tySequence__33rxC8uicqAGMtAQofD5XA tySequence__33rxC8uicqAGMtAQofD5XA;
typedef struct tySequence__33rxC8uicqAGMtAQofD5XA_Content tySequence__33rxC8uicqAGMtAQofD5XA_Content;
typedef struct tyObject_VMReport__9cjV2V6xZw5oMsSlKOLED4A tyObject_VMReport__9cjV2V6xZw5oMsSlKOLED4A;
typedef struct tySequence__MQUSH180yROiuekkk6QI9aA tySequence__MQUSH180yROiuekkk6QI9aA;
typedef struct tySequence__MQUSH180yROiuekkk6QI9aA_Content tySequence__MQUSH180yROiuekkk6QI9aA_Content;
typedef struct tyObject_CmdReport__QIY3pdocrJtxyXRhTwSNbQ tyObject_CmdReport__QIY3pdocrJtxyXRhTwSNbQ;
typedef struct tyObject_TraceSemReport__pnxILDKsfm6AbS3nnGN7DA tyObject_TraceSemReport__pnxILDKsfm6AbS3nnGN7DA;
typedef struct tyObject_DebugReportBase__XRBhv0G2cMozNtciQtiH0Q tyObject_DebugReportBase__XRBhv0G2cMozNtciQtiH0Q;
typedef struct tyObject_DebugSemStep__laQH8t8yshdcbvJOhXqYng tyObject_DebugSemStep__laQH8t8yshdcbvJOhXqYng;
typedef struct tyObject_TIdent__1LTsGP7bSxg45u9aHcxh6OA tyObject_TIdent__1LTsGP7bSxg45u9aHcxh6OA;
typedef struct tyObject_DebugCallableCandidate__HR24VKUiGRgwkLgCTzvE7Q tyObject_DebugCallableCandidate__HR24VKUiGRgwkLgCTzvE7Q;
typedef struct tyObject_SemCallMismatch__lzpDTnKatKXpERY7A0MUWQ tyObject_SemCallMismatch__lzpDTnKatKXpERY7A0MUWQ;
typedef struct tyObject_MismatchInfo__LwBm47U9cubiCjEKKB3dlpg tyObject_MismatchInfo__LwBm47U9cubiCjEKKB3dlpg;
typedef struct tyTuple__t5pUYTJfHfb434CxIRUWIA tyTuple__t5pUYTJfHfb434CxIRUWIA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_DebugReport__6BPhLQQ9b9btuq0xJYLc8HpQ tyObject_DebugReport__6BPhLQQ9b9btuq0xJYLc8HpQ;
typedef struct tyTuple__RatReAwWxXPMMhFBmq29cIQ tyTuple__RatReAwWxXPMMhFBmq29cIQ;
typedef struct tyTuple__qB8t9aA2YcKlbbhdJv0BRnA tyTuple__qB8t9aA2YcKlbbhdJv0BRnA;
typedef struct tyTuple__3k0I0pZ0kPguHeB6bsWYUA tyTuple__3k0I0pZ0kPguHeB6bsWYUA;
typedef struct tySequence__dtDa2SDVDw2K759cMbullAw tySequence__dtDa2SDVDw2K759cMbullAw;
typedef struct tySequence__dtDa2SDVDw2K759cMbullAw_Content tySequence__dtDa2SDVDw2K759cMbullAw_Content;
typedef struct tyObject_InternalReport__HuGeN0z6x5yUhxCpvY0xzQ tyObject_InternalReport__HuGeN0z6x5yUhxCpvY0xzQ;
typedef struct tyObject_UsedBuildParams__TMqAfn61JAlZvF9ck74C6Tg tyObject_UsedBuildParams__TMqAfn61JAlZvF9ck74C6Tg;
typedef struct tyObject_BackendReport__Aeq3cJBNPSxsfrr5m1bZ9aQ tyObject_BackendReport__Aeq3cJBNPSxsfrr5m1bZ9aQ;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_ExternalReport__LlCqMawGT3e4p3j1r19cVzw tyObject_ExternalReport__LlCqMawGT3e4p3j1r19cVzw;
typedef struct tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g;
typedef struct tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw;
typedef struct tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg;
typedef struct tyTuple__VG9bzDRS2xWfcorbzlcCetg tyTuple__VG9bzDRS2xWfcorbzlcCetg;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_ReportContext__9cdUZPFiTa8oC29bwVquKVIA tyObject_ReportContext__9cdUZPFiTa8oC29bwVquKVIA;
typedef struct tyObject_SemSpellCandidate__fHr8X9b5Bw9bhwYAj2BeKwTg tyObject_SemSpellCandidate__fHr8X9b5Bw9bhwYAj2BeKwTg;
typedef struct tyObject_SemNilHistory__wOol9c6O3DMCNrj3qsuWVhA tyObject_SemNilHistory__wOol9c6O3DMCNrj3qsuWVhA;
typedef struct tyTuple__yVtqew9bMKc40vHQxOBwIQw tyTuple__yVtqew9bMKc40vHQxOBwIQw;
typedef struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg tyTuple__BUNQL5x2cKJaBSzOn5pwkg;
typedef struct tyObject_SemTypeMismatch__AdPS0YshZbWRzG7gqFZXrw tyObject_SemTypeMismatch__AdPS0YshZbWRzG7gqFZXrw;
typedef struct tyObject_TAstDiag__EVmQyBtA5JqVUf0Ul4PFiA tyObject_TAstDiag__EVmQyBtA5JqVUf0Ul4PFiA;
typedef struct tyTuple__ceXH1NEaizX4m5svW3X8Vg tyTuple__ceXH1NEaizX4m5svW3X8Vg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_DebugVmCodeEntry__GFJO0aYw29a0VgGjaHz6fZg tyObject_DebugVmCodeEntry__GFJO0aYw29a0VgGjaHz6fZg;
typedef struct tyTuple__Dw8XXZJaftLunpIqlIWvSQ tyTuple__Dw8XXZJaftLunpIqlIWvSQ;
struct tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q {
NU16 line;
NI16 col;
NI32 fileIndex;
};
typedef NU8 tyEnum_ReportCategory__v6ShWUYg25AEjhKOUmGjMQ;
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tyObject_Option__cTvgZv9bZQKykpX2neAdNPw {
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q val;
NIM_BOOL has;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ {
NimStringV2 file;
NU16 line;
NI16 col;
};
struct tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA {
  RootObj Sup;
tyObject_Option__cTvgZv9bZQKykpX2neAdNPw location;
tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ reportInst;
tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ reportFrom;
};
typedef NU16 tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw;
struct tyObject_LexerReport__L2hPDucTxxu4gZoisMeavg {
  tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA Sup;
NimStringV2 msg;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ {
  tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA Sup;
NimStringV2 msg;
NimStringV2 found;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
union{
struct {tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q eqInfo;
} _kind_1;
struct {tySequence__sM4lkSb7zS6F7OVMvW9cffQ expected;
} _kind_2;
struct {NimStringV2 expectedKind;
} _kind_3;
struct {tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* node;
} _kind_5;
};
};
struct tySequence__manAeKYtb7xtYd9cz4tqm7Q {
  NI len; tySequence__manAeKYtb7xtYd9cz4tqm7Q_Content* p;
};
struct tyObject_SemishReportBase__NyQlpRjyRMr12ZU4MnrKvg {
  tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA Sup;
tySequence__manAeKYtb7xtYd9cz4tqm7Q context;
};
struct tySequence__rsh9bSgfYxIqIMIhkaVEzeA {
  NI len; tySequence__rsh9bSgfYxIqIMIhkaVEzeA_Content* p;
};
struct tySequence__XrT6wRHqo12fVwXeGBWNEw {
  NI len; tySequence__XrT6wRHqo12fVwXeGBWNEw_Content* p;
};
struct tyTuple__PnC4UDvgAKpIJAQzHfgaQw {
tySequence__XrT6wRHqo12fVwXeGBWNEw Field0;
tySequence__XrT6wRHqo12fVwXeGBWNEw Field1;
};
struct tyTuple__2Ffi2d9cS9cU3rIY5BeTYZTQ {
tyObject_Option__cTvgZv9bZQKykpX2neAdNPw Field0;
NIM_BOOL Field1;
};
struct tyTuple__OZxYMNBWbABSgGMxK14Krw {
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q Field0;
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q Field1;
};
typedef NU8 tyEnum_Nilability__dAu3xzPyX4fkhWMbu9aZVaA;
struct tySequence__TfSakS9c2WdlxOD8UIMHqRw {
  NI len; tySequence__TfSakS9c2WdlxOD8UIMHqRw_Content* p;
};
typedef NU8 tyEnum_SemGcUnsafetyKind__NosnDys6m73A9crMd6m9cUAw;
struct tyTuple__fJqtP9bt2rKczv9aqA9bUtIng {
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* Field0;
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* Field1;
tyEnum_SemGcUnsafetyKind__NosnDys6m73A9crMd6m9cUAw Field2;
};
struct tySequence__RwrnB9cL5qmp0eCG0TsP9baA {
  NI len; tySequence__RwrnB9cL5qmp0eCG0TsP9baA_Content* p;
};
struct tySequence__qlSKCH4HqXlnS9caj9cYs4Pw {
  NI len; tySequence__qlSKCH4HqXlnS9caj9cYs4Pw_Content* p;
};
struct tyTuple__ssCWuzKGoCzXuz2w3ziHXw {
tySequence__qlSKCH4HqXlnS9caj9cYs4Pw Field0;
tySequence__qlSKCH4HqXlnS9caj9cYs4Pw Field1;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NU32 tyArray__o3OkXGrjEd1h16ByV9axwjg[4];
struct tyObject_Int128__9a9axPfb75jdWY25AamJewkA {
tyArray__o3OkXGrjEd1h16ByV9axwjg udata;
};
struct tyTuple__WwoBvm9bnG5PwCLNd06V1Sw {
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* Field0;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* Field1;
};
struct tySequence__uAVKDgsmtx5N16UbHJVmFg {
  NI len; tySequence__uAVKDgsmtx5N16UbHJVmFg_Content* p;
};
struct tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ {
  NI len; tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content* p;
};
struct tyTuple__Wqzt8z13TyGtS1eBzBTVpw {
tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ Field0;
tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ Field1;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
NimStringV2 Field0;
NimStringV2 Field1;
};
struct tySequence__OTmPSHM89cLVA6xqOdNc6Xw {
  NI len; tySequence__OTmPSHM89cLVA6xqOdNc6Xw_Content* p;
};
typedef NU32 tySet_tyEnum_TSymKind__QC5XTxbIvp03IeGJbMaNmw;
typedef NU8 tyEnum_TSymKind__QC5XTxbIvp03IeGJbMaNmw;
typedef NU8 tySet_tyEnum_TTypeAllowedFlag__E9bLFzVX0Of9aj0BH7cWWq9aA;
struct tyTuple__NK2MDVZxbBTjAtkh7j9amSg {
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* Field0;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* Field1;
tyEnum_TSymKind__QC5XTxbIvp03IeGJbMaNmw Field2;
tySet_tyEnum_TTypeAllowedFlag__E9bLFzVX0Of9aj0BH7cWWq9aA Field3;
};
struct tySequence__ccXmQYnpQYp8hJNFNWKgOw {
  NI len; tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content* p;
};
struct tyTuple__meXz8KXqaXZn6NTp4CbtiA {
tyObject_Int128__9a9axPfb75jdWY25AamJewkA Field0;
tyObject_Int128__9a9axPfb75jdWY25AamJewkA Field1;
tyObject_Int128__9a9axPfb75jdWY25AamJewkA Field2;
};
struct tyTuple__IaPXXipNNRxneL9bElofXaw {
NIM_BOOL Field0;
NI Field1;
NimStringV2 Field2;
NI32 Field3;
};
struct tySequence__33rxC8uicqAGMtAQofD5XA {
  NI len; tySequence__33rxC8uicqAGMtAQofD5XA_Content* p;
};
struct tyObject_SemDiagnostics__s9cjkgaAXwJ2A4T2ma8ybVQ {
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* diagnosticsTarget;
NI tempDiagFailCount;
tySequence__33rxC8uicqAGMtAQofD5XA diags;
};
struct tyObject_SemReport__9cs8ebwB0HslUeq6PUmVoSA {
  tyObject_SemishReportBase__NyQlpRjyRMr12ZU4MnrKvg Sup;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* ast;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* typ;
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* sym;
NimStringV2 str;
tySequence__rsh9bSgfYxIqIMIhkaVEzeA spellingCandidates;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
union{
struct {tyObject_TSym__RjHO5eqpy8QqcomFydmCag* previous;
} _kind_1;
struct {tyTuple__PnC4UDvgAKpIJAQzHfgaQw arguments;
} _kind_2;
struct {tyTuple__2Ffi2d9cS9cU3rIY5BeTYZTQ missingTypeBoundElaboration;
} _kind_3;
struct {tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* overlappingGroup;
} _kind_4;
struct {tyTuple__OZxYMNBWbABSgGMxK14Krw borrowPair;
} _kind_5;
struct {tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* raisesList;
} _kind_6;
struct {tyEnum_Nilability__dAu3xzPyX4fkhWMbu9aZVaA nilIssue;
tySequence__TfSakS9c2WdlxOD8UIMHqRw nilHistory;
} _kind_7;
struct {tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* wrongNode;
} _kind_8;
struct {tyTuple__fJqtP9bt2rKczv9aqA9bUtIng gcUnsafeTrace;
} _kind_9;
struct {NimStringV2 compilerOptArg;
} _kind_10;
struct {NimStringV2 badCompilerOptArg;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ allowedOptArgs;
} _kind_11;
struct {tySequence__RwrnB9cL5qmp0eCG0TsP9baA sideEffectTrace;
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q sideEffectMutateConnection;
} _kind_12;
struct {tyTuple__ssCWuzKGoCzXuz2w3ziHXw effectListing;
} _kind_13;
struct {tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ countMismatch;
} _kind_14;
struct {tyObject_Int128__9a9axPfb75jdWY25AamJewkA expectedCount;
tyObject_Int128__9a9axPfb75jdWY25AamJewkA got;
} _kind_15;
struct {NimStringV2 externName;
} _kind_16;
struct {tySequence__sM4lkSb7zS6F7OVMvW9cffQ expectedIdents;
} _kind_17;
struct {tyTuple__WwoBvm9bnG5PwCLNd06V1Sw rangeExpression;
} _kind_18;
struct {NIM_BOOL isUnsafeAddr;
} _kind_19;
struct {tySequence__uAVKDgsmtx5N16UbHJVmFg recursiveDeps;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* notProcOrField;
NIM_BOOL explicitCall;
tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ unexpectedCandidate;
} _kind_20;
struct {tyTuple__Wqzt8z13TyGtS1eBzBTVpw fieldMismatches;
tySequence__XrT6wRHqo12fVwXeGBWNEw nodes;
} _kind_21;
struct {tyObject_TSym__RjHO5eqpy8QqcomFydmCag* ownerSym;
} _kind_22;
struct {tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ symbols;
} _kind_23;
struct {tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* expandedAst;
} _kind_24;
struct {tyObject_TSym__RjHO5eqpy8QqcomFydmCag* anotherMethod;
tyTuple__UV3llMMYFckfui8YMBuUZA lockMismatch;
} _kind_25;
struct {tySequence__OTmPSHM89cLVA6xqOdNc6Xw typeMismatch;
} _kind_26;
struct {tySet_tyEnum_TSymKind__QC5XTxbIvp03IeGJbMaNmw expectedSymbolKind;
} _kind_27;
struct {tyTuple__NK2MDVZxbBTjAtkh7j9amSg allowedType;
} _kind_28;
struct {tySequence__ccXmQYnpQYp8hJNFNWKgOw callMismatches;
} _kind_29;
struct {tyTuple__meXz8KXqaXZn6NTp4CbtiA indexSpec;
} _kind_30;
struct {tyTuple__IaPXXipNNRxneL9bElofXaw processing;
} _kind_31;
struct {tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q info;
tyTuple__UV3llMMYFckfui8YMBuUZA linterFail;
} _kind_32;
struct {tyObject_SemDiagnostics__s9cjkgaAXwJ2A4T2ma8ybVQ diag;
} _kind_33;
};
};
struct tySequence__MQUSH180yROiuekkk6QI9aA {
  NI len; tySequence__MQUSH180yROiuekkk6QI9aA_Content* p;
};
struct tyObject_VMReport__9cjV2V6xZw5oMsSlKOLED4A {
  tyObject_SemishReportBase__NyQlpRjyRMr12ZU4MnrKvg Sup;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* ast;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* typ;
NimStringV2 str;
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* sym;
tyObject_VMReport__9cjV2V6xZw5oMsSlKOLED4A* trace;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
union{
struct {tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* currentExceptionA;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* currentExceptionB;
tySequence__MQUSH180yROiuekkk6QI9aA stacktrace;
NI skipped;
} _kind_1;
struct {tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* actualType;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* formalType;
} _kind_2;
struct {tyTuple__meXz8KXqaXZn6NTp4CbtiA indexSpec;
} _kind_3;
struct {NI64 exitCode;
} _kind_4;
};
};
struct tyObject_CmdReport__QIY3pdocrJtxyXRhTwSNbQ {
  tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA Sup;
NimStringV2 cmd;
NimStringV2 msg;
NI code;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
union{
struct {NimStringV2 exitOut;
NimStringV2 exitErr;
} _kind_1;
};
};
struct tyObject_DebugReportBase__XRBhv0G2cMozNtciQtiH0Q {
  tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA Sup;
};
typedef NU8 tyEnum_DebugSemStepDirection__9b158GpwXNKIgd00MvkAozQ;
typedef NU8 tyEnum_DebugSemStepKind__DvZEE5MKoGYrZbvfE2fjcQ;
typedef NU32 tySet_tyEnum_TExprFlag__tNfQc4amozU9aJBtQSbFz4g;
typedef NU8 tyEnum_MismatchKind__Q607nFQ9bkICcQlT9c32cPwQ;
struct tyObject_MismatchInfo__LwBm47U9cubiCjEKKB3dlpg {
tyEnum_MismatchKind__Q607nFQ9bkICcQlT9c32cPwQ kind;
NI pos;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* arg;
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* formal;
};
struct tyObject_SemCallMismatch__lzpDTnKatKXpERY7A0MUWQ {
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* target;
tyObject_MismatchInfo__LwBm47U9cubiCjEKKB3dlpg firstMismatch;
tyObject_SemDiagnostics__s9cjkgaAXwJ2A4T2ma8ybVQ diag;
NIM_BOOL diagnosticsEnabled;
};
struct tyObject_DebugCallableCandidate__HR24VKUiGRgwkLgCTzvE7Q {
NimStringV2 state;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* callee;
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* calleeSym;
NI calleeScope;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* call;
tyObject_SemCallMismatch__lzpDTnKatKXpERY7A0MUWQ error;
};
struct tyObject_DebugSemStep__laQH8t8yshdcbvJOhXqYng {
tyEnum_DebugSemStepDirection__9b158GpwXNKIgd00MvkAozQ direction;
NI level;
NimStringV2 name;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* node;
tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ steppedFrom;
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* sym;
tyEnum_DebugSemStepKind__DvZEE5MKoGYrZbvfE2fjcQ kind;
union{
struct {tyObject_TIdent__1LTsGP7bSxg45u9aHcxh6OA* ident;
} _kind_1;
struct {tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* typ;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* typ1;
} _kind_2;
struct {tySet_tyEnum_TExprFlag__tNfQc4amozU9aJBtQSbFz4g flags;
} _kind_3;
struct {tySet_tyEnum_TSymKind__QC5XTxbIvp03IeGJbMaNmw filters;
tyObject_DebugCallableCandidate__HR24VKUiGRgwkLgCTzvE7Q candidate;
tySequence__ccXmQYnpQYp8hJNFNWKgOw errors;
} _kind_4;
};
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct tyTuple__t5pUYTJfHfb434CxIRUWIA {
NI Field0;
tySequence__uB9b75OUPRENsBAu4AnoePA Field1;
};
struct tyObject_TraceSemReport__pnxILDKsfm6AbS3nnGN7DA {
  tyObject_DebugReportBase__XRBhv0G2cMozNtciQtiH0Q Sup;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
union{
struct {tyObject_DebugSemStep__laQH8t8yshdcbvJOhXqYng semstep;
} _kind_1;
struct {tyTuple__t5pUYTJfHfb434CxIRUWIA ctraceData;
} _kind_2;
};
};
typedef NU32 tySet_tyEnum_TOption__SHwCAjDOxx4rq5Aq5de5Dw;
typedef NU8 tyEnum_TOpcode__KGgiFxdg81Q2wdKj9bZKfEA;
typedef NU8 tyEnum_TRegisterKind__ZPhTrModfAD8eKhjOHemOg;
struct tyTuple__RatReAwWxXPMMhFBmq29cIQ {
NI Field0;
tyEnum_TOpcode__KGgiFxdg81Q2wdKj9bZKfEA Field1;
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q Field2;
tyEnum_TRegisterKind__ZPhTrModfAD8eKhjOHemOg Field3;
tyEnum_TRegisterKind__ZPhTrModfAD8eKhjOHemOg Field4;
tyEnum_TRegisterKind__ZPhTrModfAD8eKhjOHemOg Field5;
};
struct tyTuple__qB8t9aA2YcKlbbhdJv0BRnA {
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q Field0;
tyEnum_TOpcode__KGgiFxdg81Q2wdKj9bZKfEA Field1;
};
struct tySequence__dtDa2SDVDw2K759cMbullAw {
  NI len; tySequence__dtDa2SDVDw2K759cMbullAw_Content* p;
};
struct tyTuple__3k0I0pZ0kPguHeB6bsWYUA {
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* Field0;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* Field1;
tySequence__dtDa2SDVDw2K759cMbullAw Field2;
};
struct tyObject_DebugReport__6BPhLQQ9b9btuq0xJYLc8HpQ {
  tyObject_DebugReportBase__XRBhv0G2cMozNtciQtiH0Q Sup;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
union{
struct {tySet_tyEnum_TOption__SHwCAjDOxx4rq5Aq5de5Dw optionsNow;
} _kind_1;
struct {tyTuple__RatReAwWxXPMMhFBmq29cIQ vmgenExecFull;
} _kind_2;
struct {tyTuple__qB8t9aA2YcKlbbhdJv0BRnA vmgenExecMinimal;
} _kind_3;
struct {tyTuple__3k0I0pZ0kPguHeB6bsWYUA vmgenListing;
} _kind_4;
};
};
struct tyObject_UsedBuildParams__TMqAfn61JAlZvF9ck74C6Tg {
NimStringV2 project;
NimStringV2 output;
NI linesCompiled;
NI mem;
NIM_BOOL isMaxMem;
NF sec;
NIM_BOOL isCompilation;
union{
struct {NIM_BOOL threads;
NimStringV2 backend;
NimStringV2 buildMode;
NimStringV2 optimize;
NimStringV2 gc;
} _isCompilation_1;
};
};
typedef NU8 tySet_tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw[72];
struct tyObject_InternalReport__HuGeN0z6x5yUhxCpvY0xzQ {
  tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA Sup;
NimStringV2 msg;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
union{
struct {tySequence__uB9b75OUPRENsBAu4AnoePA trace;
} _kind_1;
struct {NimStringV2 expression;
} _kind_2;
struct {tyObject_UsedBuildParams__TMqAfn61JAlZvF9ck74C6Tg buildParams;
} _kind_3;
struct {NimStringV2 file;
} _kind_4;
struct {tySet_tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw enabledOptions;
} _kind_5;
};
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
NimStringV2 Field0;
NimStringV2 Field1;
NimStringV2 Field2;
};
struct tyObject_BackendReport__Aeq3cJBNPSxsfrr5m1bZ9aQ {
  tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA Sup;
NimStringV2 msg;
NimStringV2 usedCompiler;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
union{
struct {NimStringV2 filename;
} _kind_1;
struct {NimStringV2 requestedTarget;
} _kind_2;
struct {tyTuple__7q7q3E6Oj24ZNVJb9aonhAg jsonScriptParams;
} _kind_3;
struct {NimStringV2 outFilename;
NimStringV2 failureMsg;
} _kind_4;
};
};
struct tyObject_ExternalReport__LlCqMawGT3e4p3j1r19cVzw {
  tyObject_ReportBase__cODuAQhQzLWogsorHGr7HA Sup;
NimStringV2 msg;
tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw kind;
};
struct tyObject_Report__45JukV4U6A1QELeWVCpPkg {
tyEnum_ReportCategory__v6ShWUYg25AEjhKOUmGjMQ category;
union{
struct {tyObject_LexerReport__L2hPDucTxxu4gZoisMeavg lexReport;
} _category_1;
struct {tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ parserReport;
} _category_2;
struct {tyObject_SemReport__9cs8ebwB0HslUeq6PUmVoSA semReport;
} _category_3;
struct {tyObject_VMReport__9cjV2V6xZw5oMsSlKOLED4A vmReport;
} _category_4;
struct {tyObject_CmdReport__QIY3pdocrJtxyXRhTwSNbQ cmdReport;
} _category_5;
struct {tyObject_TraceSemReport__pnxILDKsfm6AbS3nnGN7DA dbgTraceReport;
} _category_6;
struct {tyObject_DebugReport__6BPhLQQ9b9btuq0xJYLc8HpQ debugReport;
} _category_7;
struct {tyObject_InternalReport__HuGeN0z6x5yUhxCpvY0xzQ internalReport;
} _category_8;
struct {tyObject_BackendReport__Aeq3cJBNPSxsfrr5m1bZ9aQ backendReport;
} _category_9;
struct {tyObject_ExternalReport__LlCqMawGT3e4p3j1r19cVzw externalReport;
} _category_10;
};
};
typedef NU8 tyEnum_TParseState__TMyoReN7VAtsUpVF9bL9cXRQ;
struct tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg {
tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* inp;
tyEnum_TParseState__TMyoReN7VAtsUpVF9bL9cXRQ state;
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q info;
NI indent;
NI emitPar;
NimStringV2 x;
tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* outp;
NIM_CHAR subsChar;
NIM_CHAR nimDirective;
NimStringV2 emit;
NimStringV2 conc;
NimStringV2 toStr;
NI curly;
NI bracket;
NI par;
NIM_BOOL pendingExprLine;
tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* config;
};
struct tyTuple__VG9bzDRS2xWfcorbzlcCetg {
NU16 Field0;
NI16 Field1;
};
typedef NU8 tyEnum_TLLStreamKind__jVcKY16LbOamXE9bxXUD6pQ;
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* s, void* buf, NI bufLen, void* ClE_0);
void* ClE_0;
} tyProc__vqN8F2I9cNb9agHf5QUpC2lg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__IIomJ6ptE6vfJ5zRbATgkQ;
struct tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g {
  RootObj Sup;
tyEnum_TLLStreamKind__jVcKY16LbOamXE9bxXUD6pQ kind;
FILE* f;
NimStringV2 s;
NI rd;
NI wr;
NI lineOffset;
tyProc__vqN8F2I9cNb9agHf5QUpC2lg repl;
tyProc__IIomJ6ptE6vfJ5zRbATgkQ onPrompt;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_TErrorHandling__NYD6anka6eDByYBQZzk1Uw;
struct tyTuple__kN8up2W6YKc5YA9avn5mV5w {
NimStringV2 Field0;
NI Field1;
NI Field2;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
NI rootIdx;
};


#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tyEnum_ReportContextKind__BVTIfJdoxlRZKCchlKaXGQ;
struct tyObject_ReportContext__9cdUZPFiTa8oC29bwVquKVIA {
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q location;
tyEnum_ReportContextKind__BVTIfJdoxlRZKCchlKaXGQ kind;
union{
struct {tyObject_TSym__RjHO5eqpy8QqcomFydmCag* entry;
} _kind_1;
};
};


#ifndef tySequence__manAeKYtb7xtYd9cz4tqm7Q_Content_PP
#define tySequence__manAeKYtb7xtYd9cz4tqm7Q_Content_PP
struct tySequence__manAeKYtb7xtYd9cz4tqm7Q_Content { NI cap; tyObject_ReportContext__9cdUZPFiTa8oC29bwVquKVIA data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_SemSpellCandidate__fHr8X9b5Bw9bhwYAj2BeKwTg {
NI dist;
NI depth;
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* sym;
NIM_BOOL isLocal;
};


#ifndef tySequence__rsh9bSgfYxIqIMIhkaVEzeA_Content_PP
#define tySequence__rsh9bSgfYxIqIMIhkaVEzeA_Content_PP
struct tySequence__rsh9bSgfYxIqIMIhkaVEzeA_Content { NI cap; tyObject_SemSpellCandidate__fHr8X9b5Bw9bhwYAj2BeKwTg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__XrT6wRHqo12fVwXeGBWNEw_Content_PP
#define tySequence__XrT6wRHqo12fVwXeGBWNEw_Content_PP
struct tySequence__XrT6wRHqo12fVwXeGBWNEw_Content { NI cap; tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tyEnum_NilTransition__A9c1I8RC2cUSTq3Q7HDwLjA;
struct tyObject_SemNilHistory__wOol9c6O3DMCNrj3qsuWVhA {
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q info;
tyEnum_Nilability__dAu3xzPyX4fkhWMbu9aZVaA nilability;
tyEnum_NilTransition__A9c1I8RC2cUSTq3Q7HDwLjA kind;
tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* node;
};


#ifndef tySequence__TfSakS9c2WdlxOD8UIMHqRw_Content_PP
#define tySequence__TfSakS9c2WdlxOD8UIMHqRw_Content_PP
struct tySequence__TfSakS9c2WdlxOD8UIMHqRw_Content { NI cap; tyObject_SemNilHistory__wOol9c6O3DMCNrj3qsuWVhA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tyEnum_SemSideEffectCallKind__Q2edt53q9cQ9aX2kyM2GRj6g;
struct tyTuple__yVtqew9bMKc40vHQxOBwIQw {
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* Field0;
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* Field1;
tyEnum_SemSideEffectCallKind__Q2edt53q9cQ9aX2kyM2GRj6g Field2;
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q Field3;
NI Field4;
};


#ifndef tySequence__RwrnB9cL5qmp0eCG0TsP9baA_Content_PP
#define tySequence__RwrnB9cL5qmp0eCG0TsP9baA_Content_PP
struct tySequence__RwrnB9cL5qmp0eCG0TsP9baA_Content { NI cap; tyTuple__yVtqew9bMKc40vHQxOBwIQw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__qlSKCH4HqXlnS9caj9cYs4Pw_Content_PP
#define tySequence__qlSKCH4HqXlnS9caj9cYs4Pw_Content_PP
struct tySequence__qlSKCH4HqXlnS9caj9cYs4Pw_Content { NI cap; tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg {
NI32 Field0;
NI32 Field1;
};


#ifndef tySequence__uAVKDgsmtx5N16UbHJVmFg_Content_PP
#define tySequence__uAVKDgsmtx5N16UbHJVmFg_Content_PP
struct tySequence__uAVKDgsmtx5N16UbHJVmFg_Content { NI cap; tyTuple__BUNQL5x2cKJaBSzOn5pwkg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content_PP
#define tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content_PP
struct tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content { NI cap; tyObject_TSym__RjHO5eqpy8QqcomFydmCag* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__XrT6wRHqo12fVwXeGBWNEw_Content_PP
#define tySequence__XrT6wRHqo12fVwXeGBWNEw_Content_PP
struct tySequence__XrT6wRHqo12fVwXeGBWNEw_Content { NI cap; tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content_PP
#define tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content_PP
struct tySequence__HcU4JPvo8W9b4LVr8K7AE9bQ_Content { NI cap; tyObject_TSym__RjHO5eqpy8QqcomFydmCag* data[SEQ_DECL_SIZE];};
#endif

      typedef NU64 tySet_tyEnum_TTypeKind__Ex3wVg8tydC7H9bvpU9cYPRg;
struct tyObject_SemTypeMismatch__AdPS0YshZbWRzG7gqFZXrw {
tySet_tyEnum_TTypeKind__Ex3wVg8tydC7H9bvpU9cYPRg formalTypeKind;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* actualType;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* formalType;
};


#ifndef tySequence__OTmPSHM89cLVA6xqOdNc6Xw_Content_PP
#define tySequence__OTmPSHM89cLVA6xqOdNc6Xw_Content_PP
struct tySequence__OTmPSHM89cLVA6xqOdNc6Xw_Content { NI cap; tyObject_SemTypeMismatch__AdPS0YshZbWRzG7gqFZXrw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content_PP
#define tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content_PP
struct tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content { NI cap; tyObject_SemCallMismatch__lzpDTnKatKXpERY7A0MUWQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__33rxC8uicqAGMtAQofD5XA_Content_PP
#define tySequence__33rxC8uicqAGMtAQofD5XA_Content_PP
struct tySequence__33rxC8uicqAGMtAQofD5XA_Content { NI cap; tyObject_TAstDiag__EVmQyBtA5JqVUf0Ul4PFiA* data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__ceXH1NEaizX4m5svW3X8Vg {
tyObject_TSym__RjHO5eqpy8QqcomFydmCag* Field0;
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q Field1;
};


#ifndef tySequence__MQUSH180yROiuekkk6QI9aA_Content_PP
#define tySequence__MQUSH180yROiuekkk6QI9aA_Content_PP
struct tySequence__MQUSH180yROiuekkk6QI9aA_Content { NI cap; tyTuple__ceXH1NEaizX4m5svW3X8Vg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content_PP
#define tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content_PP
struct tySequence__ccXmQYnpQYp8hJNFNWKgOw_Content { NI cap; tyObject_SemCallMismatch__lzpDTnKatKXpERY7A0MUWQ data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__Dw8XXZJaftLunpIqlIWvSQ {
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* Field0;
tyObject_TType__9bxl8e9cDuDwfQRcyh9cQYOlQ* Field1;
};
struct tyObject_DebugVmCodeEntry__GFJO0aYw29a0VgGjaHz6fZg {
NIM_BOOL isTarget;
tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q info;
NI pc;
NI idx;
tyEnum_TOpcode__KGgiFxdg81Q2wdKj9bZKfEA opc;
union{
struct {tyTuple__Dw8XXZJaftLunpIqlIWvSQ types;
} _opc_1;
struct {tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* ast;
} _opc_2;
};
NI ra;
NI rb;
NI rc;
};


#ifndef tySequence__dtDa2SDVDw2K759cMbullAw_Content_PP
#define tySequence__dtDa2SDVDw2K759cMbullAw_Content_PP
struct tySequence__dtDa2SDVDw2K759cMbullAw_Content { NI cap; tyObject_DebugVmCodeEntry__GFJO0aYw29a0VgGjaHz6fZg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, wrap__astZfilter95tmpl_111)(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ* rep, tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ iinfo, tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q point, tyObject_Report__45JukV4U6A1QELeWVCpPkg* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___astZreports_429)(tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ* dest, tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ src);
static N_INLINE(tyObject_Option__cTvgZv9bZQKykpX2neAdNPw, some__frontZmsgs_940)(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q val);
N_LIB_PRIVATE N_NIMCALL(void, wrap__astZreports_539)(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ* rep, tyObject_Report__45JukV4U6A1QELeWVCpPkg* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___astZreports_553)(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ, toReportLineInfo__astZreports_494)(tyTuple__kN8up2W6YKc5YA9avn5mV5w* iinfo);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___astZreports_426)(tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___frontZoptions_5582)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw** dest, tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* src);
static N_INLINE(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q, newLineInfo__frontZoptions_7556)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* conf, NimStringV2 filename, NI line, NI col);
static N_INLINE(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q, newLineInfo__astZlineinfos_58)(NI32 fileIndex, NI line, NI col);
static N_INLINE(tyTuple__VG9bzDRS2xWfcorbzlcCetg, clampLineCol__astZlineinfos_42)(NI line, NI col);
N_LIB_PRIVATE N_NIMCALL(NI32, fileInfoIdx__frontZoptions_7551)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* conf, NimStringV2 filename);
N_LIB_PRIVATE N_NIMCALL(tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g*, llStreamOpen__astZllstream_30)(NimStringV2 data);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___astZllstream_70)(tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g** dest, tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* src, NIM_BOOL cyclic);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, charArg__astZfilters_64)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* conf, tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* n, NimStringV2 name, NI pos, NIM_CHAR default_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, strArg__astZfilters_80)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* conf, tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* n, NimStringV2 name, NI pos, NimStringV2 default_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, llStreamReadLine__astZllstream_247)(tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* s, NimStringV2* line);
N_LIB_PRIVATE N_NIMCALL(void, parseLine__astZfilter95tmpl_74)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* p);
N_LIB_PRIVATE N_NIMCALL(void, newLine__astZfilter95tmpl_36)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* p);
N_LIB_PRIVATE N_NIMCALL(void, llStreamWrite__astZllstream_267)(tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* s, NimStringV2 data);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c, NI count);
static N_INLINE(NimStringV2, spaces__pureZstrutils_1070)(NI n);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3228)(NimStringV2* dest);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, scanPar__astZfilter95tmpl_38)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* p, NI d);
static N_INLINE(NIM_BOOL, withInExpr__astZfilter95tmpl_70)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* p);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, endsWith__astZllstream_169)(NimStringV2 x, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_BOOL, equalMem__system_1716)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, hashString)(NimStringV2 s);
N_LIB_PRIVATE N_NOINLINE(void, handleReport__frontZmsgs_789)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* conf, tyObject_Report__45JukV4U6A1QELeWVCpPkg* r, tyTuple__kN8up2W6YKc5YA9avn5mV5w* reportFrom, tyEnum_TErrorHandling__NYD6anka6eDByYBQZzk1Uw eh);
N_LIB_PRIVATE N_NIMCALL(void, wrap__astZfilter95tmpl_105)(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ* rep, tyTuple__kN8up2W6YKc5YA9avn5mV5w* iinfo, tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q point, tyObject_Report__45JukV4U6A1QELeWVCpPkg* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___astZreports_69)(tyObject_Report__45JukV4U6A1QELeWVCpPkg* dest);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_7587)(NimStringV2 s, NI first);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_1697)(NimStringV2 s, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__pureZstrutils_1860)(NI x, NI len);
N_LIB_PRIVATE N_NIMCALL(void, llStreamWrite__astZllstream_277)(tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* s, NIM_CHAR data);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(void, llStreamClose__astZllstream_163)(tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___astZfilter95tmpl_244)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___system_704)(NI x, NI y);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3163)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___frontZoptions_5215)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* dest);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
extern TNimTypeV2 NTIv2__1OmQ9azeiSS0eiHRtur56eQ_;
static NIM_CONST tyObject_Report__45JukV4U6A1QELeWVCpPkg TM__paI0W78l0CRDBLjAHJxn6w_2 = {0, {._category_2 = {{{{(&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_)}, {{0, 0, 0}, NIM_FALSE}, {{0, NIM_NIL}, 0, 0}, {{0, NIM_NIL}, 0, 0}}, {0, NIM_NIL}, {0, NIM_NIL}, 0, {}}}}}
;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__paI0W78l0CRDBLjAHJxn6w_3 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_4 = {0, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_3};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__paI0W78l0CRDBLjAHJxn6w_5 = { 8 | NIM_STRLIT_FLAG, "subschar" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_6 = {8, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_5};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__paI0W78l0CRDBLjAHJxn6w_7 = { 8 | NIM_STRLIT_FLAG, "metachar" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_8 = {8, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_7};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_9 = { 4 | NIM_STRLIT_FLAG, "emit" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_10 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_9};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__paI0W78l0CRDBLjAHJxn6w_11 = { 10 | NIM_STRLIT_FLAG, "result.add" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_12 = {10, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_11};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_13 = { 4 | NIM_STRLIT_FLAG, "conc" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_14 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_13};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__paI0W78l0CRDBLjAHJxn6w_15 = { 3 | NIM_STRLIT_FLAG, " & " };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_16 = {3, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_15};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__paI0W78l0CRDBLjAHJxn6w_17 = { 8 | NIM_STRLIT_FLAG, "tostring" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_18 = {8, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_17};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__paI0W78l0CRDBLjAHJxn6w_19 = { 1 | NIM_STRLIT_FLAG, "$" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_20 = {1, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_19};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__paI0W78l0CRDBLjAHJxn6w_21 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_22 = {1, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_21};
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_23 = {0, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_3};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__paI0W78l0CRDBLjAHJxn6w_24 = {
0x00, 0x00, 0x00, 0x00, 0x70, 0xbc, 0x00, 0x50,
0x01, 0x00, 0x00, 0x50, 0x00, 0x00, 0x00, 0x50,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__paI0W78l0CRDBLjAHJxn6w_25 = { 3 | NIM_STRLIT_FLAG, "end" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_26 = {3, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_25};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__paI0W78l0CRDBLjAHJxn6w_27 = { 2 | NIM_STRLIT_FLAG, "if" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_28 = {2, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_27};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_29 = { 4 | NIM_STRLIT_FLAG, "when" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_30 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_29};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__paI0W78l0CRDBLjAHJxn6w_31 = { 3 | NIM_STRLIT_FLAG, "try" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_32 = {3, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_31};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__paI0W78l0CRDBLjAHJxn6w_33 = { 5 | NIM_STRLIT_FLAG, "while" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_34 = {5, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_33};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__paI0W78l0CRDBLjAHJxn6w_35 = { 3 | NIM_STRLIT_FLAG, "for" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_36 = {3, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_35};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__paI0W78l0CRDBLjAHJxn6w_37 = { 5 | NIM_STRLIT_FLAG, "block" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_38 = {5, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_37};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_39 = { 4 | NIM_STRLIT_FLAG, "case" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_40 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_39};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_41 = { 4 | NIM_STRLIT_FLAG, "proc" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_42 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_41};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__paI0W78l0CRDBLjAHJxn6w_43 = { 8 | NIM_STRLIT_FLAG, "iterator" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_44 = {8, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_43};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__paI0W78l0CRDBLjAHJxn6w_45 = { 9 | NIM_STRLIT_FLAG, "converter" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_46 = {9, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_45};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__paI0W78l0CRDBLjAHJxn6w_47 = { 5 | NIM_STRLIT_FLAG, "macro" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_48 = {5, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_47};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__paI0W78l0CRDBLjAHJxn6w_49 = { 8 | NIM_STRLIT_FLAG, "template" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_50 = {8, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_49};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__paI0W78l0CRDBLjAHJxn6w_51 = { 6 | NIM_STRLIT_FLAG, "method" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_52 = {6, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_51};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_53 = { 4 | NIM_STRLIT_FLAG, "func" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_54 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_53};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_55 = { 4 | NIM_STRLIT_FLAG, "elif" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_56 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_55};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__paI0W78l0CRDBLjAHJxn6w_57 = { 2 | NIM_STRLIT_FLAG, "of" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_58 = {2, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_57};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_59 = { 4 | NIM_STRLIT_FLAG, "else" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_60 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_59};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__paI0W78l0CRDBLjAHJxn6w_61 = { 6 | NIM_STRLIT_FLAG, "except" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_62 = {6, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_61};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__paI0W78l0CRDBLjAHJxn6w_63 = { 7 | NIM_STRLIT_FLAG, "finally" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_64 = {7, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_63};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__paI0W78l0CRDBLjAHJxn6w_65 = { 3 | NIM_STRLIT_FLAG, "let" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_66 = {3, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_65};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__paI0W78l0CRDBLjAHJxn6w_67 = { 3 | NIM_STRLIT_FLAG, "var" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_68 = {3, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_67};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__paI0W78l0CRDBLjAHJxn6w_69 = { 5 | NIM_STRLIT_FLAG, "const" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_70 = {5, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_69};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_71 = { 4 | NIM_STRLIT_FLAG, "type" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_72 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_71};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__paI0W78l0CRDBLjAHJxn6w_74 = { 15 | NIM_STRLIT_FLAG, "filter_tmpl.nim" };
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__paI0W78l0CRDBLjAHJxn6w_73 = {{15, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_74},
((NI) 106),
((NI) 16)}
;
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__paI0W78l0CRDBLjAHJxn6w_75 = { 4 | NIM_STRLIT_FLAG, "#end" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_76 = {4, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_75};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__paI0W78l0CRDBLjAHJxn6w_77 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x24,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_78 = {1, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_21};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__paI0W78l0CRDBLjAHJxn6w_79 = { 1 | NIM_STRLIT_FLAG, "\"" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_80 = {1, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_79};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__paI0W78l0CRDBLjAHJxn6w_81 = { 2 | NIM_STRLIT_FLAG, "(\"" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_82 = {2, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_81};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__paI0W78l0CRDBLjAHJxn6w_83 = { 2 | NIM_STRLIT_FLAG, "\\x" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_84 = {2, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_83};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__paI0W78l0CRDBLjAHJxn6w_85 = { 2 | NIM_STRLIT_FLAG, "\\\\" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_86 = {2, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_85};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__paI0W78l0CRDBLjAHJxn6w_87 = { 2 | NIM_STRLIT_FLAG, "\\\'" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_88 = {2, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_87};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__paI0W78l0CRDBLjAHJxn6w_89 = { 2 | NIM_STRLIT_FLAG, "\\\"" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_90 = {2, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_89};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__paI0W78l0CRDBLjAHJxn6w_91 = { 1 | NIM_STRLIT_FLAG, "}" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_92 = {1, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_91};
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__paI0W78l0CRDBLjAHJxn6w_93 = {{15, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_74},
((NI) 191),
((NI) 22)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__paI0W78l0CRDBLjAHJxn6w_94 = {{15, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_74},
((NI) 214),
((NI) 22)}
;
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__paI0W78l0CRDBLjAHJxn6w_95 = { 3 | NIM_STRLIT_FLAG, "\\n\"" };
static const NimStringV2 TM__paI0W78l0CRDBLjAHJxn6w_96 = {3, (NimStrPayload*)&TM__paI0W78l0CRDBLjAHJxn6w_95};
extern NIM_BOOL nimInErrorMode__system_4174;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
	(void)(T1_);
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(tyObject_Option__cTvgZv9bZQKykpX2neAdNPw, some__frontZmsgs_940)(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q val) {
	tyObject_Option__cTvgZv9bZQKykpX2neAdNPw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__cTvgZv9bZQKykpX2neAdNPw));
	result.has = NIM_TRUE;
	result.val = val;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4174);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, wrap__astZfilter95tmpl_111)(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ* rep, tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ iinfo, tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q point, tyObject_Report__45JukV4U6A1QELeWVCpPkg* Result) {
	tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ colontmp_;
	tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ tmp;
	tyObject_Option__cTvgZv9bZQKykpX2neAdNPw T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_Report__45JukV4U6A1QELeWVCpPkg));
	(*Result) = TM__paI0W78l0CRDBLjAHJxn6w_2;
	nimZeroMem((void*)(&colontmp_), sizeof(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ));
	colontmp_.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
	nimZeroMem((void*)(&tmp), sizeof(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ));
	tmp.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
	tmp = (*rep);
	eqcopy___astZreports_429((&tmp.Sup.reportInst), iinfo);
	nimZeroMem((void*)(&T2_), sizeof(tyObject_Option__cTvgZv9bZQKykpX2neAdNPw));
	T2_ = some__frontZmsgs_940(point);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	tmp.Sup.location = T2_;
	colontmp_ = tmp;
	nimZeroMem((void*)(&tmp), sizeof(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ));
	tmp.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
	wrap__astZreports_539((&colontmp_), Result);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___astZreports_553((&tmp));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___astZreports_553((&tmp));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, wrap__astZfilter95tmpl_105)(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ* rep, tyTuple__kN8up2W6YKc5YA9avn5mV5w* iinfo, tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q point, tyObject_Report__45JukV4U6A1QELeWVCpPkg* Result) {
	tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ colontmp_;
	tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ colontmp__2;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_Report__45JukV4U6A1QELeWVCpPkg));
	(*Result) = TM__paI0W78l0CRDBLjAHJxn6w_2;
	nimZeroMem((void*)(&colontmp_), sizeof(tyObject_ReportLineInfo__pgZ26CllG5ZGoZyiNZp9aHQ));
	colontmp__2 = toReportLineInfo__astZreports_494(iinfo);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmp_ = colontmp__2;
	wrap__astZfilter95tmpl_111(rep, colontmp_, point, Result);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___astZreports_426((&colontmp_));
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyTuple__VG9bzDRS2xWfcorbzlcCetg, clampLineCol__astZlineinfos_42)(NI line, NI col) {
	tyTuple__VG9bzDRS2xWfcorbzlcCetg result;
	nimZeroMem((void*)(&result), sizeof(tyTuple__VG9bzDRS2xWfcorbzlcCetg));
	{
		{
			if (!(line < ((NI) 65535))) goto LA4_;
			result.Field0 = ((NU16) (line));
			goto LA1;
		}
		LA4_: ;
		result.Field0 = ((NU16) 65535);
	} LA1: ;
	{
		{
			if (!(col < ((NI) 32767))) goto LA9_;
			result.Field1 = ((NI16) (col));
			goto LA6;
		}
		LA9_: ;
		result.Field1 = ((NI16) -1);
	} LA6: ;
	return result;
}
static N_INLINE(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q, newLineInfo__astZlineinfos_58)(NI32 fileIndex, NI line, NI col) {
	tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q result;
	tyTuple__VG9bzDRS2xWfcorbzlcCetg colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q));
	result.fileIndex = fileIndex;
	colontmp_ = clampLineCol__astZlineinfos_42(line, col);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.line = colontmp_.Field0;
	result.col = colontmp_.Field1;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q, newLineInfo__frontZoptions_7556)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* conf, NimStringV2 filename, NI line, NI col) {
	tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q result;
	NI32 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q));
	T1_ = (NI32)0;
	T1_ = fileInfoIdx__frontZoptions_7551(conf, filename);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = newLineInfo__astZlineinfos_58(T1_, line, col);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NimStringV2, spaces__pureZstrutils_1070)(NI n) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = nsuRepeatChar(32, n);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, newLine__astZfilter95tmpl_36)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* p) {
	NimStringV2 colontmp_;
	NimStringV2 colontmp__2;
NIM_BOOL oldNimErrFin10_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmp_.len = 0; colontmp_.p = NIM_NIL;
	colontmp__2 = nsuRepeatChar(41, ((NI) ((*p).emitPar)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmp_ = colontmp__2;
	llStreamWrite__astZllstream_267((*p).outp, colontmp_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*p).emitPar = ((NI) 0);
	{
		if (!((NU16)(((NU16) 1)) < (NU16)((*p).info.line))) goto LA4_;
		llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_22);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA4_: ;
	{
		NimStringV2 colontmp__3;
		NimStringV2 colontmp__4;
		if (!(*p).pendingExprLine) goto LA8_;
		colontmp__3.len = 0; colontmp__3.p = NIM_NIL;
		colontmp__4 = spaces__pureZstrutils_1070(((NI) 2));
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		colontmp__3 = colontmp__4;
		llStreamWrite__astZllstream_267((*p).outp, colontmp__3);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		(*p).pendingExprLine = NIM_FALSE;
		{
			LA10_:;
		}
		{
			oldNimErrFin10_ = *nimErr_; *nimErr_ = NIM_FALSE;
			eqdestroy___system_3228((&colontmp__3));
			*nimErr_ = oldNimErrFin10_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA8_: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___system_3228((&colontmp_));
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {
	prepareAdd(s, ((NI) 1));
	(*(*s).p).data[(*s).len] = c;
	(*(*s).p).data[(NI)((*s).len + ((NI) 1))] = 0;
	(*s).len += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, scanPar__astZfilter95tmpl_38)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* p, NI d) {
	NI i;
	i = d;
	{
		while (1) {
			{
				if (!!((i < (*p).x.len))) goto LA5_;
				goto LA2;
			}
			LA5_: ;
			switch (((NU8)((*p).x.p->data[i]))) {
			case 40:
			{
				(*p).par += ((NI) 1);
			}
			break;
			case 41:
			{
				(*p).par -= ((NI) 1);
			}
			break;
			case 91:
			{
				(*p).bracket += ((NI) 1);
			}
			break;
			case 93:
			{
				(*p).bracket -= ((NI) 1);
			}
			break;
			case 123:
			{
				(*p).curly += ((NI) 1);
			}
			break;
			case 125:
			{
				(*p).curly -= ((NI) 1);
			}
			break;
			default:
			{
			}
			break;
			}
			i += ((NI) 1);
		} LA2: ;
	}
}
static N_INLINE(NIM_BOOL, withInExpr__astZfilter95tmpl_70)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* p) {
	NIM_BOOL result;
	NIM_BOOL colontmp_;
	NIM_BOOL colontmp__2;
	result = (NIM_BOOL)0;
	colontmp_ = (NIM_BOOL)0;
	colontmp__2 = (NIM_BOOL)0;
	{
		{
			colontmp__2 = (((NI) 0) < (*p).par);
			{
				if (!colontmp__2) goto LA5_;
				goto LA2;
			}
			LA5_: ;
			colontmp__2 = (((NI) 0) < (*p).bracket);
		} LA2: ;
		colontmp_ = colontmp__2;
		{
			if (!colontmp_) goto LA9_;
			goto LA1;
		}
		LA9_: ;
		colontmp_ = (((NI) 0) < (*p).curly);
	} LA1: ;
	result = colontmp_;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1716)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = a.len;
	blen = b.len;
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem__system_1716(((void*) ((&a.p->data[((NI) 0)]))), ((void*) ((&b.p->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, parseLine__astZfilter95tmpl_74)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* p) {
	NIM_BOOL colontmp_;
	NI j;
	NI len;
NIM_BOOL oldNimErrFin77_;
NIM_BOOL oldNimErrFin71_;
NIM_BOOL oldNimErrFin84_;
NIM_BOOL oldNimErrFin88_;
NIM_BOOL oldNimErrFin92_;
NIM_BOOL oldNimErrFin101_;
NIM_BOOL oldNimErrFin36_;
NIM_BOOL oldNimErrFin107_;
NIM_BOOL oldNimErrFin111_;
NIM_BOOL oldNimErrFin121_;
NIM_BOOL oldNimErrFin155_;
NIM_BOOL oldNimErrFin177_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmp_ = (NIM_BOOL)0;
	j = ((NI) 0);
	len = (*p).x.len;
	{
		while (1) {
			NIM_BOOL colontmp__2;
			colontmp__2 = (NIM_BOOL)0;
			{
				colontmp__2 = (j < len);
				{
					if (!!(colontmp__2)) goto LA6_;
					goto LA3;
				}
				LA6_: ;
				colontmp__2 = ((NU8)((*p).x.p->data[j]) == (NU8)(32));
			} LA3: ;
			{
				if (!!(colontmp__2)) goto LA10_;
				goto LA2;
			}
			LA10_: ;
			j += ((NI) 1);
		} LA2: ;
	}
	{
		NIM_BOOL colontmp__3;
		NIM_BOOL colontmp__4;
		colontmp__3 = (NIM_BOOL)0;
		{
			{
				colontmp_ = (((NI) 2) <= len);
				{
					if (!!(colontmp_)) goto LA17_;
					goto LA14;
				}
				LA17_: ;
				colontmp_ = ((NU8)((*p).x.p->data[((NI) 0)]) == (NU8)((*p).nimDirective));
			} LA14: ;
			colontmp__3 = colontmp_;
			{
				if (!!(colontmp__3)) goto LA21_;
				goto LA13;
			}
			LA21_: ;
			colontmp__3 = ((NU8)((*p).x.p->data[((NI) 1)]) == (NU8)(63));
		} LA13: ;
		{
			if (!colontmp__3) goto LA25_;
			newLine__astZfilter95tmpl_36(p);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA12;
		}
		LA25_: ;
		colontmp__4 = (NIM_BOOL)0;
		{
			colontmp__4 = (j < len);
			{
				if (!!(colontmp__4)) goto LA30_;
				goto LA27;
			}
			LA30_: ;
			colontmp__4 = ((NU8)((*p).x.p->data[j]) == (NU8)((*p).nimDirective));
		} LA27: ;
		{
			NIM_BOOL colontmp__5;
			NimStringV2 keyw;
			NI d;
			if (!colontmp__4) goto LA34_;
			colontmp__5 = (NIM_BOOL)0;
			keyw.len = 0; keyw.p = NIM_NIL;
			newLine__astZfilter95tmpl_36(p);
			if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			j += ((NI) 1);
			{
				while (1) {
					NIM_BOOL colontmp__6;
					colontmp__6 = (NIM_BOOL)0;
					{
						colontmp__6 = (j < len);
						{
							if (!!(colontmp__6)) goto LA42_;
							goto LA39;
						}
						LA42_: ;
						colontmp__6 = ((NU8)((*p).x.p->data[j]) == (NU8)(32));
					} LA39: ;
					{
						if (!!(colontmp__6)) goto LA46_;
						goto LA38;
					}
					LA46_: ;
					j += ((NI) 1);
				} LA38: ;
			}
			d = j;
			keyw = TM__paI0W78l0CRDBLjAHJxn6w_23;
			{
				while (1) {
					NIM_BOOL colontmp__7;
					colontmp__7 = (NIM_BOOL)0;
					{
						colontmp__7 = (j < len);
						{
							if (!!(colontmp__7)) goto LA53_;
							goto LA50;
						}
						LA53_: ;
						colontmp__7 = (((NU8)((*p).x.p->data[j])) >= ((NU8)(97)) && ((NU8)((*p).x.p->data[j])) <= ((NU8)(122)) || ((NU8)((*p).x.p->data[j])) >= ((NU8)(65)) && ((NU8)((*p).x.p->data[j])) <= ((NU8)(90)) || ((NU8)((*p).x.p->data[j])) >= ((NU8)(48)) && ((NU8)((*p).x.p->data[j])) <= ((NU8)(57)) || ((NU8)((*p).x.p->data[j])) >= ((NU8)(128)) && ((NU8)((*p).x.p->data[j])) <= ((NU8)(255)) || ((NU8)((*p).x.p->data[j])) == ((NU8)(46)) || ((NU8)((*p).x.p->data[j])) == ((NU8)(95)));
					} LA50: ;
					{
						if (!!(colontmp__7)) goto LA57_;
						goto LA49;
					}
					LA57_: ;
					nimAddCharV1((&keyw), (*p).x.p->data[j]);
					j += ((NI) 1);
				} LA49: ;
			}
			scanPar__astZfilter95tmpl_38(p, j);
			if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			{
				colontmp__5 = withInExpr__astZfilter95tmpl_70((&(*p)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
				{
					if (!colontmp__5) goto LA62_;
					goto LA59;
				}
				LA62_: ;
				colontmp__5 = endsWith__astZllstream_169((*p).x, TM__paI0W78l0CRDBLjAHJxn6w_24);
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			} LA59: ;
			(*p).pendingExprLine = colontmp__5;
			switch (hashString(keyw) & 31) {
			case 1: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_34)) goto LA65_;
break;
			case 3: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_58)) goto LA66_;
break;
			case 6: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_40)) goto LA65_;
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_48)) goto LA65_;
break;
			case 7: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_28)) goto LA65_;
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_52)) goto LA65_;
break;
			case 9: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_62)) goto LA66_;
break;
			case 10: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_42)) goto LA65_;
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_66)) goto LA67_;
break;
			case 12: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_68)) goto LA67_;
break;
			case 16: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_30)) goto LA65_;
break;
			case 17: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_44)) goto LA65_;
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_56)) goto LA66_;
break;
			case 18: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_50)) goto LA65_;
break;
			case 19: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_36)) goto LA65_;
break;
			case 21: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_60)) goto LA66_;
break;
			case 23: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_26)) goto LA64_;
break;
			case 24: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_46)) goto LA65_;
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_64)) goto LA66_;
break;
			case 26: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_70)) goto LA67_;
break;
			case 27: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_32)) goto LA65_;
break;
			case 29: 
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_38)) goto LA65_;
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_54)) goto LA65_;
if (eqStrings(keyw, TM__paI0W78l0CRDBLjAHJxn6w_72)) goto LA67_;
break;
			}
			goto LA68_;
			LA64_: ;
			{
				NimStringV2 colontmp__8;
				NimStringV2 colontmp__11;
				colontmp__8.len = 0; colontmp__8.p = NIM_NIL;
				{
					tyObject_Report__45JukV4U6A1QELeWVCpPkg colontmp__9;
					tyObject_Report__45JukV4U6A1QELeWVCpPkg colontmp__10;
					tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ T78_;
					{
						if (!(((NI) 2) <= (*p).indent)) goto LA75_;
						(*p).indent -= ((NI) 2);
						goto LA72;
					}
					LA75_: ;
					nimZeroMem((void*)(&colontmp__9), sizeof(tyObject_Report__45JukV4U6A1QELeWVCpPkg));
					colontmp__9 = TM__paI0W78l0CRDBLjAHJxn6w_2;
					(*p).info.col = ((NI16) (j));
					nimZeroMem((void*)(&colontmp__10), sizeof(tyObject_Report__45JukV4U6A1QELeWVCpPkg));
					colontmp__10 = TM__paI0W78l0CRDBLjAHJxn6w_2;
					T78_.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
					nimZeroMem((void*)(&T78_), sizeof(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ));
					T78_.kind = ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 67);
					switch (T78_.kind) {
					case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 53):
					break;
					case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 55) ... ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 58):
					break;
					case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 59):
					break;
					case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 60):
					break;
					case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 69):
					break;
					default:
					break;
					} 
					T78_.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
					wrap__astZfilter95tmpl_105((&T78_), (&TM__paI0W78l0CRDBLjAHJxn6w_73), (*p).info, (&colontmp__10));
					if (NIM_UNLIKELY(*nimErr_)) goto LA77_;
					colontmp__9 = colontmp__10;
					handleReport__frontZmsgs_789((*p).config, (&colontmp__9), (&TM__paI0W78l0CRDBLjAHJxn6w_73), ((tyEnum_TErrorHandling__NYD6anka6eDByYBQZzk1Uw) 1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA77_;
					{
						LA77_:;
					}
					{
						oldNimErrFin77_ = *nimErr_; *nimErr_ = NIM_FALSE;
						eqdestroy___astZreports_69((&colontmp__9));
						if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
						*nimErr_ = oldNimErrFin77_;
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
				} LA72: ;
				colontmp__11 = spaces__pureZstrutils_1070(((NI) ((*p).indent)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
				colontmp__8 = colontmp__11;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__8);
				if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
				llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_76);
				if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
				{
					LA71_:;
				}
				{
					oldNimErrFin71_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___system_3228((&colontmp__8));
					*nimErr_ = oldNimErrFin71_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			}
			goto LA69_;
			LA65_: ;
			{
				NimStringV2 colontmp__12;
				NimStringV2 colontmp__13;
				NimStringV2 colontmp__14;
				NimStringV2 colontmp__15;
				colontmp__12.len = 0; colontmp__12.p = NIM_NIL;
				colontmp__13.len = 0; colontmp__13.p = NIM_NIL;
				colontmp__14 = spaces__pureZstrutils_1070(((NI) ((*p).indent)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA84_;
				colontmp__12 = colontmp__14;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__12);
				if (NIM_UNLIKELY(*nimErr_)) goto LA84_;
				colontmp__15 = substr__system_7587((*p).x, d);
				if (NIM_UNLIKELY(*nimErr_)) goto LA84_;
				colontmp__13 = colontmp__15;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__13);
				if (NIM_UNLIKELY(*nimErr_)) goto LA84_;
				(*p).indent += ((NI) 2);
				{
					LA84_:;
				}
				{
					oldNimErrFin84_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___system_3228((&colontmp__13));
					eqdestroy___system_3228((&colontmp__12));
					*nimErr_ = oldNimErrFin84_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			}
			goto LA69_;
			LA66_: ;
			{
				NimStringV2 colontmp__16;
				NimStringV2 colontmp__17;
				NimStringV2 colontmp__18;
				NimStringV2 colontmp__19;
				colontmp__16.len = 0; colontmp__16.p = NIM_NIL;
				colontmp__17.len = 0; colontmp__17.p = NIM_NIL;
				colontmp__18 = spaces__pureZstrutils_1070(((NI) ((NI)((*p).indent - ((NI) 2)))));
				if (NIM_UNLIKELY(*nimErr_)) goto LA88_;
				colontmp__16 = colontmp__18;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__16);
				if (NIM_UNLIKELY(*nimErr_)) goto LA88_;
				colontmp__19 = substr__system_7587((*p).x, d);
				if (NIM_UNLIKELY(*nimErr_)) goto LA88_;
				colontmp__17 = colontmp__19;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__17);
				if (NIM_UNLIKELY(*nimErr_)) goto LA88_;
				{
					LA88_:;
				}
				{
					oldNimErrFin88_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___system_3228((&colontmp__17));
					eqdestroy___system_3228((&colontmp__16));
					*nimErr_ = oldNimErrFin88_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			}
			goto LA69_;
			LA67_: ;
			{
				NimStringV2 colontmp__20;
				NimStringV2 colontmp__21;
				NimStringV2 colontmp__22;
				NimStringV2 colontmp__23;
				colontmp__20.len = 0; colontmp__20.p = NIM_NIL;
				colontmp__21.len = 0; colontmp__21.p = NIM_NIL;
				colontmp__22 = spaces__pureZstrutils_1070(((NI) ((*p).indent)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
				colontmp__20 = colontmp__22;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__20);
				if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
				colontmp__23 = substr__system_7587((*p).x, d);
				if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
				colontmp__21 = colontmp__23;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__21);
				if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
				{
					NIM_BOOL T95_;
					T95_ = (NIM_BOOL)0;
					T95_ = contains__pureZstrutils_1697((*p).x, TM__paI0W78l0CRDBLjAHJxn6w_77);
					if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
					if (!!(T95_)) goto LA96_;
					(*p).indent += ((NI) 2);
				}
				LA96_: ;
				{
					LA92_:;
				}
				{
					oldNimErrFin92_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___system_3228((&colontmp__21));
					eqdestroy___system_3228((&colontmp__20));
					*nimErr_ = oldNimErrFin92_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			}
			goto LA69_;
			LA68_: ;
			{
				NimStringV2 colontmp__24;
				NimStringV2 colontmp__25;
				NimStringV2 colontmp__26;
				NimStringV2 colontmp__27;
				colontmp__24.len = 0; colontmp__24.p = NIM_NIL;
				colontmp__25.len = 0; colontmp__25.p = NIM_NIL;
				colontmp__26 = spaces__pureZstrutils_1070(((NI) ((*p).indent)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA101_;
				colontmp__24 = colontmp__26;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__24);
				if (NIM_UNLIKELY(*nimErr_)) goto LA101_;
				colontmp__27 = substr__system_7587((*p).x, d);
				if (NIM_UNLIKELY(*nimErr_)) goto LA101_;
				colontmp__25 = colontmp__27;
				llStreamWrite__astZllstream_267((*p).outp, colontmp__25);
				if (NIM_UNLIKELY(*nimErr_)) goto LA101_;
				{
					LA101_:;
				}
				{
					oldNimErrFin101_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___system_3228((&colontmp__25));
					eqdestroy___system_3228((&colontmp__24));
					*nimErr_ = oldNimErrFin101_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
			}
			LA69_: ;
			(*p).state = ((tyEnum_TParseState__TMyoReN7VAtsUpVF9bL9cXRQ) 0);
			eqdestroy___system_3228((&keyw));
			goto LA12;
			{
				LA36_:;
			}
			{
				oldNimErrFin36_ = *nimErr_; *nimErr_ = NIM_FALSE;
				eqdestroy___system_3228((&keyw));
				*nimErr_ = oldNimErrFin36_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA34_: ;
		(*p).par = ((NI) 0);
		(*p).curly = ((NI) 0);
		(*p).bracket = ((NI) 0);
		j = ((NI) 0);
		switch ((*p).state) {
		case ((tyEnum_TParseState__TMyoReN7VAtsUpVF9bL9cXRQ) 1):
		{
			NimStringV2 colontmp__28;
			NimStringV2 colontmp__29;
			colontmp__28.len = 0; colontmp__28.p = NIM_NIL;
			llStreamWrite__astZllstream_267((*p).outp, (*p).conc);
			if (NIM_UNLIKELY(*nimErr_)) goto LA107_;
			llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_78);
			if (NIM_UNLIKELY(*nimErr_)) goto LA107_;
			colontmp__29 = spaces__pureZstrutils_1070(((NI) ((NI)((*p).indent + ((NI) 2)))));
			if (NIM_UNLIKELY(*nimErr_)) goto LA107_;
			colontmp__28 = colontmp__29;
			llStreamWrite__astZllstream_267((*p).outp, colontmp__28);
			if (NIM_UNLIKELY(*nimErr_)) goto LA107_;
			llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_80);
			if (NIM_UNLIKELY(*nimErr_)) goto LA107_;
			{
				LA107_:;
			}
			{
				oldNimErrFin107_ = *nimErr_; *nimErr_ = NIM_FALSE;
				eqdestroy___system_3228((&colontmp__28));
				*nimErr_ = oldNimErrFin107_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		break;
		case ((tyEnum_TParseState__TMyoReN7VAtsUpVF9bL9cXRQ) 0):
		{
			NimStringV2 colontmp__30;
			NimStringV2 colontmp__31;
			colontmp__30.len = 0; colontmp__30.p = NIM_NIL;
			newLine__astZfilter95tmpl_36(p);
			if (NIM_UNLIKELY(*nimErr_)) goto LA111_;
			colontmp__31 = spaces__pureZstrutils_1070(((NI) ((*p).indent)));
			if (NIM_UNLIKELY(*nimErr_)) goto LA111_;
			colontmp__30 = colontmp__31;
			llStreamWrite__astZllstream_267((*p).outp, colontmp__30);
			if (NIM_UNLIKELY(*nimErr_)) goto LA111_;
			llStreamWrite__astZllstream_267((*p).outp, (*p).emit);
			if (NIM_UNLIKELY(*nimErr_)) goto LA111_;
			llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_82);
			if (NIM_UNLIKELY(*nimErr_)) goto LA111_;
			(*p).emitPar += ((NI) 1);
			{
				LA111_:;
			}
			{
				oldNimErrFin111_ = *nimErr_; *nimErr_ = NIM_FALSE;
				eqdestroy___system_3228((&colontmp__30));
				*nimErr_ = oldNimErrFin111_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		break;
		}
		(*p).state = ((tyEnum_TParseState__TMyoReN7VAtsUpVF9bL9cXRQ) 1);
		{
			while (1) {
				{
					if (!!((j < len))) goto LA118_;
					goto LA115;
				}
				LA118_: ;
				switch (((NU8)((*p).x.p->data[j]))) {
				case 1 ... 31:
				case 128 ... 255:
				{
					NimStringV2 colontmp__32;
					NimStringV2 colontmp__33;
					colontmp__32.len = 0; colontmp__32.p = NIM_NIL;
					llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_84);
					if (NIM_UNLIKELY(*nimErr_)) goto LA121_;
					colontmp__33 = toHex__pureZstrutils_1860(((NU8)((*p).x.p->data[j])), ((NI) 2));
					if (NIM_UNLIKELY(*nimErr_)) goto LA121_;
					colontmp__32 = colontmp__33;
					llStreamWrite__astZllstream_267((*p).outp, colontmp__32);
					if (NIM_UNLIKELY(*nimErr_)) goto LA121_;
					j += ((NI) 1);
					{
						LA121_:;
					}
					{
						oldNimErrFin121_ = *nimErr_; *nimErr_ = NIM_FALSE;
						eqdestroy___system_3228((&colontmp__32));
						*nimErr_ = oldNimErrFin121_;
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				case 92:
				{
					llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_86);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					j += ((NI) 1);
				}
				break;
				case 39:
				{
					llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_88);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					j += ((NI) 1);
				}
				break;
				case 34:
				{
					llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_90);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					j += ((NI) 1);
				}
				break;
				default:
				{
					{
						{
							if (!((NU8)((*p).x.p->data[j]) == (NU8)((*p).subsChar))) goto LA131_;
							j += ((NI) 1);
							switch (((NU8)((*p).x.p->data[j]))) {
							case 123:
							{
								NI curly;
								(*p).info.col = ((NI16) (j));
								llStreamWrite__astZllstream_277((*p).outp, 34);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_267((*p).outp, (*p).conc);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_267((*p).outp, (*p).toStr);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_277((*p).outp, 40);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								j += ((NI) 1);
								curly = ((NI) 0);
								{
									while (1) {
										{
											if (!!((j < len))) goto LA138_;
											goto LA135;
										}
										LA138_: ;
										switch (((NU8)((*p).x.p->data[j]))) {
										case 123:
										{
											j += ((NI) 1);
											curly += ((NI) 1);
											llStreamWrite__astZllstream_277((*p).outp, 123);
											if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
										}
										break;
										case 125:
										{
											j += ((NI) 1);
											{
												if (!(curly == ((NI) 0))) goto LA144_;
												goto LA134;
											}
											LA144_: ;
											{
												if (!(((NI) 0) < curly)) goto LA148_;
												curly -= ((NI) 1);
											}
											LA148_: ;
											llStreamWrite__astZllstream_277((*p).outp, 125);
											if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
										}
										break;
										default:
										{
											llStreamWrite__astZllstream_277((*p).outp, (*p).x.p->data[j]);
											if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
											j += ((NI) 1);
										}
										break;
										}
									} LA135: ;
								} LA134: ;
								{
									tyObject_Report__45JukV4U6A1QELeWVCpPkg colontmp__34;
									tyObject_Report__45JukV4U6A1QELeWVCpPkg colontmp__35;
									tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ T156_;
									if (!(((NI) 0) < curly)) goto LA153_;
									nimZeroMem((void*)(&colontmp__34), sizeof(tyObject_Report__45JukV4U6A1QELeWVCpPkg));
									colontmp__34 = TM__paI0W78l0CRDBLjAHJxn6w_2;
									nimZeroMem((void*)(&colontmp__35), sizeof(tyObject_Report__45JukV4U6A1QELeWVCpPkg));
									colontmp__35 = TM__paI0W78l0CRDBLjAHJxn6w_2;
									T156_.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
									nimZeroMem((void*)(&T156_), sizeof(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ));
									T156_.kind = ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 58);
									T156_._kind_2.expected.len = 1; T156_._kind_2.expected.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
									T156_._kind_2.expected.p->data[0] = TM__paI0W78l0CRDBLjAHJxn6w_92;
									switch (T156_.kind) {
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 53):
									break;
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 55) ... ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 58):
									break;
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 59):
									break;
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 60):
									break;
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 69):
									break;
									default:
									break;
									} 
									T156_.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
									wrap__astZfilter95tmpl_105((&T156_), (&TM__paI0W78l0CRDBLjAHJxn6w_93), (*p).info, (&colontmp__35));
									if (NIM_UNLIKELY(*nimErr_)) goto LA155_;
									colontmp__34 = colontmp__35;
									handleReport__frontZmsgs_789((*p).config, (&colontmp__34), (&TM__paI0W78l0CRDBLjAHJxn6w_93), ((tyEnum_TErrorHandling__NYD6anka6eDByYBQZzk1Uw) 1));
									if (NIM_UNLIKELY(*nimErr_)) goto LA155_;
									eqdestroy___astZreports_69((&colontmp__34));
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									goto LA114;
									{
										LA155_:;
									}
									{
										oldNimErrFin155_ = *nimErr_; *nimErr_ = NIM_FALSE;
										eqdestroy___astZreports_69((&colontmp__34));
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
										*nimErr_ = oldNimErrFin155_;
									}
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								}
								LA153_: ;
								llStreamWrite__astZllstream_277((*p).outp, 41);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_267((*p).outp, (*p).conc);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_277((*p).outp, 34);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
							break;
							case 97 ... 122:
							case 65 ... 90:
							case 128 ... 255:
							{
								llStreamWrite__astZllstream_277((*p).outp, 34);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_267((*p).outp, (*p).conc);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_267((*p).outp, (*p).toStr);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_277((*p).outp, 40);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								{
									while (1) {
										NIM_BOOL colontmp__36;
										colontmp__36 = (NIM_BOOL)0;
										{
											colontmp__36 = (j < len);
											{
												if (!!(colontmp__36)) goto LA165_;
												goto LA162;
											}
											LA165_: ;
											colontmp__36 = (((NU8)((*p).x.p->data[j])) >= ((NU8)(97)) && ((NU8)((*p).x.p->data[j])) <= ((NU8)(122)) || ((NU8)((*p).x.p->data[j])) >= ((NU8)(65)) && ((NU8)((*p).x.p->data[j])) <= ((NU8)(90)) || ((NU8)((*p).x.p->data[j])) >= ((NU8)(48)) && ((NU8)((*p).x.p->data[j])) <= ((NU8)(57)) || ((NU8)((*p).x.p->data[j])) >= ((NU8)(128)) && ((NU8)((*p).x.p->data[j])) <= ((NU8)(255)) || ((NU8)((*p).x.p->data[j])) == ((NU8)(46)) || ((NU8)((*p).x.p->data[j])) == ((NU8)(95)));
										} LA162: ;
										{
											if (!!(colontmp__36)) goto LA169_;
											goto LA161;
										}
										LA169_: ;
										llStreamWrite__astZllstream_277((*p).outp, (*p).x.p->data[j]);
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
										j += ((NI) 1);
									} LA161: ;
								}
								llStreamWrite__astZllstream_277((*p).outp, 41);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_267((*p).outp, (*p).conc);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								llStreamWrite__astZllstream_277((*p).outp, 34);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
							break;
							default:
							{
								{
									tyObject_Report__45JukV4U6A1QELeWVCpPkg colontmp__37;
									tyObject_Report__45JukV4U6A1QELeWVCpPkg colontmp__38;
									tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ T178_;
									{
										if (!((NU8)((*p).x.p->data[j]) == (NU8)((*p).subsChar))) goto LA175_;
										llStreamWrite__astZllstream_277((*p).outp, (*p).subsChar);
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
										j += ((NI) 1);
										goto LA172;
									}
									LA175_: ;
									nimZeroMem((void*)(&colontmp__37), sizeof(tyObject_Report__45JukV4U6A1QELeWVCpPkg));
									colontmp__37 = TM__paI0W78l0CRDBLjAHJxn6w_2;
									(*p).info.col = ((NI16) (j));
									nimZeroMem((void*)(&colontmp__38), sizeof(tyObject_Report__45JukV4U6A1QELeWVCpPkg));
									colontmp__38 = TM__paI0W78l0CRDBLjAHJxn6w_2;
									T178_.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
									nimZeroMem((void*)(&T178_), sizeof(tyObject_ParserReport__1OmQ9azeiSS0eiHRtur56eQ));
									T178_.kind = ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 68);
									switch (T178_.kind) {
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 53):
									break;
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 55) ... ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 58):
									break;
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 59):
									break;
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 60):
									break;
									case ((tyEnum_ReportKind__RGGX4GG6fAWgUwwvGKW19bw) 69):
									break;
									default:
									break;
									} 
									T178_.Sup.Sup.m_type = (&NTIv2__1OmQ9azeiSS0eiHRtur56eQ_);
									wrap__astZfilter95tmpl_105((&T178_), (&TM__paI0W78l0CRDBLjAHJxn6w_94), (*p).info, (&colontmp__38));
									if (NIM_UNLIKELY(*nimErr_)) goto LA177_;
									colontmp__37 = colontmp__38;
									handleReport__frontZmsgs_789((*p).config, (&colontmp__37), (&TM__paI0W78l0CRDBLjAHJxn6w_94), ((tyEnum_TErrorHandling__NYD6anka6eDByYBQZzk1Uw) 1));
									if (NIM_UNLIKELY(*nimErr_)) goto LA177_;
									{
										LA177_:;
									}
									{
										oldNimErrFin177_ = *nimErr_; *nimErr_ = NIM_FALSE;
										eqdestroy___astZreports_69((&colontmp__37));
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
										*nimErr_ = oldNimErrFin177_;
									}
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								} LA172: ;
							}
							break;
							}
							goto LA128;
						}
						LA131_: ;
						llStreamWrite__astZllstream_277((*p).outp, (*p).x.p->data[j]);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						j += ((NI) 1);
					} LA128: ;
				}
				break;
				}
			} LA115: ;
		} LA114: ;
		llStreamWrite__astZllstream_267((*p).outp, TM__paI0W78l0CRDBLjAHJxn6w_96);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	} LA12: ;
	}BeforeRet_: ;
}
static N_INLINE(NI, minuspercent___system_704)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_704(((NI) (ptrdiff_t) (p)), ((NI) 16));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			{
				if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA9_;
				result = NIM_TRUE;
				goto LA6;
			}
			LA9_: ;
			(*cell).rc -= ((NI) 16);
		} LA6: ;
		rememberCycle__system_3163(result, cell, (*((TNimTypeV2**) (p))));
	}
	LA3_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_704(((NI) (ptrdiff_t) (p)), ((NI) 16));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			{
				if (!((NI)((NI64)((*cell).rc) >> (NU64)(((NI) 4))) == ((NI) 0))) goto LA9_;
				result = NIM_TRUE;
				goto LA6;
			}
			LA9_: ;
			(*cell).rc -= ((NI) 16);
		} LA6: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___astZfilter95tmpl_244)(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg* dest) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest).inp);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).inp);
	}
	LA4_: ;
	eqdestroy___system_3228((&(*dest).x));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest).outp);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).outp);
	}
	LA9_: ;
	eqdestroy___system_3228((&(*dest).emit));
	eqdestroy___system_3228((&(*dest).conc));
	eqdestroy___system_3228((&(*dest).toStr));
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLast((*dest).config);
		if (!T13_) goto LA14_;
		eqdestroy___frontZoptions_5215((*dest).config);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).config, ((NI) 8));
	}
	LA14_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g*, filterTmpl__astZfilter95tmpl_229)(tyObject_ConfigRefcolonObjectType___LaK09ayL9alwKUad7rts0rTw* conf, tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* stdin_0, NimStringV2 filename, tyObject_TNode__Bujcm1vZNtQEsOsw5ZIYIw* call) {
	tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* result;
	tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg p;
	tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q T2_;
	tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* T3_;
	NIM_CHAR T4_;
	NIM_CHAR T5_;
	NimStringV2 T6_;
	NimStringV2 T7_;
	NimStringV2 T8_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g*)0;
	nimZeroMem((void*)(&p), sizeof(tyObject_TTmplParser__hVXV9cC75rOvsaODz9bp1zeg));
	eqcopy___frontZoptions_5582(&p.config, conf);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimZeroMem((void*)(&T2_), sizeof(tyObject_TLineInfo__WGx4rAexNXnczy1Avn646Q));
	T2_ = newLineInfo__frontZoptions_7556(conf, filename, ((NI) 0), ((NI) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	p.info = T2_;
	T3_ = (tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g*)0;
	T3_ = llStreamOpen__astZllstream_30(TM__paI0W78l0CRDBLjAHJxn6w_4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	p.outp = T3_;
	eqcopy___astZllstream_70(&p.inp, stdin_0, NIM_TRUE);
	T4_ = (NIM_CHAR)0;
	T4_ = charArg__astZfilters_64(conf, call, TM__paI0W78l0CRDBLjAHJxn6w_6, ((NI) 1), 36);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	p.subsChar = T4_;
	T5_ = (NIM_CHAR)0;
	T5_ = charArg__astZfilters_64(conf, call, TM__paI0W78l0CRDBLjAHJxn6w_8, ((NI) 2), 35);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	p.nimDirective = T5_;
	T6_.len = 0; T6_.p = NIM_NIL;
	T6_ = strArg__astZfilters_80(conf, call, TM__paI0W78l0CRDBLjAHJxn6w_10, ((NI) 3), TM__paI0W78l0CRDBLjAHJxn6w_12);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	p.emit = T6_;
	T7_.len = 0; T7_.p = NIM_NIL;
	T7_ = strArg__astZfilters_80(conf, call, TM__paI0W78l0CRDBLjAHJxn6w_14, ((NI) 4), TM__paI0W78l0CRDBLjAHJxn6w_16);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	p.conc = T7_;
	T8_.len = 0; T8_.p = NIM_NIL;
	T8_ = strArg__astZfilters_80(conf, call, TM__paI0W78l0CRDBLjAHJxn6w_18, ((NI) 5), TM__paI0W78l0CRDBLjAHJxn6w_20);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	p.toStr = T8_;
	p.x = rawNewString(((NI) 120));
	{
		tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* T11_;
		NIM_BOOL T12_;
		T11_ = (tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g*)0;
		T11_ = p.inp;
		T12_ = (NIM_BOOL)0;
		T12_ = llStreamReadLine__astZllstream_247(T11_, (&p.x));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T12_) goto LA13_;
		p.info.line += ((NI) 1);
	}
	LA13_: ;
	{
		while (1) {
			{
				tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g* T19_;
				NIM_BOOL T20_;
				T19_ = (tyObject_TLLStream__a5oZYQ9aTktYME2449ayEi6g*)0;
				T19_ = p.inp;
				T20_ = (NIM_BOOL)0;
				T20_ = llStreamReadLine__astZllstream_247(T19_, (&p.x));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				if (!!(T20_)) goto LA21_;
				goto LA16;
			}
			LA21_: ;
			p.info.line += ((NI) 1);
			parseLine__astZfilter95tmpl_74((&p));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		} LA16: ;
	}
	newLine__astZfilter95tmpl_36((&p));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = p.outp;
	p.outp = 0;
	llStreamClose__astZllstream_163(p.inp);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___astZfilter95tmpl_244((&p));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
