/* Generated by Nim Compiler v0.1.0-dev.21456 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringV2 NimStringV2;
typedef struct NimStrPayload NimStrPayload;
struct NimStringV2 {
NI64 len;
NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3205)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, stdlibatpstdatsprivate__globsInit000)(void) {
	nimTestErrorFlag();
	return ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nativeToUnixPath__stdZprivateZglobs_75)(NimStringV2 path) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	eqcopy___system_3205((&result), path);
	return result;
}
