/* Generated by Nim Compiler v0.1.0-dev.20827 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct RootObj {
TNimTypeV2* m_type;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg {
  RootObj Sup;
NI pos;
NIM_BOOL inShortState;
NIM_BOOL allowWhitespaceAfterColon;
tySet_tyChar__nmiMWKVIe46vacnhAFrQvw shortNoVal;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ longNoVal;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ cmds;
NI idx;
tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA kind;
NimStringV2 key;
NimStringV2 val;
};
typedef NU8 tyArray__WA2r72JeITHTO3SbTEOdJQ[8192];
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};


#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseopt_335)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3726)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3228)(NimStringV2* dest);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, newSeq__systemZio_592)(NI len);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3231)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, handleShortOption__pureZparseopt_87)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* p, NimStringV2 cmd);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
static N_INLINE(NI, cardSet)(tyArray__WA2r72JeITHTO3SbTEOdJQ s, NI len);
static N_INLINE(NI, countBits32)(NU32 n);
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_26)(NU32 x);
N_CDECL(int, __builtin_popcount)(unsigned int x);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_7587)(NimStringV2 s, NI first);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_3234)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NI, parseWord__pureZparseopt_25)(NimStringV2 s, NI i, NimStringV2* w, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw delim);
static N_INLINE(NIM_BOOL, contains__stdZenumutils_47)(NimStringV2* a, NI aLen_0, NimStringV2 item);
static N_INLINE(NI, find__stdZenumutils_52)(NimStringV2* a, NI aLen_0, NimStringV2 item);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_BOOL, equalMem__system_1716)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, quoteShellCommand__pureZos_773)(NimStringV2* args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, X5BX5D___pureZparseopt_249)(NimStringV2* s, NI sLen_0, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__system_3620)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* s, NI len);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___stdZenumutils_99)(NI a, NI b);
N_LIB_PRIVATE TNimTypeV2 NTIv2__l9cyoK9aLLTUH7LBRIbLqETg_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__GYgvYKeHVTEls0AcywABHQ_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__GYgvYKeHVTEls0AcywABHQ_3 = {0, (NimStrPayload*)&TM__GYgvYKeHVTEls0AcywABHQ_2};
static const NimStringV2 TM__GYgvYKeHVTEls0AcywABHQ_4 = {0, (NimStrPayload*)&TM__GYgvYKeHVTEls0AcywABHQ_2};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__GYgvYKeHVTEls0AcywABHQ_5 = {
0x00, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x24,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__GYgvYKeHVTEls0AcywABHQ_6 = {0, (NimStrPayload*)&TM__GYgvYKeHVTEls0AcywABHQ_2};
extern NIM_BOOL nimInErrorMode__system_4174;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseopt_335)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* dest) {
	eqdestroy___system_3726((&(*dest).longNoVal));
	eqdestroy___system_3726((&(*dest).cmds));
	eqdestroy___system_3228((&(*dest).key));
	eqdestroy___system_3228((&(*dest).val));
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
	(void)(T1_);
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
	(void)(T1_);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4174);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initOptParser__pureZparseopt_51)(NimStringV2* args, NI argsLen_0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw shortNoVal, tySequence__sM4lkSb7zS6F7OVMvW9cffQ longNoVal, NIM_BOOL allowWhitespaceAfterColon, tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* Result) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg));
	(*Result).Sup.m_type = (&NTIv2__l9cyoK9aLLTUH7LBRIbLqETg_);
	(*Result).pos = ((NI) 0);
	(*Result).idx = ((NI) 0);
	(*Result).inShortState = NIM_FALSE;
	nimCopyMem((void*)(*Result).shortNoVal, (NIM_CONST void*)shortNoVal, 32);
	(*Result).longNoVal = longNoVal;
	(*Result).allowWhitespaceAfterColon = allowWhitespaceAfterColon;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = newSeq__systemZio_592(((NI) (argsLen_0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).cmds = T1_;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = argsLen_0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NimStringV2* colontmp__2;
				NimStringV2* colontmp__3;
				{
					if (!!((i_2 < colontmp_))) goto LA7_;
					goto LA4;
				}
				LA7_: ;
				i = i_2;
				colontmp__2 = (&(*Result).cmds.p->data[i]);
				colontmp__3 = (&args[i]);
				eqcopy___system_3231(colontmp__2, (*colontmp__3));
				i_2 += ((NI) 1);
			} LA4: ;
		}
	}
	(*Result).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 0);
	(*Result).key = TM__GYgvYKeHVTEls0AcywABHQ_3;
	(*Result).val = TM__GYgvYKeHVTEls0AcywABHQ_4;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {
	prepareAdd(s, ((NI) 1));
	(*(*s).p).data[(*s).len] = c;
	(*(*s).p).data[(NI)((*s).len + ((NI) 1))] = 0;
	(*s).len += ((NI) 1);
}
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_26)(NU32 x) {
	NI result;
	int T1_;
	result = (NI)0;
	T1_ = (int)0;
	T1_ = __builtin_popcount(x);
	result = ((NI) (T1_));
	return result;
}
static N_INLINE(NI, countBits32)(NU32 n) {
	NI result;
	result = (NI)0;
	result = countSetBitsImpl__systemZcountbits95impl_26(n);
	return result;
}
static N_INLINE(NI, cardSet)(tyArray__WA2r72JeITHTO3SbTEOdJQ s, NI len) {
	NI result;
	NI i;
	result = (NI)0;
	i = ((NI) 0);
	result = ((NI) 0);
	{
		while (1) {
			NI T7_;
			{
				if (!!((i < len))) goto LA5_;
				goto LA2;
			}
			LA5_: ;
			T7_ = (NI)0;
			T7_ = countBits32(((NU32) (s[(i)- 0])));
			result += T7_;
			i += ((NI) 1);
		} LA2: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, handleShortOption__pureZparseopt_87)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* p, NimStringV2 cmd) {
	NIM_BOOL colontmp_;
	NIM_BOOL colontmp__2;
	NI i;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmp_ = (NIM_BOOL)0;
	colontmp__2 = (NIM_BOOL)0;
	i = (*p).pos;
	(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 3);
	{
		if (!(i < cmd.len)) goto LA3_;
		nimAddCharV1((&(*p).key), cmd.p->data[i]);
		i += ((NI) 1);
	}
	LA3_: ;
	(*p).inShortState = NIM_TRUE;
	{
		while (1) {
			NIM_BOOL colontmp__3;
			colontmp__3 = (NIM_BOOL)0;
			{
				colontmp__3 = (i < cmd.len);
				{
					if (!!(colontmp__3)) goto LA10_;
					goto LA7;
				}
				LA10_: ;
				colontmp__3 = (((NU8)(cmd.p->data[i])) == ((NU8)(9)) || ((NU8)(cmd.p->data[i])) == ((NU8)(32)));
			} LA7: ;
			{
				if (!!(colontmp__3)) goto LA14_;
				goto LA6;
			}
			LA14_: ;
			i += ((NI) 1);
			(*p).inShortState = NIM_FALSE;
		} LA6: ;
	}
	{
		NIM_BOOL colontmp__4;
		colontmp__4 = (NIM_BOOL)0;
		{
			colontmp__4 = (i < cmd.len);
			{
				if (!!(colontmp__4)) goto LA20_;
				goto LA17;
			}
			LA20_: ;
			{
				colontmp_ = (((NU8)(cmd.p->data[i])) == ((NU8)(58)) || ((NU8)(cmd.p->data[i])) == ((NU8)(61)));
				{
					if (!colontmp_) goto LA25_;
					goto LA22;
				}
				LA25_: ;
				{
					colontmp__2 = (((NI) 0) < cardSet((*p).shortNoVal, 32));
					{
						if (!!(colontmp__2)) goto LA30_;
						goto LA27;
					}
					LA30_: ;
					colontmp__2 = !((((*p).shortNoVal[(NU)(((NU8)((*p).key.p->data[((NI) 0)])))>>3] &(1U<<((NU)(((NU8)((*p).key.p->data[((NI) 0)])))&7U)))!=0));
				} LA27: ;
				colontmp_ = colontmp__2;
			} LA22: ;
			colontmp__4 = colontmp_;
		} LA17: ;
		{
			NIM_BOOL colontmp__5;
			NimStringV2* colontmp__7;
			NimStringV2 colontmp__8;
			if (!colontmp__4) goto LA34_;
			colontmp__5 = (NIM_BOOL)0;
			{
				colontmp__5 = (i < cmd.len);
				{
					if (!!(colontmp__5)) goto LA39_;
					goto LA36;
				}
				LA39_: ;
				colontmp__5 = (((NU8)(cmd.p->data[i])) == ((NU8)(58)) || ((NU8)(cmd.p->data[i])) == ((NU8)(61)));
			} LA36: ;
			{
				if (!colontmp__5) goto LA43_;
				i += ((NI) 1);
			}
			LA43_: ;
			(*p).inShortState = NIM_FALSE;
			{
				while (1) {
					NIM_BOOL colontmp__6;
					colontmp__6 = (NIM_BOOL)0;
					{
						colontmp__6 = (i < cmd.len);
						{
							if (!!(colontmp__6)) goto LA50_;
							goto LA47;
						}
						LA50_: ;
						colontmp__6 = (((NU8)(cmd.p->data[i])) == ((NU8)(9)) || ((NU8)(cmd.p->data[i])) == ((NU8)(32)));
					} LA47: ;
					{
						if (!!(colontmp__6)) goto LA54_;
						goto LA46;
					}
					LA54_: ;
					i += ((NI) 1);
				} LA46: ;
			}
			colontmp__7 = (&(*p).val);
			colontmp__8 = substr__system_7587(cmd, i);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqsink___system_3234(colontmp__7, colontmp__8);
			(*p).pos = ((NI) 0);
			(*p).idx += ((NI) 1);
			goto LA16;
		}
		LA34_: ;
		(*p).pos = i;
	} LA16: ;
	{
		NIM_BOOL colontmp__9;
		NIM_BOOL colontmp__10;
		NIM_BOOL colontmp__11;
		if (!(cmd.len <= i)) goto LA58_;
		colontmp__9 = (NIM_BOOL)0;
		colontmp__10 = (NIM_BOOL)0;
		(*p).inShortState = NIM_FALSE;
		(*p).pos = ((NI) 0);
		(*p).idx += ((NI) 1);
		colontmp__11 = (NIM_BOOL)0;
		{
			{
				{
					NI T63_;
					T63_ = (*p).cmds.len;
					colontmp__10 = ((*p).idx < T63_);
					{
						if (!!(colontmp__10)) goto LA66_;
						goto LA62;
					}
					LA66_: ;
					colontmp__10 = (((NI) 0) < cardSet((*p).shortNoVal, 32));
				} LA62: ;
				colontmp__9 = colontmp__10;
				{
					if (!!(colontmp__9)) goto LA70_;
					goto LA61;
				}
				LA70_: ;
				colontmp__9 = !((((*p).shortNoVal[(NU)(((NU8)((*p).key.p->data[((NI) 0)])))>>3] &(1U<<((NU)(((NU8)((*p).key.p->data[((NI) 0)])))&7U)))!=0));
			} LA61: ;
			colontmp__11 = colontmp__9;
			{
				if (!!(colontmp__11)) goto LA74_;
				goto LA60;
			}
			LA74_: ;
			colontmp__11 = ((*p).val.len == 0);
		} LA60: ;
		{
			NimStringV2* colontmp__12;
			NimStringV2* colontmp__13;
			if (!colontmp__11) goto LA78_;
			colontmp__12 = (&(*p).val);
			colontmp__13 = (&(*p).cmds.p->data[(*p).idx]);
			eqcopy___system_3231(colontmp__12, (*colontmp__13));
			(*p).idx += ((NI) 1);
		}
		LA78_: ;
	}
	LA58_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseWord__pureZparseopt_25)(NimStringV2 s, NI i, NimStringV2* w, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw delim) {
	NI result;
	result = (NI)0;
	result = i;
	{
		NIM_BOOL colontmp_;
		colontmp_ = (NIM_BOOL)0;
		{
			colontmp_ = (result < s.len);
			{
				if (!!(colontmp_)) goto LA5_;
				goto LA2;
			}
			LA5_: ;
			colontmp_ = ((NU8)(s.p->data[result]) == (NU8)(34));
		} LA2: ;
		{
			if (!colontmp_) goto LA9_;
			result += ((NI) 1);
			{
				while (1) {
					{
						if (!!((result < s.len))) goto LA15_;
						goto LA12;
					}
					LA15_: ;
					{
						if (!((NU8)(s.p->data[result]) == (NU8)(34))) goto LA19_;
						result += ((NI) 1);
						goto LA11;
					}
					LA19_: ;
					nimAddCharV1((&(*w)), s.p->data[result]);
					result += ((NI) 1);
				} LA12: ;
			} LA11: ;
			goto LA1;
		}
		LA9_: ;
		{
			while (1) {
				NIM_BOOL colontmp__2;
				colontmp__2 = (NIM_BOOL)0;
				{
					colontmp__2 = (result < s.len);
					{
						if (!!(colontmp__2)) goto LA26_;
						goto LA23;
					}
					LA26_: ;
					colontmp__2 = !(((delim[(NU)(((NU8)(s.p->data[result])))>>3] &(1U<<((NU)(((NU8)(s.p->data[result])))&7U)))!=0));
				} LA23: ;
				{
					if (!!(colontmp__2)) goto LA30_;
					goto LA22;
				}
				LA30_: ;
				nimAddCharV1((&(*w)), s.p->data[result]);
				result += ((NI) 1);
			} LA22: ;
		}
	} LA1: ;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1716)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = a.len;
	blen = b.len;
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem__system_1716(((void*) ((&a.p->data[((NI) 0)]))), ((void*) ((&b.p->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, find__stdZenumutils_52)(NimStringV2* a, NI aLen_0, NimStringV2 item) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	{
		NimStringV2* i;
		NI i_2;
		i = (NimStringV2*)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				{
					if (!!((i_2 < aLen_0))) goto LA6_;
					goto LA3;
				}
				LA6_: ;
				i = (&a[i_2]);
				{
					if (!eqStrings((*i), item)) goto LA10_;
					goto BeforeRet_;
				}
				LA10_: ;
				result += ((NI) 1);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZenumutils_47)(NimStringV2* a, NI aLen_0, NimStringV2 item) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = find__stdZenumutils_52(a, aLen_0, item);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nponext)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* p) {
	NI i;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		T3_ = (*p).cmds.len;
		if (!(T3_ <= (*p).idx)) goto LA4_;
		(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 0);
		goto BeforeRet_;
	}
	LA4_: ;
	i = (*p).pos;
	{
		while (1) {
			NIM_BOOL colontmp_;
			colontmp_ = (NIM_BOOL)0;
			{
				colontmp_ = (i < (*p).cmds.p->data[(*p).idx].len);
				{
					if (!!(colontmp_)) goto LA11_;
					goto LA8;
				}
				LA11_: ;
				colontmp_ = (((NU8)((*p).cmds.p->data[(*p).idx].p->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmds.p->data[(*p).idx].p->data[i])) == ((NU8)(32)));
			} LA8: ;
			{
				if (!!(colontmp_)) goto LA15_;
				goto LA7;
			}
			LA15_: ;
			i += ((NI) 1);
		} LA7: ;
	}
	(*p).pos = i;
	setLengthStrV2((&(*p).key), ((NI) 0));
	setLengthStrV2((&(*p).val), ((NI) 0));
	{
		if (!(*p).inShortState) goto LA19_;
		(*p).inShortState = NIM_FALSE;
		{
			{
				if (!((*p).cmds.p->data[(*p).idx].len <= i)) goto LA24_;
				(*p).idx += ((NI) 1);
				(*p).pos = ((NI) 0);
				{
					NI T28_;
					T28_ = (*p).cmds.len;
					if (!(T28_ <= (*p).idx)) goto LA29_;
					(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 0);
					goto BeforeRet_;
				}
				LA29_: ;
				goto LA21;
			}
			LA24_: ;
			handleShortOption__pureZparseopt_87(p, (*p).cmds.p->data[(*p).idx]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto BeforeRet_;
		} LA21: ;
	}
	LA19_: ;
	{
		NIM_BOOL colontmp__2;
		NimStringV2* colontmp__16;
		NimStringV2* colontmp__17;
		colontmp__2 = (NIM_BOOL)0;
		{
			colontmp__2 = (i < (*p).cmds.p->data[(*p).idx].len);
			{
				if (!!(colontmp__2)) goto LA35_;
				goto LA32;
			}
			LA35_: ;
			colontmp__2 = ((NU8)((*p).cmds.p->data[(*p).idx].p->data[i]) == (NU8)(45));
		} LA32: ;
		{
			if (!colontmp__2) goto LA39_;
			i += ((NI) 1);
			{
				NIM_BOOL colontmp__3;
				colontmp__3 = (NIM_BOOL)0;
				{
					colontmp__3 = (i < (*p).cmds.p->data[(*p).idx].len);
					{
						if (!!(colontmp__3)) goto LA45_;
						goto LA42;
					}
					LA45_: ;
					colontmp__3 = ((NU8)((*p).cmds.p->data[(*p).idx].p->data[i]) == (NU8)(45));
				} LA42: ;
				{
					NIM_BOOL colontmp__4;
					NimStringV2 T51_;
					if (!colontmp__3) goto LA49_;
					colontmp__4 = (NIM_BOOL)0;
					(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 2);
					i += ((NI) 1);
					T51_.len = 0; T51_.p = NIM_NIL;
					T51_ = (*p).cmds.p->data[(*p).idx];
					i = parseWord__pureZparseopt_25(T51_, i, (&(*p).key), TM__GYgvYKeHVTEls0AcywABHQ_5);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					{
						while (1) {
							NIM_BOOL colontmp__5;
							colontmp__5 = (NIM_BOOL)0;
							{
								colontmp__5 = (i < (*p).cmds.p->data[(*p).idx].len);
								{
									if (!!(colontmp__5)) goto LA57_;
									goto LA54;
								}
								LA57_: ;
								colontmp__5 = (((NU8)((*p).cmds.p->data[(*p).idx].p->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmds.p->data[(*p).idx].p->data[i])) == ((NU8)(32)));
							} LA54: ;
							{
								if (!!(colontmp__5)) goto LA61_;
								goto LA53;
							}
							LA61_: ;
							i += ((NI) 1);
						} LA53: ;
					}
					{
						NIM_BOOL colontmp__6;
						NIM_BOOL colontmp__12;
						NimStringV2* colontmp__15;
						colontmp__6 = (NIM_BOOL)0;
						{
							colontmp__6 = (i < (*p).cmds.p->data[(*p).idx].len);
							{
								if (!!(colontmp__6)) goto LA67_;
								goto LA64;
							}
							LA67_: ;
							colontmp__6 = (((NU8)((*p).cmds.p->data[(*p).idx].p->data[i])) == ((NU8)(58)) || ((NU8)((*p).cmds.p->data[(*p).idx].p->data[i])) == ((NU8)(61)));
						} LA64: ;
						{
							NIM_BOOL colontmp__7;
							NIM_BOOL colontmp__9;
							if (!colontmp__6) goto LA71_;
							colontmp__7 = (NIM_BOOL)0;
							i += ((NI) 1);
							{
								while (1) {
									NIM_BOOL colontmp__8;
									colontmp__8 = (NIM_BOOL)0;
									{
										colontmp__8 = (i < (*p).cmds.p->data[(*p).idx].len);
										{
											if (!!(colontmp__8)) goto LA78_;
											goto LA75;
										}
										LA78_: ;
										colontmp__8 = (((NU8)((*p).cmds.p->data[(*p).idx].p->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmds.p->data[(*p).idx].p->data[i])) == ((NU8)(32)));
									} LA75: ;
									{
										if (!!(colontmp__8)) goto LA82_;
										goto LA74;
									}
									LA82_: ;
									i += ((NI) 1);
								} LA74: ;
							}
							colontmp__9 = (NIM_BOOL)0;
							{
								{
									NI T90_;
									colontmp__7 = ((*p).cmds.p->data[(*p).idx].len <= i);
									{
										if (!!(colontmp__7)) goto LA88_;
										goto LA85;
									}
									LA88_: ;
									T90_ = (*p).cmds.len;
									colontmp__7 = ((*p).idx < T90_);
								} LA85: ;
								colontmp__9 = colontmp__7;
								{
									if (!!(colontmp__9)) goto LA93_;
									goto LA84;
								}
								LA93_: ;
								colontmp__9 = (*p).allowWhitespaceAfterColon;
							} LA84: ;
							{
								if (!colontmp__9) goto LA97_;
								(*p).idx += ((NI) 1);
								i = ((NI) 0);
							}
							LA97_: ;
							{
								NI T101_;
								NimStringV2* colontmp__10;
								NimStringV2 colontmp__11;
								T101_ = (*p).cmds.len;
								if (!((*p).idx < T101_)) goto LA102_;
								colontmp__10 = (&(*p).val);
								colontmp__11 = substr__system_7587((*p).cmds.p->data[(*p).idx], i);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								eqsink___system_3234(colontmp__10, colontmp__11);
							}
							LA102_: ;
							goto LA63;
						}
						LA71_: ;
						colontmp__12 = (NIM_BOOL)0;
						{
							NI T116_;
							{
								NI T106_;
								NIM_BOOL T111_;
								T106_ = (*p).longNoVal.len;
								colontmp__4 = (((NI) 0) < T106_);
								{
									if (!!(colontmp__4)) goto LA109_;
									goto LA105;
								}
								LA109_: ;
								T111_ = (NIM_BOOL)0;
								T111_ = contains__stdZenumutils_47((*p).longNoVal.p->data, (*p).longNoVal.len, (*p).key);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								colontmp__4 = !(T111_);
							} LA105: ;
							colontmp__12 = colontmp__4;
							{
								if (!!(colontmp__12)) goto LA114_;
								goto LA104;
							}
							LA114_: ;
							T116_ = (*p).cmds.len;
							colontmp__12 = ((NI)((*p).idx + ((NI) 1)) < T116_);
						} LA104: ;
						{
							NimStringV2* colontmp__13;
							NimStringV2* colontmp__14;
							if (!colontmp__12) goto LA119_;
							colontmp__13 = (&(*p).val);
							colontmp__14 = (&(*p).cmds.p->data[(NI)((*p).idx + ((NI) 1))]);
							eqcopy___system_3231(colontmp__13, (*colontmp__14));
							(*p).idx += ((NI) 1);
							goto LA63;
						}
						LA119_: ;
						colontmp__15 = (&(*p).val);
						eqsink___system_3234(colontmp__15, TM__GYgvYKeHVTEls0AcywABHQ_6);
					} LA63: ;
					(*p).idx += ((NI) 1);
					(*p).pos = ((NI) 0);
					goto LA41;
				}
				LA49_: ;
				(*p).pos = i;
				handleShortOption__pureZparseopt_87(p, (*p).cmds.p->data[(*p).idx]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA41: ;
			goto LA31;
		}
		LA39_: ;
		(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 1);
		colontmp__16 = (&(*p).key);
		colontmp__17 = (&(*p).cmds.p->data[(*p).idx]);
		eqcopy___system_3231(colontmp__16, (*colontmp__17));
		(*p).idx += ((NI) 1);
		(*p).pos = ((NI) 0);
	} LA31: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, X5BX5D___pureZparseopt_249)(NimStringV2* s, NI sLen_0, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	NI a;
	NI L;
	result.len = 0; result.p = NIM_NIL;
	a = x.a;
	L = (NI)((NI)((NI)(sLen_0 - x.b) - a) + ((NI) 1));
	newSeq__system_3620((&result), ((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NimStringV2* colontmp_;
				NimStringV2* colontmp__2;
				{
					if (!!((i_2 < L))) goto LA6_;
					goto LA3;
				}
				LA6_: ;
				i = i_2;
				colontmp_ = (&result.p->data[i]);
				colontmp__2 = (&s[(NI)(i + a)]);
				eqcopy___system_3231(colontmp_, (*colontmp__2));
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___stdZenumutils_99)(NI a, NI b) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	result.a = a;
	result.b = b;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, npocmdLineRest)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* p) {
	NimStringV2 result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmp_;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmp__2;
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmp_.len = 0; colontmp_.p = NIM_NIL;
	T2_ = dotdot___stdZenumutils_99((*p).idx, ((NI) 1));
	colontmp__2 = X5BX5D___pureZparseopt_249((*p).cmds.p->data, (*p).cmds.len, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmp_ = colontmp__2;
	result = quoteShellCommand__pureZos_773(colontmp_.p->data, colontmp_.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___system_3726((&colontmp_));
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parseoptDatInit000)(void) {
NTIv2__l9cyoK9aLLTUH7LBRIbLqETg_.destructor = (void*)eqdestroy___pureZparseopt_335; NTIv2__l9cyoK9aLLTUH7LBRIbLqETg_.size = sizeof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg); NTIv2__l9cyoK9aLLTUH7LBRIbLqETg_.align = NIM_ALIGNOF(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg); NTIv2__l9cyoK9aLLTUH7LBRIbLqETg_.name = "|stdlib.parseopt.OptParser|RootObj|";
; NTIv2__l9cyoK9aLLTUH7LBRIbLqETg_.traceImpl = (void*)NIM_NIL; NTIv2__l9cyoK9aLLTUH7LBRIbLqETg_.flags = 0;}

