/* Generated by Nim Compiler v0.1.0-dev.21456 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringV2 NimStringV2;
typedef struct NimStrPayload NimStrPayload;
struct NimStringV2 {
NI64 len;
NimStrPayload* p;
};
struct NimStrPayload {
NI64 cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__6De9adFlL6F9cF72MvAYqSqQ_1 = { 18 | NIM_STRLIT_FLAG, "sckInstantiationOf" };
static const NimStringV2 TM__6De9adFlL6F9cF72MvAYqSqQ_2 = {18, (NimStrPayload*)&TM__6De9adFlL6F9cF72MvAYqSqQ_1};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__6De9adFlL6F9cF72MvAYqSqQ_3 = { 20 | NIM_STRLIT_FLAG, "sckInstantiationFrom" };
static const NimStringV2 TM__6De9adFlL6F9cF72MvAYqSqQ_4 = {20, (NimStrPayload*)&TM__6De9adFlL6F9cF72MvAYqSqQ_3};
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___astZreports95base95sem_10)(NU8 e) {
	NimStringV2 result;
	NimStringV2 _2;
	NimStringV2 _3;
	switch (e) {
	case ((NU8) 0):
	goto LA0_;
	case ((NU8) 1):
	goto LA1_;
	}
	LA0_:;
	_2 = TM__6De9adFlL6F9cF72MvAYqSqQ_2;
	result = _2;
	goto LA2_;
	LA1_:;
	_3 = TM__6De9adFlL6F9cF72MvAYqSqQ_4;
	result = _3;
	goto LA2_;
	LA2_:;
	return result;
}
