/* Generated by Nim Compiler v0.1.0-dev.20827 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2314)(NimStringV2* s);
static N_INLINE(NIM_BOOL, isUpperAscii__utilsZstrutils50_5)(NIM_CHAR c);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_BOOL nimInErrorMode__system_4174;
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s) {
	NIM_BOOL colontmp_;
	colontmp_ = (NIM_BOOL)0;
	{
		colontmp_ = !(((*s).p == ((NimStrPayload*) NIM_NIL)));
		{
			if (!!(colontmp_)) goto LA4_;
			goto LA1;
		}
		LA4_: ;
		colontmp_ = ((NI)((*(*s).p).cap & ((NI) IL64(4611686018427387904))) == ((NI) IL64(4611686018427387904)));
	} LA1: ;
	{
		if (!colontmp_) goto LA8_;
		nimPrepareStrMutationImpl__system_2314(s);
	}
	LA8_: ;
}
static N_INLINE(NIM_BOOL, isUpperAscii__utilsZstrutils50_5)(NIM_CHAR c) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4174);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, toLowerAscii__utilsZstrutils50_12)(NimStringV2* a) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_CHAR* c;
		NI i;
		NI L;
		c = (NIM_CHAR*)0;
		i = ((NI) 0);
		L = (*a).len;
		{
			while (1) {
				NI colontmp_;
				{
					if (!!((i < L))) goto LA6_;
					goto LA3;
				}
				LA6_: ;
				colontmp_ = (NI)0;
				nimPrepareStrMutationV2((&(*a)));
				c = (&(*a).p->data[i]);
				{
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = isUpperAscii__utilsZstrutils50_5((*c));
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T11_) goto LA12_;
						colontmp_ = ((NI) 32);
						goto LA8;
					}
					LA12_: ;
					colontmp_ = ((NI) 0);
				} LA8: ;
				(*c) = ((NIM_CHAR) (((NI) ((NI)(((NU8)((*c))) + colontmp_)))));
				i += ((NI) 1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
