/* Generated by Nim Compiler v0.1.0-dev.21456 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct _sG5Block_M18mirZmirgen95blocks _sG5Block_M18mirZmirgen95blocks;
typedef struct _T2i32aG5Block_M18mirZmirgen95blocks _T2i32aG5Block_M18mirZmirgen95blocks;
typedef struct _I8NimSeqV2_4680843406 _I8NimSeqV2_4680843406;
typedef struct _I13NimSeqPayload_4680843409 _I13NimSeqPayload_4680843409;
typedef struct _G5Block_M18mirZmirgen95blocks _G5Block_M18mirZmirgen95blocks;
typedef struct _I6Option_4680843275 _I6Option_4680843275;
typedef struct _G4TSym_M14astZast95types _G4TSym_M14astZast95types;
typedef struct _I6Option_4680843283 _I6Option_4680843283;
typedef struct _G5Value_M13mirZmirconstr _G5Value_M13mirZmirconstr;
typedef struct _G7MirNode_M12mirZmirtrees _G7MirNode_M12mirZmirtrees;
typedef struct _si32 _si32;
typedef struct _T2i32ai32 _T2i32ai32;
typedef struct _G8BlockCtx_M18mirZmirgen95blocks _G8BlockCtx_M18mirZmirgen95blocks;
typedef struct _sT2G5Value_M13mirZmirconstrI6Option_4680843275 _sT2G5Value_M13mirZmirconstrI6Option_4680843275;
typedef struct _T2i32aT2G5Value_M13mirZmirconstrI6Option_4680843275 _T2i32aT2G5Value_M13mirZmirconstrI6Option_4680843275;
typedef struct _G10MirBuilder_M13mirZmirconstr _G10MirBuilder_M13mirZmirconstr;
typedef struct _T2G5Value_M13mirZmirconstrI6Option_4680843275 _T2G5Value_M13mirZmirconstrI6Option_4680843275;
typedef struct _G7Context_M13mirZmirconstr _G7Context_M13mirZmirconstr;
typedef struct _G6MirEnv_M10mirZmirenv _G6MirEnv_M10mirZmirenv;
typedef struct _G5Local_M13mirZmirbodies _G5Local_M13mirZmirbodies;
typedef struct _G6TIdent_M10astZidents _G6TIdent_M10astZidents;
typedef struct _L9MirBuffer_12_M13mirZmirconstr _L9MirBuffer_12_M13mirZmirconstr;
typedef struct _sG7MirNode_M12mirZmirtrees _sG7MirNode_M12mirZmirtrees;
typedef struct _T2i32aG7MirNode_M12mirZmirtrees _T2i32aG7MirNode_M12mirZmirtrees;
typedef struct _I12PartialStore_3388997662 _I12PartialStore_3388997662;
typedef struct _sG5Local_M13mirZmirbodies _sG5Local_M13mirZmirbodies;
typedef struct _T2i32aG5Local_M13mirZmirbodies _T2i32aG5Local_M13mirZmirbodies;
typedef struct _L27ModuleGraphcolonObjectType__222_M20modulesZmodulegraphs _L27ModuleGraphcolonObjectType__222_M20modulesZmodulegraphs;
typedef struct NimStringV2 NimStringV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct _I11SymbolTable_3439329334 _I11SymbolTable_3439329334;
typedef struct _G9DataTable_M14mirZdatatables _G9DataTable_M14mirZdatatables;
typedef struct _I5Store_3456106507 _I5Store_3456106507;
typedef struct _ssG7MirNode_M12mirZmirtrees _ssG7MirNode_M12mirZmirtrees;
typedef struct _T2i32asG7MirNode_M12mirZmirtrees _T2i32asG7MirNode_M12mirZmirtrees;
typedef struct _su32 _su32;
typedef struct _T2i32au32 _T2i32au32;
typedef struct _I11SymbolTable_3439329302 _I11SymbolTable_3439329302;
typedef struct _I5Store_3439329304 _I5Store_3439329304;
typedef struct _srG4TSym_M14astZast95types _srG4TSym_M14astZast95types;
typedef struct _T2i32arG4TSym_M14astZast95types _T2i32arG4TSym_M14astZast95types;
typedef struct _I5Table_3439329307 _I5Table_3439329307;
typedef struct _sT3i32i32u32 _sT3i32i32u32;
typedef struct _T2i32aT3i32i32u32 _T2i32aT3i32i32u32;
typedef struct _I11SymbolTable_3439329318 _I11SymbolTable_3439329318;
typedef struct _I5Store_3439329320 _I5Store_3439329320;
typedef struct _I5Table_3439329323 _I5Table_3439329323;
typedef struct _I5Store_3439329336 _I5Store_3439329336;
typedef struct _I5Table_3439329339 _I5Table_3439329339;
typedef struct _G7TypeEnv_M12mirZmirtypes _G7TypeEnv_M12mirZmirtypes;
typedef struct _I9TypeTable_3472883739 _I9TypeTable_3472883739;
typedef struct _I5Table_3472883741 _I5Table_3472883741;
typedef struct _sT3i32rG5TType_M14astZast95typesu32 _sT3i32rG5TType_M14astZast95typesu32;
typedef struct _T2i32aT3i32rG5TType_M14astZast95typesu32 _T2i32aT3i32rG5TType_M14astZast95typesu32;
typedef struct _I5Store_3472883752 _I5Store_3472883752;
typedef struct _sG7TypeSym_M12mirZmirtypes _sG7TypeSym_M12mirZmirtypes;
typedef struct _T2i32aG7TypeSym_M12mirZmirtypes _T2i32aG7TypeSym_M12mirZmirtypes;
typedef struct _I5Store_3472883760 _I5Store_3472883760;
typedef struct _sG10TypeHeader_M12mirZmirtypes _sG10TypeHeader_M12mirZmirtypes;
typedef struct _T2i32aG10TypeHeader_M12mirZmirtypes _T2i32aG10TypeHeader_M12mirZmirtypes;
typedef struct _sG8RecField_M12mirZmirtypes _sG8RecField_M12mirZmirtypes;
typedef struct _T2i32aG8RecField_M12mirZmirtypes _T2i32aG8RecField_M12mirZmirtypes;
typedef struct _sT2u32u32 _sT2u32u32;
typedef struct _T2i32aT2u32u32 _T2i32aT2u32u32;
typedef struct _I5Table_3472883772 _I5Table_3472883772;
typedef struct _sT3i32u32u32 _sT3i32u32u32;
typedef struct _T2i32aT3i32u32u32 _T2i32aT3i32u32u32;
typedef struct _I5Table_3472883783 _I5Table_3472883783;
typedef struct _sT3i32A16u8u32 _sT3i32A16u8u32;
typedef struct _T2i32aT3i32A16u8u32 _T2i32aT3i32A16u8u32;
typedef struct _I7BiTable_2684354600 _I7BiTable_2684354600;
typedef struct _sS _sS;
typedef struct _T2i32aS _T2i32aS;
typedef struct _I7BiTable_2684354606 _I7BiTable_2684354606;
typedef struct _si64 _si64;
typedef struct _T2i32ai64 _T2i32ai64;
typedef struct _L25ConfigRefcolonObjectType__1291_M13frontZoptions _L25ConfigRefcolonObjectType__1291_M13frontZoptions;
typedef struct _I5Store_3439329356 _I5Store_3439329356;
typedef struct _srG5TNode_M14astZast95types _srG5TNode_M14astZast95types;
typedef struct _T2i32arG5TNode_M14astZast95types _T2i32arG5TNode_M14astZast95types;
typedef struct _I8NimSeqV2_4680843623 _I8NimSeqV2_4680843623;
typedef struct _I13NimSeqPayload_4680843626 _I13NimSeqPayload_4680843626;
typedef struct _T3Si32i32 _T3Si32i32;
typedef struct _L9RefHeader_2502_M6system _L9RefHeader_2502_M6system;
typedef struct TNimTypeV2 TNimTypeV2;
struct _sG5Block_M18mirZmirgen95blocks {
NI32 len;
_T2i32aG5Block_M18mirZmirgen95blocks* p;
};
struct _I8NimSeqV2_4680843406 {
NI32 len;
_I13NimSeqPayload_4680843409* p;
};
struct _I6Option_4680843275 {
NU32 val;
NIM_BOOL has;
};
struct _G7MirNode_M12mirZmirtrees {
NU32 typ;
NU32 info;
NU8 kind;
union {
struct {
NU32 prc;
} _kind_1;
struct {
NU32 global;
} _kind_2;
struct {
NU32 cnst;
} _kind_3;
struct {
NU32 local;
} _kind_4;
struct {
NI32 field;
} _kind_5;
struct {
NU32 number;
} _kind_6;
struct {
NU32 strVal;
} _kind_7;
struct {
NU32 ast;
} _kind_8;
struct {
NU32 label;
} _kind_9;
struct {
NU32 imm;
} _kind_10;
struct {
NU16 magic;
} _kind_11;
struct {
} _kind_12;
struct {
NU32 len;
} _kind_13;
};
};
struct _G5Value_M13mirZmirconstr {
_G7MirNode_M12mirZmirtrees node;
NU32 info;
};
struct _I6Option_4680843283 {
_G5Value_M13mirZmirconstr val;
NIM_BOOL has;
};
struct _si32 {
NI32 len;
_T2i32ai32* p;
};
struct _G5Block_M18mirZmirgen95blocks {
_I6Option_4680843275 id;
NU8 kind;
union {
struct {
_G4TSym_M14astZast95types* label;
} _kind_1;
struct {
NI32 numRegistered;
} _kind_2;
struct {
_I6Option_4680843283 selector;
_si32 exits;
} _kind_3;
struct {
_G5Value_M13mirZmirconstr selectorVar;
NI32 excState;
} _kind_4;
struct {
} _kind_5;
};
};
struct _I13NimSeqPayload_4680843409 {
NI32 cap;
_G5Block_M18mirZmirgen95blocks data[SEQ_DECL_SIZE];
};
struct _sT2G5Value_M13mirZmirconstrI6Option_4680843275 {
NI32 len;
_T2i32aT2G5Value_M13mirZmirconstrI6Option_4680843275* p;
};
struct _G8BlockCtx_M18mirZmirgen95blocks {
_sG5Block_M18mirZmirgen95blocks blocks;
_sT2G5Value_M13mirZmirconstrI6Option_4680843275 toDestroy;
NI32 currScope;
};
struct _T2G5Value_M13mirZmirconstrI6Option_4680843275 {
_G5Value_M13mirZmirconstr Field0;
_I6Option_4680843275 Field1;
};
struct _T2i32aT2G5Value_M13mirZmirconstrI6Option_4680843275 {
NI32 cap;
_T2G5Value_M13mirZmirconstrI6Option_4680843275 data[SEQ_DECL_SIZE];
};
struct _G7Context_M13mirZmirconstr {
NU32 pos;
NI32 num;
};
struct _T2i32aG5Block_M18mirZmirgen95blocks {
NI32 cap;
_G5Block_M18mirZmirgen95blocks data[SEQ_DECL_SIZE];
};
struct _G5Local_M13mirZmirbodies {
NU32 typ;
NU32 alignment;
NU64 flags;
NIM_BOOL isImmutable;
_G6TIdent_M10astZidents* name;
};
struct _sG7MirNode_M12mirZmirtrees {
NI32 len;
_T2i32aG7MirNode_M12mirZmirtrees* p;
};
struct _L9MirBuffer_12_M13mirZmirconstr {
_sG7MirNode_M12mirZmirtrees nodes;
NI32 cursor;
NI32 num;
};
struct _sG5Local_M13mirZmirbodies {
NI32 len;
_T2i32aG5Local_M13mirZmirbodies* p;
};
struct _I12PartialStore_3388997662 {
_sG5Local_M13mirZmirbodies data;
NU32 base;
};
struct _G10MirBuilder_M13mirZmirconstr {
_L9MirBuffer_12_M13mirZmirconstr front;
_L9MirBuffer_12_M13mirZmirconstr back;
NIM_BOOL swapped;
NU32 currentSourceId;
_I12PartialStore_3388997662 locals;
NU32 nextLabel;
};
struct NimStringV2 {
NI32 len;
NimStrPayload* p;
};
struct NimStrPayload {
NI32 cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct _ssG7MirNode_M12mirZmirtrees {
NI32 len;
_T2i32asG7MirNode_M12mirZmirtrees* p;
};
struct _I5Store_3456106507 {
_ssG7MirNode_M12mirZmirtrees data;
};
struct _su32 {
NI32 len;
_T2i32au32* p;
};
struct _G9DataTable_M14mirZdatatables {
_I5Store_3456106507 vals;
_su32 keys;
};
struct _srG4TSym_M14astZast95types {
NI32 len;
_T2i32arG4TSym_M14astZast95types* p;
};
struct _I5Store_3439329304 {
_srG4TSym_M14astZast95types data;
};
struct _sT3i32i32u32 {
NI32 len;
_T2i32aT3i32i32u32* p;
};
struct _I5Table_3439329307 {
_sT3i32i32u32 data;
NI32 counter;
};
struct _I11SymbolTable_3439329302 {
_I5Store_3439329304 data;
_I5Table_3439329307 map;
};
struct _I5Store_3439329320 {
_srG4TSym_M14astZast95types data;
};
struct _I5Table_3439329323 {
_sT3i32i32u32 data;
NI32 counter;
};
struct _I11SymbolTable_3439329318 {
_I5Store_3439329320 data;
_I5Table_3439329323 map;
};
struct _I5Store_3439329336 {
_srG4TSym_M14astZast95types data;
};
struct _I5Table_3439329339 {
_sT3i32i32u32 data;
NI32 counter;
};
struct _I11SymbolTable_3439329334 {
_I5Store_3439329336 data;
_I5Table_3439329339 map;
};
struct _sT3i32rG5TType_M14astZast95typesu32 {
NI32 len;
_T2i32aT3i32rG5TType_M14astZast95typesu32* p;
};
struct _I5Table_3472883741 {
_sT3i32rG5TType_M14astZast95typesu32 data;
NI32 counter;
};
struct _I9TypeTable_3472883739 {
_I5Table_3472883741 inner;
};
struct _sG7TypeSym_M12mirZmirtypes {
NI32 len;
_T2i32aG7TypeSym_M12mirZmirtypes* p;
};
struct _I5Store_3472883752 {
_sG7TypeSym_M12mirZmirtypes data;
};
struct _sG10TypeHeader_M12mirZmirtypes {
NI32 len;
_T2i32aG10TypeHeader_M12mirZmirtypes* p;
};
struct _I5Store_3472883760 {
_sG10TypeHeader_M12mirZmirtypes data;
};
struct _sG8RecField_M12mirZmirtypes {
NI32 len;
_T2i32aG8RecField_M12mirZmirtypes* p;
};
struct _sT2u32u32 {
NI32 len;
_T2i32aT2u32u32* p;
};
struct _sT3i32u32u32 {
NI32 len;
_T2i32aT3i32u32u32* p;
};
struct _I5Table_3472883772 {
_sT3i32u32u32 data;
NI32 counter;
};
struct _sT3i32A16u8u32 {
NI32 len;
_T2i32aT3i32A16u8u32* p;
};
struct _I5Table_3472883783 {
_sT3i32A16u8u32 data;
NI32 counter;
};
struct _sS {
NI32 len;
_T2i32aS* p;
};
struct _I7BiTable_2684354600 {
_sS vals;
_su32 keys;
};
struct _si64 {
NI32 len;
_T2i32ai64* p;
};
struct _I7BiTable_2684354606 {
_si64 vals;
_su32 keys;
};
struct _G7TypeEnv_M12mirZmirtypes {
_I9TypeTable_3472883739 map;
_I5Store_3472883752 symbols;
_I5Store_3472883760 headers;
_sG8RecField_M12mirZmirtypes fields;
_sT2u32u32 params;
_su32 structs;
NI32 numStructs;
_I5Table_3472883772 canon;
_I5Table_3472883783 instances;
_I7BiTable_2684354600 idents;
_I7BiTable_2684354606 numbers;
_L25ConfigRefcolonObjectType__1291_M13frontZoptions* config;
_L27ModuleGraphcolonObjectType__222_M20modulesZmodulegraphs* graph;
NU32 sizeType;
NU32 usizeType;
};
struct _srG5TNode_M14astZast95types {
NI32 len;
_T2i32arG5TNode_M14astZast95types* p;
};
struct _I5Store_3439329356 {
_srG5TNode_M14astZast95types data;
};
struct _G6MirEnv_M10mirZmirenv {
_G9DataTable_M14mirZdatatables data;
_I11SymbolTable_3439329302 constants;
_I11SymbolTable_3439329318 globals;
_I11SymbolTable_3439329334 procedures;
_G7TypeEnv_M12mirZmirtypes types;
_I7BiTable_2684354606 numbers;
_I7BiTable_2684354600 strings;
_I5Store_3439329356 asts;
_su32 bodies;
};
struct _I8NimSeqV2_4680843623 {
NI32 len;
_I13NimSeqPayload_4680843626* p;
};
struct _I13NimSeqPayload_4680843626 {
NI32 cap;
_T2G5Value_M13mirZmirconstrI6Option_4680843275 data[SEQ_DECL_SIZE];
};
struct _T3Si32i32 {
NimStringV2 Field0;
NI32 Field1;
NI32 Field2;
};
struct _T2i32ai32 {
NI32 cap;
NI32 data[SEQ_DECL_SIZE];
};
struct _T2i32aG7MirNode_M12mirZmirtrees {
NI32 cap;
_G7MirNode_M12mirZmirtrees data[SEQ_DECL_SIZE];
};
struct _L9RefHeader_2502_M6system {
NI32 rc;
NI32 rootIdx;
};
N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd)(NI32 len, void* p, NI32 addlen, NI32 elemSize, NI32 elemAlign);
static N_INLINE(void, nimZeroMem)(void* p, NI32 size);
N_LIB_PRIVATE N_NIMCALL(void, add__mirZmirgen95blocks_739)(_sG5Block_M18mirZmirgen95blocks* x, _G5Block_M18mirZmirgen95blocks* value);
static N_INLINE(_G5Block_M18mirZmirgen95blocks, pop__mirZmirgen95blocks_661)(_sG5Block_M18mirZmirgen95blocks* s);
N_LIB_PRIVATE N_NIMCALL(void, emitDestroy__mirZmirgen95blocks_103)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Value_M13mirZmirconstr val);
static N_INLINE(NIM_BOOL, isNone__mirZmirgen95blocks_54)(_I6Option_4680843275 self);
static N_INLINE(_I6Option_4680843275, none__mirZmirgen95blocks_698)(void);
N_LIB_PRIVATE N_NIMCALL(NU32, allocLabel__mirZmirconstr_741)(_G10MirBuilder_M13mirZmirconstr* bu);
static N_INLINE(_I6Option_4680843275, some__mirZmirgen95blocks_59)(NU32 val);
static N_INLINE(NU32*, unsafeGet__mirZmirgen95blocks_64)(_I6Option_4680843275* self);
N_LIB_PRIVATE N_NIMCALL(void, goto__mirZmirconstr_852)(_G10MirBuilder_M13mirZmirconstr* bu, NU32 label);
static N_INLINE(NIM_BOOL, isSome__mirZmirgen95blocks_68)(_I6Option_4680843275 self);
static N_INLINE(_G7Context_M13mirZmirconstr, start__mirZmirconstr_692)(_G10MirBuilder_M13mirZmirconstr* bu, _G7MirNode_M12mirZmirtrees n);
N_LIB_PRIVATE N_NIMCALL(_G7MirNode_M12mirZmirtrees, labelNode__mirZmirgen95blocks_100)(NU32 label);
static N_INLINE(void, add__mirZmirconstr_617)(_G10MirBuilder_M13mirZmirconstr* bu, _G7MirNode_M12mirZmirtrees n);
static N_INLINE(void, finish__mirZmirconstr_708)(_G10MirBuilder_M13mirZmirconstr* bu, _G7Context_M13mirZmirconstr saved);
N_LIB_PRIVATE N_NIMCALL(void, setLen__mirZmirgen95blocks_462)(_sT2G5Value_M13mirZmirconstrI6Option_4680843275* s, NI32 newlen);
N_LIB_PRIVATE N_NIMCALL(void, raiseExit__mirZmirgen95blocks_631)(_G8BlockCtx_M18mirZmirgen95blocks* c, _G10MirBuilder_M13mirZmirconstr* bu);
N_LIB_PRIVATE N_NIMCALL(void, join__mirZmirconstr_847)(_G10MirBuilder_M13mirZmirconstr* bu, NU32 label);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___mirZmirgen95blocks_124)(_G5Block_M18mirZmirgen95blocks* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NU32, requestLabel__mirZmirgen95blocks_50)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Block_M18mirZmirgen95blocks* b);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___experimentalZcolortext_1745)(_si32* dest);
N_LIB_PRIVATE N_NIMCALL(void, add__mirZmirgen95blocks_702)(_sT2G5Value_M13mirZmirconstrI6Option_4680843275* x, _T2G5Value_M13mirZmirconstrI6Option_4680843275* value);
static N_INLINE(NIM_BOOL, isSome__mirZmirgen95blocks_320)(_I6Option_4680843283 self);
N_LIB_PRIVATE N_NIMCALL(NI32, incl__mirZmirgen95blocks_325)(_si32* s, NI32 val);
static N_INLINE(_G5Value_M13mirZmirconstr*, unsafeGet__mirZmirgen95blocks_347)(_I6Option_4680843283* self);
static N_INLINE(void, use__mirZmirconstr_760)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Value_M13mirZmirconstr val);
static N_INLINE(NU32, getOrIncl__mirZinjecthooks_481)(_G6MirEnv_M10mirZmirenv* env, NI64 v);
N_LIB_PRIVATE N_NIMCALL(_G5Value_M13mirZmirconstr, literal__mirZmirconstr_106)(NU8 kind, NU32 n, NU32 typ);
static N_INLINE(NU32, addLocal__mirZmirconstr_565)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Local_M13mirZmirbodies data);
N_LIB_PRIVATE N_NIMCALL(_G5Value_M13mirZmirconstr, allocTemp__mirZmirconstr_726)(_G10MirBuilder_M13mirZmirconstr* bu, NU32 t, NU32 id, NIM_BOOL alias);
N_LIB_PRIVATE N_NIMCALL(void, emitByVal__mirZmirconstr_811)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Value_M13mirZmirconstr y);
N_LIB_PRIVATE N_NIMCALL(_G4TSym_M14astZast95types*, getCompilerProc__modulesZmagicsys_158)(_L27ModuleGraphcolonObjectType__222_M20modulesZmodulegraphs* g, NimStringV2 name);
N_LIB_PRIVATE N_NIMCALL(NU32, add__semZinjectdestructors_2265)(_I11SymbolTable_3439329334* tab, _G4TSym_M14astZast95types* s);
static N_INLINE(_G7MirNode_M12mirZmirtrees, procNode__mirZmirconstr_74)(NU32 id);
static N_INLINE(NU32, getOrIncl__mirZmirgen95blocks_408)(_G6MirEnv_M10mirZmirenv* env, NI32 v);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___astZreports95sem_615)(_G4TSym_M14astZast95types** dest);
N_LIB_PRIVATE N_NIMCALL(void, shrink__mirZmirgen95blocks_470)(_sT2G5Value_M13mirZmirconstrI6Option_4680843275* x, NI32 newLen);
static N_INLINE(void, zeroMem__system_1704)(void* p, NI32 size);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI32 align);
N_LIB_PRIVATE N_NOINLINE(void, unreachableImpl__utilsZidioms_15)(NimStringV2 str, _T3Si32i32 loc);
N_LIB_PRIVATE N_NIMCALL(void, add__experimentalZdiff_238)(_si32* x, NI32 value);
N_LIB_PRIVATE N_NIMCALL(NU32, getOrIncl__icZic_1904)(_I7BiTable_2684354606* t, NI64 v);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI32 size);
N_LIB_PRIVATE N_NIMCALL(void, shrink__mirZmirgen95blocks_184)(_sG5Block_M18mirZmirgen95blocks* x, NI32 newLen);
N_LIB_PRIVATE N_NIMCALL(void, add__mirZmirconstr_624)(_sG7MirNode_M12mirZmirtrees* x, _G7MirNode_M12mirZmirtrees value);
static N_INLINE(NI32, len__mirZmirconstr_216)(_L9MirBuffer_12_M13mirZmirconstr b);
static N_INLINE(NI32, minuspercent___system_707)(NI32 x, NI32 y);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3135)(NIM_BOOL isDestroyAction, _L9RefHeader_2502_M6system* s, TNimTypeV2* desc);
static N_INLINE(NIM_BOOL, isSome__mirZmirconstr_763)(NU32 i);
static N_INLINE(NU32, X5BX5D___mirZmirconstr_771)(NU32 i);
N_LIB_PRIVATE N_NIMCALL(void, add__mirZmirconstr_644)(_G10MirBuilder_M13mirZmirconstr* bu, NU32 id, _G7MirNode_M12mirZmirtrees n);
N_LIB_PRIVATE N_NIMCALL(NU32, add__mirZmirconstr_569)(_I12PartialStore_3388997662* s, _G5Local_M13mirZmirbodies item);
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__UsXpUPjMR8JNUzqmpi6SXA_1 = { 17 | NIM_STRLIT_FLAG, "nimAbortException" };
static const NimStringV2 TM__UsXpUPjMR8JNUzqmpi6SXA_2 = {17, (NimStrPayload*)&TM__UsXpUPjMR8JNUzqmpi6SXA_1};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__UsXpUPjMR8JNUzqmpi6SXA_3 = { 14 | NIM_STRLIT_FLAG, "nimLeaveExcept" };
static const NimStringV2 TM__UsXpUPjMR8JNUzqmpi6SXA_4 = {14, (NimStrPayload*)&TM__UsXpUPjMR8JNUzqmpi6SXA_3};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__UsXpUPjMR8JNUzqmpi6SXA_5 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__UsXpUPjMR8JNUzqmpi6SXA_6 = {0, (NimStrPayload*)&TM__UsXpUPjMR8JNUzqmpi6SXA_5};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__UsXpUPjMR8JNUzqmpi6SXA_8 = { 17 | NIM_STRLIT_FLAG, "mirgen_blocks.nim" };
static NIM_CONST _T3Si32i32 TM__UsXpUPjMR8JNUzqmpi6SXA_7 = {{17, (NimStrPayload*)&TM__UsXpUPjMR8JNUzqmpi6SXA_8},
((NI32) 182),
((NI32) 17)}
;
extern NIM_BOOL nimInErrorMode__system_4132;
N_LIB_PRIVATE N_NIMCALL(void, add__mirZmirgen95blocks_739)(_sG5Block_M18mirZmirgen95blocks* x, _G5Block_M18mirZmirgen95blocks* value) {
	NI32 oldLen;
	_sG5Block_M18mirZmirgen95blocks* _6;
	_I8NimSeqV2_4680843406* _7;
	_I8NimSeqV2_4680843406* xu;
	NIM_BOOL _8;
	_I8NimSeqV2_4680843406* _9;
	NIM_BOOL _11;
	_I8NimSeqV2_4680843406* _21;
	_I8NimSeqV2_4680843406* _22;
	_I13NimSeqPayload_4680843409* _23;
	oldLen = (*x).len;
	_6 = x;
	_7 = ((_I8NimSeqV2_4680843406*) (_6));
	xu = _7;
	_8 = 0;
	_9 = xu;
	_8 = ((*_9).p == ((_I13NimSeqPayload_4680843409*) NIM_NIL));
	_11 = !(_8);
	if (_11)
	{
		_I8NimSeqV2_4680843406* _12;
		_I13NimSeqPayload_4680843409* _13;
		NI32 _14;
		NI32 _15;
		_12 = xu;
		_13 = (*_12).p;
		_14 = (*_13).cap;
		_15 = (NI32)(oldLen + ((NI32) 1));
		_8 = (_14 < _15);
	}
	if (_8)
	{
		_I8NimSeqV2_4680843406* _16;
		_I8NimSeqV2_4680843406* _17;
		void* _18;
		void* _19;
		_I13NimSeqPayload_4680843409* _20;
		_16 = xu;
		_17 = xu;
		_18 = ((void*) ((*_17).p));
		_19 = prepareSeqAdd(oldLen, _18, ((NI32) 1), ((NI32) 44), ((NI32) 4));
		_20 = ((_I13NimSeqPayload_4680843409*) (_19));
		(*_16).p = _20;
	}
	_21 = xu;
	(*_21).len = (NI32)(oldLen + ((NI32) 1));
	_22 = xu;
	_23 = (*_22).p;
	(*_23).data[oldLen] = (*value);
	return ;
}
N_LIB_PRIVATE N_NIMCALL(NI32, startScope__mirZmirgen95blocks_736)(_G8BlockCtx_M18mirZmirgen95blocks* c) {
	NI32 result;
	_G5Block_M18mirZmirgen95blocks _2;
	result = (*c).currScope;
	nimZeroMem((void*)(&_2), sizeof(_G5Block_M18mirZmirgen95blocks));
	_2.kind = ((NU8) 1);
	add__mirZmirgen95blocks_739((&(*c).blocks), (&_2));
	(*c).currScope = ((*c).blocks.len-1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, closeScope__mirZmirgen95blocks_774)(_G8BlockCtx_M18mirZmirgen95blocks* c, _G10MirBuilder_M13mirZmirconstr* bu, NI32 nextScope, NIM_BOOL hasStructuredExit) {
	_G5Block_M18mirZmirgen95blocks scope;
	NI32 _8;
	NI32 start;
	NI32 i_2;
	NIM_BOOL _28;
	NI32 _69;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	scope = pop__mirZmirgen95blocks_661((&(*c).blocks));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_8 = (*c).toDestroy.len;
	start = (NI32)(_8 - scope._kind_2.numRegistered);
	if (hasStructuredExit)
	{
		NI32 i;
		i = ((*c).toDestroy.len-1);
		while (1) {
			NIM_BOOL colontmp_;
			NIM_BOOL _15;
			NI32 _16;
			colontmp_ = (start <= i);
			_15 = !(colontmp_);
			if (_15)
			{
				goto LA3_;
			}
			_16 = i;
			emitDestroy__mirZmirgen95blocks_103(bu, (*c).toDestroy.p->data[_16].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			i = (NI32)(i - ((NI32) 1));
		}
		LA3_:;
	}
	i_2 = ((*c).toDestroy.len-1);
	while (1) {
		NIM_BOOL _21;
		NIM_BOOL colontmp__2;
		NIM_BOOL _26;
		_21 = 0;
		_21 = (start <= i_2);
		if (_21)
		{
			NI32 _23;
			NIM_BOOL _70;
			_23 = i_2;
			_70 = isNone__mirZmirgen95blocks_54((*c).toDestroy.p->data[_23].Field1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			_21 = _70;
		}
		colontmp__2 = _21;
		_26 = !(colontmp__2);
		if (_26)
		{
			goto LA8_;
		}
		i_2 = (NI32)(i_2 - ((NI32) 1));
	}
	LA8_:;
	_28 = (start <= i_2);
	if (_28)
	{
		_I6Option_4680843275 next;
		_I6Option_4680843275 curr;
		NI32 a;
		NI32 b;
		NI32 step;
		NI32 res;
		NI32 _60;
		NIM_BOOL _62;
		NIM_BOOL _66;
		next = none__mirZmirgen95blocks_698();
		if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		if (hasStructuredExit)
		{
			NU32 _30;
			_I6Option_4680843275 _71;
			NU32* _31;
			_30 = allocLabel__mirZmirconstr_741(bu);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			_71 = some__mirZmirgen95blocks_59(_30);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			next = _71;
			_31 = unsafeGet__mirZmirgen95blocks_64((&next));
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			goto__mirZmirconstr_852(bu, (*_31));
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		}
		curr = none__mirZmirgen95blocks_698();
		if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		a = i_2;
		b = start;
		step = ((NI32) 1);
		res = a;
		while (1) {
			NIM_BOOL colontmp__3;
			NIM_BOOL _41;
			NI32 i_3;
			NIM_BOOL _44;
			NI32 _59;
			colontmp__3 = (b <= res);
			_41 = !(colontmp__3);
			if (_41)
			{
				goto LA13_;
			}
			i_3 = res;
			_44 = isSome__mirZmirgen95blocks_68((*c).toDestroy.p->data[i_3].Field1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			if (_44)
			{
				NIM_BOOL _46;
				_G7MirNode_M12mirZmirtrees _54;
				_G7Context_M13mirZmirconstr savedX60gensym65_;
				NU32* _55;
				_G7MirNode_M12mirZmirtrees _57;
				_46 = isSome__mirZmirgen95blocks_68(curr);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				if (_46)
				{
					_G7MirNode_M12mirZmirtrees _48;
					_G7Context_M13mirZmirconstr savedX60gensym63_;
					_I6Option_4680843275* _49;
					NU32* _50;
					_G7MirNode_M12mirZmirtrees _52;
					nimZeroMem((void*)(&_48), sizeof(_G7MirNode_M12mirZmirtrees));
					_48.kind = ((NU8) 80);
					savedX60gensym63_ = start__mirZmirconstr_692(bu, _48);
					if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
					_49 = (&(*c).toDestroy.p->data[i_3].Field1);
					_50 = unsafeGet__mirZmirgen95blocks_64((&(*_49)));
					if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
					_52 = labelNode__mirZmirgen95blocks_100((*_50));
					if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
					add__mirZmirconstr_617(bu, _52);
					if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
					finish__mirZmirconstr_708(bu, savedX60gensym63_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				}
				curr = (*c).toDestroy.p->data[i_3].Field1;
				nimZeroMem((void*)(&_54), sizeof(_G7MirNode_M12mirZmirtrees));
				_54.kind = ((NU8) 79);
				savedX60gensym65_ = start__mirZmirconstr_692(bu, _54);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				_55 = unsafeGet__mirZmirgen95blocks_64((&curr));
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				_57 = labelNode__mirZmirgen95blocks_100((*_55));
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				add__mirZmirconstr_617(bu, _57);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
				finish__mirZmirconstr_708(bu, savedX60gensym65_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			}
			emitDestroy__mirZmirgen95blocks_103(bu, (*c).toDestroy.p->data[i_3].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			_59 = ((NI32) (step));
			res = (NI32)(res - _59);
		}
		LA13_:;
		_60 = ((NI32) (start));
		setLen__mirZmirgen95blocks_462((&(*c).toDestroy), _60);
		_62 = isSome__mirZmirgen95blocks_68(curr);
		if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		if (_62)
		{
			_G7MirNode_M12mirZmirtrees _64;
			_G7Context_M13mirZmirconstr savedX60gensym67_;
			nimZeroMem((void*)(&_64), sizeof(_G7MirNode_M12mirZmirtrees));
			_64.kind = ((NU8) 80);
			savedX60gensym67_ = start__mirZmirconstr_692(bu, _64);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			raiseExit__mirZmirgen95blocks_631(c, bu);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			finish__mirZmirconstr_708(bu, savedX60gensym67_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		}
		_66 = isSome__mirZmirgen95blocks_68(next);
		if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		if (_66)
		{
			NU32* _67;
			_67 = unsafeGet__mirZmirgen95blocks_64((&next));
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			join__mirZmirconstr_847(bu, (*_67));
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
		}
		goto LA18_;
	}
	_69 = ((NI32) (start));
	setLen__mirZmirgen95blocks_462((&(*c).toDestroy), _69);
	LA18_:;
	(*c).currScope = nextScope;
	eqdestroy___mirZmirgen95blocks_124((&scope));
	goto LA19_;
	LA4_: {
		*nimErr_ = NIM_FALSE;
		eqdestroy___mirZmirgen95blocks_124((&scope));
		*nimErr_ = NIM_TRUE;
		goto BeforeRet_;
	}
	LA19_:;
	}BeforeRet_: ;
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, raiseExit__mirZmirgen95blocks_631)(_G8BlockCtx_M18mirZmirgen95blocks* c, _G10MirBuilder_M13mirZmirconstr* bu) {
	NI32 last;
	NI32 a;
	NI32 b;
	NI32 step;
	NI32 res;
	_G7MirNode_M12mirZmirtrees _34;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	last = ((*c).toDestroy.len-1);
	a = ((*c).blocks.len-1);
	b = ((NI32) 0);
	step = ((NI32) 1);
	res = a;
	while (1) {
		NIM_BOOL colontmp_;
		NIM_BOOL _13;
		NI32 i;
		_G5Block_M18mirZmirgen95blocks b_2;
		NIM_BOOL _18;
		_G5Block_M18mirZmirgen95blocks* _30;
		NU32 _31;
		_G7MirNode_M12mirZmirtrees _32;
		NI32 _33;
		colontmp_ = (b <= res);
		_13 = !(colontmp_);
		if (_13)
		{
			goto LA2_;
		}
		i = res;
		b_2 = (*c).blocks.p->data[i];
		switch (b_2.kind) {
		case ((NU8) 0):
		goto LA3_;
		case ((NU8) 1):
		goto LA4_;
		case ((NU8) 2):
		case ((NU8) 3):
		case ((NU8) 4):
		case ((NU8) 5):
		goto LA5_;
		}
		LA3_:;
		goto LA6_;
		LA4_:;
		_18 = (((NI32) 0) < b_2._kind_2.numRegistered);
		if (_18)
		{
			NI32 _19;
			NIM_BOOL _21;
			NI32 _26;
			_I6Option_4680843275* _25;
			NU32* _27;
			_G7MirNode_M12mirZmirtrees _29;
			_19 = last;
			_21 = isNone__mirZmirgen95blocks_54((*c).toDestroy.p->data[_19].Field1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (_21)
			{
				NI32 _23;
				_I6Option_4680843275* _22;
				NU32 _24;
				_I6Option_4680843275 _35;
				_23 = last;
				_22 = (&(*c).toDestroy.p->data[_23].Field1);
				_24 = allocLabel__mirZmirconstr_741(bu);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				_35 = some__mirZmirgen95blocks_59(_24);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				(*_22) = _35;
			}
			_26 = last;
			_25 = (&(*c).toDestroy.p->data[_26].Field1);
			_27 = unsafeGet__mirZmirgen95blocks_64((&(*_25)));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_29 = labelNode__mirZmirgen95blocks_100((*_27));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			add__mirZmirconstr_617(bu, _29);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA9_;
		}
		goto LA6_;
		LA5_:;
		_30 = (&(*c).blocks.p->data[i]);
		_31 = requestLabel__mirZmirgen95blocks_50(bu, _30);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_32 = labelNode__mirZmirgen95blocks_100(_31);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		add__mirZmirconstr_617(bu, _32);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA9_;
		LA6_:;
		_33 = ((NI32) (step));
		res = (NI32)(res - _33);
	}
	LA2_:;
	nimZeroMem((void*)(&_34), sizeof(_G7MirNode_M12mirZmirtrees));
	_34.kind = ((NU8) 20);
	add__mirZmirconstr_617(bu, _34);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	LA9_:;
	}BeforeRet_: ;
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___mirZmirgen95blocks_124)(_G5Block_M18mirZmirgen95blocks* dest) {
	NIM_BOOL _4;
	switch ((*dest).kind) {
	case ((NU8) 0):
	goto LA0_;
	case ((NU8) 1):
	goto LA1_;
	case ((NU8) 3):
	goto LA2_;
	case ((NU8) 4):
	goto LA3_;
	case ((NU8) 2):
	case ((NU8) 5):
	goto LA4_;
	}
	LA0_:;
	_4 = nimDecRefIsLastCyclicDyn((*dest)._kind_1.label);
	if (_4)
	{
		nimDestroyAndDispose((*dest)._kind_1.label);
	}
	goto LA6_;
	LA1_:;
	goto LA6_;
	LA2_:;
	eqdestroy___experimentalZcolortext_1745((&(*dest)._kind_3.exits));
	goto LA6_;
	LA3_:;
	goto LA6_;
	LA4_:;
	goto LA6_;
	LA6_:;
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, register__mirZmirgen95blocks_691)(_G8BlockCtx_M18mirZmirgen95blocks* c, _G5Value_M13mirZmirconstr loc) {
	NI32 _3;
	NI32* _4;
	_G5Value_M13mirZmirconstr _5;
	_I6Option_4680843275 _6;
	_T2G5Value_M13mirZmirconstrI6Option_4680843275 _7;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	_3 = (*c).currScope;
	_4 = (&(*c).blocks.p->data[_3]._kind_2.numRegistered);
	(*_4) = (NI32)((*_4) + ((NI32) 1));
	_5 = loc;
	_6 = none__mirZmirgen95blocks_698();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_7.Field0 = _5;
	_7.Field1 = _6;
	add__mirZmirgen95blocks_702((&(*c).toDestroy), (&_7));
	}BeforeRet_: ;
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, blockExit__mirZmirgen95blocks_287)(_G8BlockCtx_M18mirZmirgen95blocks* c, _L27ModuleGraphcolonObjectType__222_M20modulesZmodulegraphs* graph, _G6MirEnv_M10mirZmirenv* env, _G10MirBuilder_M13mirZmirconstr* bu, NI32 targetBlock) {
	NI32 last;
	NI32 a;
	NI32 b;
	NI32 step;
	NI32 res;
	_G7MirNode_M12mirZmirtrees _94;
	_G7Context_M13mirZmirconstr savedX60gensym35_;
	_G5Block_M18mirZmirgen95blocks* _95;
	NU32 _96;
	_G7MirNode_M12mirZmirtrees _97;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	last = ((*c).toDestroy.len-1);
	a = ((*c).blocks.len-1);
	b = (NI32)(targetBlock + ((NI32) 1));
	step = ((NI32) 1);
	res = a;
	while (1) {
		NIM_BOOL colontmp_;
		NIM_BOOL _16;
		NI32 i;
		_G5Block_M18mirZmirgen95blocks b_2;
		NI32 start;
		NI32 j;
		NIM_BOOL _31;
		_G7MirNode_M12mirZmirtrees _42;
		_G7Context_M13mirZmirconstr savedX60gensym12_;
		_G5Block_M18mirZmirgen95blocks* _43;
		NU32 _44;
		_G7MirNode_M12mirZmirtrees _45;
		_G5Local_M13mirZmirbodies _49;
		NU32 idX60gensym14_;
		_G5Value_M13mirZmirconstr valX60gensym13_;
		_G7MirNode_M12mirZmirtrees _52;
		_G7Context_M13mirZmirconstr savedX60gensym15_;
		_G5Value_M13mirZmirconstr _53;
		_G7MirNode_M12mirZmirtrees _55;
		_G7Context_M13mirZmirconstr savedX60gensym18_;
		_G7MirNode_M12mirZmirtrees _56;
		_G7MirNode_M12mirZmirtrees _57;
		NI64 _59;
		NU32 _60;
		_G5Value_M13mirZmirconstr _61;
		_G5Value_M13mirZmirconstr tmp;
		NU32 labelX60gensym19_;
		_G7MirNode_M12mirZmirtrees _64;
		_G7Context_M13mirZmirconstr savedX60gensym21_;
		_G5Value_M13mirZmirconstr _65;
		NU32 _66;
		_G7MirNode_M12mirZmirtrees _67;
		_G7MirNode_M12mirZmirtrees _69;
		_G7Context_M13mirZmirconstr savedX60gensym23_;
		_G4TSym_M14astZast95types* p;
		_G7MirNode_M12mirZmirtrees _72;
		_G7Context_M13mirZmirconstr savedX60gensym26_;
		_G7MirNode_M12mirZmirtrees _73;
		NU32 _75;
		_G7MirNode_M12mirZmirtrees _76;
		NU32 _77;
		_G5Value_M13mirZmirconstr _78;
		_G7MirNode_M12mirZmirtrees _80;
		_G7Context_M13mirZmirconstr savedX60gensym28_;
		NU32 _81;
		_G7MirNode_M12mirZmirtrees _82;
		_G7MirNode_M12mirZmirtrees _84;
		_G7Context_M13mirZmirconstr savedX60gensym30_;
		_G4TSym_M14astZast95types* p_2;
		_G7MirNode_M12mirZmirtrees _87;
		_G7Context_M13mirZmirconstr savedX60gensym33_;
		_G7MirNode_M12mirZmirtrees _88;
		NU32 _90;
		_G7MirNode_M12mirZmirtrees _91;
		NI32 _92;
		colontmp_ = (b <= res);
		_16 = !(colontmp_);
		if (_16)
		{
			goto LA2_;
		}
		i = res;
		b_2 = (*c).blocks.p->data[i];
		switch (b_2.kind) {
		case ((NU8) 1):
		goto LA3_;
		case ((NU8) 3):
		goto LA4_;
		case ((NU8) 4):
		goto LA5_;
		case ((NU8) 5):
		goto LA6_;
		case ((NU8) 0):
		case ((NU8) 2):
		goto LA7_;
		}
		LA3_:;
		start = (NI32)(last - b_2._kind_2.numRegistered);
		j = last;
		while (1) {
			NIM_BOOL colontmp__2;
			NIM_BOOL _27;
			NI32 _28;
			colontmp__2 = (start < j);
			_27 = !(colontmp__2);
			if (_27)
			{
				goto LA10_;
			}
			_28 = j;
			emitDestroy__mirZmirgen95blocks_103(bu, (*c).toDestroy.p->data[_28].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			j = (NI32)(j - ((NI32) 1));
		}
		LA10_:;
		last = start;
		goto LA11_;
		LA4_:;
		_31 = isSome__mirZmirgen95blocks_320(b_2._kind_3.selector);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (_31)
		{
			_si32* _33;
			NI32 pos;
			_G7MirNode_M12mirZmirtrees _35;
			_G7Context_M13mirZmirconstr savedX60gensym8_;
			_G5Value_M13mirZmirconstr* _36;
			_G5Value_M13mirZmirconstr _37;
			NI64 _38;
			NU32 _39;
			_G5Value_M13mirZmirconstr _40;
			_33 = (&(*c).blocks.p->data[i]._kind_3.exits);
			pos = incl__mirZmirgen95blocks_325(_33, targetBlock);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimZeroMem((void*)(&_35), sizeof(_G7MirNode_M12mirZmirtrees));
			_35.kind = ((NU8) 25);
			savedX60gensym8_ = start__mirZmirconstr_692(bu, _35);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_36 = unsafeGet__mirZmirgen95blocks_347((&b_2._kind_3.selector));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_37 = (*_36);
			use__mirZmirconstr_760(bu, _37);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_38 = ((NI64) (pos));
			_39 = getOrIncl__mirZinjecthooks_481(env, _38);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_40 = literal__mirZmirconstr_106(((NU8) 12), _39, ((NU32) 9));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			use__mirZmirconstr_760(bu, _40);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			finish__mirZmirconstr_708(bu, savedX60gensym8_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		nimZeroMem((void*)(&_42), sizeof(_G7MirNode_M12mirZmirtrees));
		_42.kind = ((NU8) 71);
		savedX60gensym12_ = start__mirZmirconstr_692(bu, _42);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_43 = (&(*c).blocks.p->data[i]);
		_44 = requestLabel__mirZmirgen95blocks_50(bu, _43);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_45 = labelNode__mirZmirgen95blocks_100(_44);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		add__mirZmirconstr_617(bu, _45);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		finish__mirZmirconstr_708(bu, savedX60gensym12_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA13_;
		LA5_:;
		nimZeroMem((void*)(&_49), sizeof(_G5Local_M13mirZmirbodies));
		_49.typ = ((NU32) 1);
		idX60gensym14_ = addLocal__mirZmirconstr_565(bu, _49);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		valX60gensym13_ = allocTemp__mirZmirconstr_726((&(*bu)), ((NU32) 1), idX60gensym14_, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		nimZeroMem((void*)(&_52), sizeof(_G7MirNode_M12mirZmirtrees));
		_52.kind = ((NU8) 21);
		savedX60gensym15_ = start__mirZmirconstr_692(bu, _52);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		_53 = valX60gensym13_;
		use__mirZmirconstr_760(bu, _53);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		nimZeroMem((void*)(&_55), sizeof(_G7MirNode_M12mirZmirtrees));
		_55.kind = ((NU8) 43);
		_55.typ = ((NU32) 1);
		savedX60gensym18_ = start__mirZmirconstr_692(bu, _55);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		nimZeroMem((void*)(&_56), sizeof(_G7MirNode_M12mirZmirtrees));
		_56.kind = ((NU8) 18);
		_56._kind_10.imm = ((NU32) 0);
		add__mirZmirconstr_617(bu, _56);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		nimZeroMem((void*)(&_57), sizeof(_G7MirNode_M12mirZmirtrees));
		_57.kind = ((NU8) 19);
		_57._kind_11.magic = ((NU16) 67);
		add__mirZmirconstr_617(bu, _57);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		emitByVal__mirZmirconstr_811(bu, b_2._kind_4.selectorVar);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		_59 = ((NI64) (b_2._kind_4.excState));
		_60 = getOrIncl__mirZinjecthooks_481(env, _59);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		_61 = literal__mirZmirconstr_106(((NU8) 12), _60, ((NU32) 9));
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		emitByVal__mirZmirconstr_811(bu, _61);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		finish__mirZmirconstr_708(bu, savedX60gensym18_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		finish__mirZmirconstr_708(bu, savedX60gensym15_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		tmp = valX60gensym13_;
		labelX60gensym19_ = allocLabel__mirZmirconstr_741(bu);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		nimZeroMem((void*)(&_64), sizeof(_G7MirNode_M12mirZmirtrees));
		_64.kind = ((NU8) 72);
		savedX60gensym21_ = start__mirZmirconstr_692(bu, _64);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		_65 = tmp;
		use__mirZmirconstr_760(bu, _65);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		_66 = labelX60gensym19_;
		nimZeroMem((void*)(&_67), sizeof(_G7MirNode_M12mirZmirtrees));
		_67.kind = ((NU8) 10);
		_67._kind_9.label = _66;
		add__mirZmirconstr_617(bu, _67);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		finish__mirZmirconstr_708(bu, savedX60gensym21_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		nimZeroMem((void*)(&_69), sizeof(_G7MirNode_M12mirZmirtrees));
		_69.kind = ((NU8) 68);
		savedX60gensym23_ = start__mirZmirconstr_692(bu, _69);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		p = getCompilerProc__modulesZmagicsys_158(graph, TM__UsXpUPjMR8JNUzqmpi6SXA_2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
		nimZeroMem((void*)(&_72), sizeof(_G7MirNode_M12mirZmirtrees));
		_72.kind = ((NU8) 43);
		_72.typ = ((NU32) 0);
		savedX60gensym26_ = start__mirZmirconstr_692(bu, _72);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		nimZeroMem((void*)(&_73), sizeof(_G7MirNode_M12mirZmirtrees));
		_73.kind = ((NU8) 18);
		_73._kind_10.imm = ((NU32) 0);
		add__mirZmirconstr_617(bu, _73);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		_75 = add__semZinjectdestructors_2265((&(*env).procedures), p);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		_76 = procNode__mirZmirconstr_74(_75);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		add__mirZmirconstr_617(bu, _76);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		_77 = getOrIncl__mirZmirgen95blocks_408(env, ((NI32) 0));
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		_78 = literal__mirZmirconstr_106(((NU8) 12), _77, ((NU32) 1));
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		emitByVal__mirZmirconstr_811(bu, _78);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		finish__mirZmirconstr_708(bu, savedX60gensym26_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		finish__mirZmirconstr_708(bu, savedX60gensym23_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		nimZeroMem((void*)(&_80), sizeof(_G7MirNode_M12mirZmirtrees));
		_80.kind = ((NU8) 81);
		savedX60gensym28_ = start__mirZmirconstr_692(bu, _80);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		_81 = labelX60gensym19_;
		nimZeroMem((void*)(&_82), sizeof(_G7MirNode_M12mirZmirtrees));
		_82.kind = ((NU8) 10);
		_82._kind_9.label = _81;
		add__mirZmirconstr_617(bu, _82);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		finish__mirZmirconstr_708(bu, savedX60gensym28_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		eqdestroy___astZreports95sem_615((&p));
		goto LA11_;
		LA15_: {
			*nimErr_ = NIM_FALSE;
			eqdestroy___astZreports95sem_615((&p));
			*nimErr_ = NIM_TRUE;
			goto LA14_;
		}
		LA14_: {
			*nimErr_ = NIM_FALSE;
			*nimErr_ = NIM_TRUE;
			goto BeforeRet_;
		}
		LA6_:;
		nimZeroMem((void*)(&_84), sizeof(_G7MirNode_M12mirZmirtrees));
		_84.kind = ((NU8) 68);
		savedX60gensym30_ = start__mirZmirconstr_692(bu, _84);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		p_2 = getCompilerProc__modulesZmagicsys_158(graph, TM__UsXpUPjMR8JNUzqmpi6SXA_4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&_87), sizeof(_G7MirNode_M12mirZmirtrees));
		_87.kind = ((NU8) 43);
		_87.typ = ((NU32) 0);
		savedX60gensym33_ = start__mirZmirconstr_692(bu, _87);
		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
		nimZeroMem((void*)(&_88), sizeof(_G7MirNode_M12mirZmirtrees));
		_88.kind = ((NU8) 18);
		_88._kind_10.imm = ((NU32) 0);
		add__mirZmirconstr_617(bu, _88);
		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
		_90 = add__semZinjectdestructors_2265((&(*env).procedures), p_2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
		_91 = procNode__mirZmirconstr_74(_90);
		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
		add__mirZmirconstr_617(bu, _91);
		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
		finish__mirZmirconstr_708(bu, savedX60gensym33_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
		finish__mirZmirconstr_708(bu, savedX60gensym30_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
		eqdestroy___astZreports95sem_615((&p_2));
		goto LA11_;
		LA16_: {
			*nimErr_ = NIM_FALSE;
			eqdestroy___astZreports95sem_615((&p_2));
			*nimErr_ = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_:;
		goto LA11_;
		LA11_:;
		_92 = ((NI32) (step));
		res = (NI32)(res - _92);
	}
	LA2_:;
	nimZeroMem((void*)(&_94), sizeof(_G7MirNode_M12mirZmirtrees));
	_94.kind = ((NU8) 71);
	savedX60gensym35_ = start__mirZmirconstr_692(bu, _94);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_95 = (&(*c).blocks.p->data[targetBlock]);
	_96 = requestLabel__mirZmirgen95blocks_50(bu, _95);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_97 = labelNode__mirZmirgen95blocks_100(_96);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	add__mirZmirconstr_617(bu, _97);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	finish__mirZmirconstr_708(bu, savedX60gensym35_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	LA13_:;
	}BeforeRet_: ;
	return ;
}
N_LIB_PRIVATE N_NIMCALL(NI32, findBlock__mirZmirgen95blocks_608)(_G8BlockCtx_M18mirZmirgen95blocks c, _G4TSym_M14astZast95types* label) {
	NI32 result;
	NI32 i;
	i = (c.blocks.len-1);
	while (1) {
		NIM_BOOL _5;
		NIM_BOOL colontmp_;
		NIM_BOOL _14;
		_5 = 0;
		_5 = (((NI32) 0) <= i);
		if (_5)
		{
			NIM_BOOL _7;
			NI32 _8;
			NIM_BOOL _9;
			NIM_BOOL _10;
			_7 = 0;
			_8 = i;
			_9 = (c.blocks.p->data[_8].kind == ((NU8) 0));
			_7 = !(_9);
			_10 = !(_7);
			if (_10)
			{
				NI32 _11;
				NIM_BOOL _12;
				_11 = i;
				_12 = (c.blocks.p->data[_11]._kind_1.label == label);
				_7 = !(_12);
			}
			_5 = _7;
		}
		colontmp_ = _5;
		_14 = !(colontmp_);
		if (_14)
		{
			goto LA4_;
		}
		i = (NI32)(i - ((NI32) 1));
	}
	LA4_:;
	result = i;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, emitDestroy__mirZmirgen95blocks_103)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Value_M13mirZmirconstr val) {
	_G7MirNode_M12mirZmirtrees _4;
	_G7Context_M13mirZmirconstr savedX60gensym3_;
	_G5Value_M13mirZmirconstr _5;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&_4), sizeof(_G7MirNode_M12mirZmirtrees));
	_4.kind = ((NU8) 82);
	savedX60gensym3_ = start__mirZmirconstr_692(bu, _4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_5 = val;
	use__mirZmirconstr_760(bu, _5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	finish__mirZmirconstr_708(bu, savedX60gensym3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return ;
}
static N_INLINE(NIM_BOOL, isNone__mirZmirgen95blocks_54)(_I6Option_4680843275 self) {
	NIM_BOOL result;
	result = !(self.has);
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(_I6Option_4680843275, none__mirZmirgen95blocks_698)(void) {
	_I6Option_4680843275 result;
	nimZeroMem((void*)(&result), sizeof(_I6Option_4680843275));
	return result;
}
static N_INLINE(_I6Option_4680843275, some__mirZmirgen95blocks_59)(NU32 val) {
	_I6Option_4680843275 result;
	nimZeroMem((void*)(&result), sizeof(_I6Option_4680843275));
	result.has = NIM_TRUE;
	result.val = val;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(_G7MirNode_M12mirZmirtrees, labelNode__mirZmirgen95blocks_100)(NU32 label) {
	_G7MirNode_M12mirZmirtrees result;
	NU32 _2;
	_2 = label;
	nimZeroMem((void*)(&result), sizeof(_G7MirNode_M12mirZmirtrees));
	result.kind = ((NU8) 10);
	result._kind_9.label = _2;
	goto LA0_;
	LA0_:;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setLen__mirZmirgen95blocks_462)(_sT2G5Value_M13mirZmirconstrI6Option_4680843275* s, NI32 newlen) {
	NI32 _3;
	NI32 _5;
	NIM_BOOL _6;
	NI32 oldLen;
	NI32 _9;
	NIM_BOOL _10;
	_sT2G5Value_M13mirZmirconstrI6Option_4680843275* _12;
	_I8NimSeqV2_4680843623* _13;
	_I8NimSeqV2_4680843623* xu;
	NIM_BOOL _14;
	_I8NimSeqV2_4680843623* _15;
	NIM_BOOL _17;
	_I8NimSeqV2_4680843623* _29;
	_I8NimSeqV2_4680843623* _30;
	_I13NimSeqPayload_4680843626* _31;
	_T2G5Value_M13mirZmirconstrI6Option_4680843275* _32;
	void* _33;
	NI32 _34;
	NI32 _35;
	NI32 _36;
	NI32 _37;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	_3 = ((NI32) (newlen));
	_5 = (*s).len;
	_6 = (_3 < _5);
	if (_6)
	{
		shrink__mirZmirgen95blocks_470(s, newlen);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA1_;
	}
	oldLen = (*s).len;
	_9 = ((NI32) (newlen));
	_10 = (_9 <= oldLen);
	if (_10)
	{
		goto LA3_;
	}
	_12 = s;
	_13 = ((_I8NimSeqV2_4680843623*) (_12));
	xu = _13;
	_14 = 0;
	_15 = xu;
	_14 = ((*_15).p == ((_I13NimSeqPayload_4680843626*) NIM_NIL));
	_17 = !(_14);
	if (_17)
	{
		_I8NimSeqV2_4680843623* _18;
		_I13NimSeqPayload_4680843626* _19;
		NI32 _20;
		NI32 _21;
		_18 = xu;
		_19 = (*_18).p;
		_20 = (*_19).cap;
		_21 = ((NI32) (newlen));
		_14 = (_20 < _21);
	}
	if (_14)
	{
		_I8NimSeqV2_4680843623* _22;
		_I8NimSeqV2_4680843623* _23;
		void* _24;
		NI32 _25;
		NI32 _26;
		void* _27;
		_I13NimSeqPayload_4680843626* _28;
		_22 = xu;
		_23 = xu;
		_24 = ((void*) ((*_23).p));
		_25 = ((NI32) (newlen));
		_26 = (NI32)(_25 - oldLen);
		_27 = prepareSeqAdd(oldLen, _24, _26, ((NI32) 28), ((NI32) 4));
		_28 = ((_I13NimSeqPayload_4680843626*) (_27));
		(*_22).p = _28;
	}
	_29 = xu;
	(*_29).len = ((NI32) (newlen));
	_30 = xu;
	_31 = (*_30).p;
	_32 = (&(*_31).data[oldLen]);
	_33 = ((void*) (_32));
	_34 = ((NI32) (newlen));
	_35 = (NI32)(_34 - oldLen);
	_36 = (NI32)(_35 * ((NI32) 28));
	_37 = ((NI32) (_36));
	zeroMem__system_1704(_33, _37);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	LA1_:;
	LA3_:;
	}BeforeRet_: ;
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, shrink__mirZmirgen95blocks_184)(_sG5Block_M18mirZmirgen95blocks* x, NI32 newLen) {
	NI32 _5;
	NI32 a;
	NI32 b;
	NI32 step;
	NI32 res;
	_sG5Block_M18mirZmirgen95blocks* _16;
	_I8NimSeqV2_4680843406* _17;
	_5 = (*x).len;
	a = (NI32)(_5 - ((NI32) 1));
	b = ((NI32) (newLen));
	step = ((NI32) 1);
	res = a;
	while (1) {
		NIM_BOOL colontmp_;
		NIM_BOOL _12;
		NI32 i;
		_G5Block_M18mirZmirgen95blocks* _14;
		NI32 _15;
		colontmp_ = (b <= res);
		_12 = !(colontmp_);
		if (_12)
		{
			goto LA2_;
		}
		i = res;
		_14 = (&(*x).p->data[i]);
		eqdestroy___mirZmirgen95blocks_124(_14);
		_15 = ((NI32) (step));
		res = (NI32)(res - _15);
	}
	LA2_:;
	_16 = x;
	_17 = ((_I8NimSeqV2_4680843406*) (_16));
	(*_17).len = ((NI32) (newLen));
	return ;
}
N_LIB_PRIVATE N_NIMCALL(NI32, closest__mirZmirgen95blocks_591)(_G8BlockCtx_M18mirZmirgen95blocks c) {
	NI32 result;
	result = (c.blocks.len-1);
	while (1) {
		NIM_BOOL _3;
		NIM_BOOL colontmp_;
		NIM_BOOL _8;
		_3 = 0;
		_3 = (((NI32) 0) <= result);
		if (_3)
		{
			NI32 _5;
			NIM_BOOL _6;
			_5 = result;
			_6 = (c.blocks.p->data[_5].kind == ((NU8) 0));
			_3 = !(_6);
		}
		colontmp_ = _3;
		_8 = !(colontmp_);
		if (_8)
		{
			goto LA3_;
		}
		result = (NI32)(result - ((NI32) 1));
	}
	LA3_:;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, requestLabel__mirZmirgen95blocks_50)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Block_M18mirZmirgen95blocks* b) {
	NU32 result;
	NIM_BOOL _4;
	NU32* _6;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_4 = isNone__mirZmirgen95blocks_54((*b).id);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (_4)
	{
		NU32 _5;
		_I6Option_4680843275 _7;
		_5 = allocLabel__mirZmirconstr_741(bu);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_7 = some__mirZmirgen95blocks_59(_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*b).id = _7;
	}
	_6 = unsafeGet__mirZmirgen95blocks_64((&(*b).id));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (*_6);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, closeBlock__mirZmirgen95blocks_657)(_G8BlockCtx_M18mirZmirgen95blocks* c, _G10MirBuilder_M13mirZmirconstr* bu) {
	NIM_BOOL result;
	_G5Block_M18mirZmirgen95blocks blk;
	NIM_BOOL _4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	blk = pop__mirZmirgen95blocks_661((&(*c).blocks));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_4 = 0;
	_4 = (blk.kind == ((NU8) 0));
	if (_4)
	{
		NIM_BOOL _9;
		_9 = isSome__mirZmirgen95blocks_68(blk.id);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		_4 = _9;
	}
	if (_4)
	{
		NU32* _7;
		_7 = unsafeGet__mirZmirgen95blocks_64((&blk.id));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		join__mirZmirconstr_847(bu, (*_7));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		result = NIM_TRUE;
	}
	eqdestroy___mirZmirgen95blocks_124((&blk));
	goto LA3_;
	LA1_: {
		*nimErr_ = NIM_FALSE;
		eqdestroy___mirZmirgen95blocks_124((&blk));
		*nimErr_ = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_:;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___mirZmirgen95blocks_160)(_sG5Block_M18mirZmirgen95blocks* dest) {
	NI32 colontmp_;
	colontmp_ = ((NI32) 0);
	while (1) {
		NI32 _6;
		NIM_BOOL colontmp__2;
		NIM_BOOL _8;
		NI32 _9;
		NI32 _11;
		NIM_BOOL _13;
		NI32 _17;
		_si32* _16;
		_6 = (*dest).len;
		colontmp__2 = (colontmp_ < _6);
		_8 = !(colontmp__2);
		if (_8)
		{
			goto LA2_;
		}
		_9 = colontmp_;
		switch ((*dest).p->data[_9].kind) {
		case ((NU8) 0):
		goto LA3_;
		case ((NU8) 1):
		goto LA4_;
		case ((NU8) 3):
		goto LA5_;
		case ((NU8) 4):
		goto LA6_;
		case ((NU8) 2):
		case ((NU8) 5):
		goto LA7_;
		}
		LA3_:;
		_11 = colontmp_;
		_13 = nimDecRefIsLastCyclicDyn((*dest).p->data[_11]._kind_1.label);
		if (_13)
		{
			NI32 _14;
			_14 = colontmp_;
			nimDestroyAndDispose((*dest).p->data[_14]._kind_1.label);
		}
		goto LA9_;
		LA4_:;
		goto LA9_;
		LA5_:;
		_17 = colontmp_;
		_16 = (&(*dest).p->data[_17]._kind_3.exits);
		eqdestroy___experimentalZcolortext_1745(_16);
		goto LA9_;
		LA6_:;
		goto LA9_;
		LA7_:;
		goto LA9_;
		LA9_:;
		colontmp_ = (NI32)(colontmp_ + ((NI32) 1));
	}
	LA2_:;
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(_G5Block_M18mirZmirgen95blocks));
}
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___mirZmirgen95blocks_446)(_sT2G5Value_M13mirZmirconstrI6Option_4680843275* dest) {
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(_T2G5Value_M13mirZmirconstrI6Option_4680843275));
}
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, add__mirZmirgen95blocks_702)(_sT2G5Value_M13mirZmirconstrI6Option_4680843275* x, _T2G5Value_M13mirZmirconstrI6Option_4680843275* value) {
	NI32 oldLen;
	_sT2G5Value_M13mirZmirconstrI6Option_4680843275* _6;
	_I8NimSeqV2_4680843623* _7;
	_I8NimSeqV2_4680843623* xu;
	NIM_BOOL _8;
	_I8NimSeqV2_4680843623* _9;
	NIM_BOOL _11;
	_I8NimSeqV2_4680843623* _21;
	_I8NimSeqV2_4680843623* _22;
	_I13NimSeqPayload_4680843626* _23;
	oldLen = (*x).len;
	_6 = x;
	_7 = ((_I8NimSeqV2_4680843623*) (_6));
	xu = _7;
	_8 = 0;
	_9 = xu;
	_8 = ((*_9).p == ((_I13NimSeqPayload_4680843626*) NIM_NIL));
	_11 = !(_8);
	if (_11)
	{
		_I8NimSeqV2_4680843623* _12;
		_I13NimSeqPayload_4680843626* _13;
		NI32 _14;
		NI32 _15;
		_12 = xu;
		_13 = (*_12).p;
		_14 = (*_13).cap;
		_15 = (NI32)(oldLen + ((NI32) 1));
		_8 = (_14 < _15);
	}
	if (_8)
	{
		_I8NimSeqV2_4680843623* _16;
		_I8NimSeqV2_4680843623* _17;
		void* _18;
		void* _19;
		_I13NimSeqPayload_4680843626* _20;
		_16 = xu;
		_17 = xu;
		_18 = ((void*) ((*_17).p));
		_19 = prepareSeqAdd(oldLen, _18, ((NI32) 1), ((NI32) 28), ((NI32) 4));
		_20 = ((_I13NimSeqPayload_4680843626*) (_19));
		(*_16).p = _20;
	}
	_21 = xu;
	(*_21).len = (NI32)(oldLen + ((NI32) 1));
	_22 = xu;
	_23 = (*_22).p;
	(*_23).data[oldLen] = (*value);
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, tailExit__mirZmirgen95blocks_553)(_G8BlockCtx_M18mirZmirgen95blocks* c, _G10MirBuilder_M13mirZmirconstr* bu) {
	NI32 last;
	NIM_BOOL _6;
	NI32 a;
	NI32 b;
	NI32 step;
	NI32 res;
	_G7MirNode_M12mirZmirtrees _41;
	_G7Context_M13mirZmirconstr savedX60gensym44_;
	_G5Block_M18mirZmirgen95blocks* _42;
	NU32 _43;
	_G7MirNode_M12mirZmirtrees _44;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	last = ((*c).toDestroy.len-1);
	_6 = (((NI32) 0) <= last);
	if (_6)
	{
		_G7MirNode_M12mirZmirtrees _8;
		_G7Context_M13mirZmirconstr savedX60gensym38_;
		_G7MirNode_M12mirZmirtrees _10;
		_G7Context_M13mirZmirconstr savedX60gensym41_;
		_G7MirNode_M12mirZmirtrees _11;
		_G7MirNode_M12mirZmirtrees _12;
		nimZeroMem((void*)(&_8), sizeof(_G7MirNode_M12mirZmirtrees));
		_8.kind = ((NU8) 68);
		savedX60gensym38_ = start__mirZmirconstr_692(bu, _8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&_10), sizeof(_G7MirNode_M12mirZmirtrees));
		_10.kind = ((NU8) 43);
		_10.typ = ((NU32) 0);
		savedX60gensym41_ = start__mirZmirconstr_692(bu, _10);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&_11), sizeof(_G7MirNode_M12mirZmirtrees));
		_11.kind = ((NU8) 18);
		_11._kind_10.imm = ((NU32) 0);
		add__mirZmirconstr_617(bu, _11);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&_12), sizeof(_G7MirNode_M12mirZmirtrees));
		_12.kind = ((NU8) 19);
		_12._kind_11.magic = ((NU16) 269);
		add__mirZmirconstr_617(bu, _12);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		finish__mirZmirconstr_708(bu, savedX60gensym41_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		finish__mirZmirconstr_708(bu, savedX60gensym38_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	a = ((*c).blocks.len-1);
	b = ((NI32) 0);
	step = ((NI32) 1);
	res = a;
	while (1) {
		NIM_BOOL colontmp_;
		NIM_BOOL _21;
		NI32 i;
		_G5Block_M18mirZmirgen95blocks b_2;
		NI32 start;
		NI32 a_2;
		NI32 b_3;
		NI32 step_2;
		NI32 res_2;
		NI32 _39;
		colontmp_ = (b <= res);
		_21 = !(colontmp_);
		if (_21)
		{
			goto LA3_;
		}
		i = res;
		b_2 = (*c).blocks.p->data[i];
		switch (b_2.kind) {
		case ((NU8) 1):
		goto LA4_;
		case ((NU8) 0):
		goto LA5_;
		case ((NU8) 2):
		goto LA6_;
		case ((NU8) 3):
		case ((NU8) 5):
		case ((NU8) 4):
		goto LA7_;
		}
		LA4_:;
		start = (NI32)(last - b_2._kind_2.numRegistered);
		a_2 = last;
		b_3 = (NI32)(start + ((NI32) 1));
		step_2 = ((NI32) 1);
		res_2 = a_2;
		while (1) {
			NIM_BOOL colontmp__2;
			NIM_BOOL _35;
			NI32 j;
			NI32 _38;
			colontmp__2 = (b_3 <= res_2);
			_35 = !(colontmp__2);
			if (_35)
			{
				goto LA10_;
			}
			j = res_2;
			emitDestroy__mirZmirgen95blocks_103(bu, (*c).toDestroy.p->data[j].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_38 = ((NI32) (step_2));
			res_2 = (NI32)(res_2 - _38);
		}
		LA10_:;
		last = start;
		goto LA11_;
		LA5_:;
		goto LA11_;
		LA6_:;
		goto LA11_;
		LA7_:;
		unreachableImpl__utilsZidioms_15(TM__UsXpUPjMR8JNUzqmpi6SXA_6, TM__UsXpUPjMR8JNUzqmpi6SXA_7);
		goto BeforeRet_;
		LA11_:;
		_39 = ((NI32) (step));
		res = (NI32)(res - _39);
	}
	LA3_:;
	nimZeroMem((void*)(&_41), sizeof(_G7MirNode_M12mirZmirtrees));
	_41.kind = ((NU8) 71);
	savedX60gensym44_ = start__mirZmirconstr_692(bu, _41);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_42 = (&(*c).blocks.p->data[((NI32) 0)]);
	_43 = requestLabel__mirZmirgen95blocks_50(bu, _42);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_44 = labelNode__mirZmirgen95blocks_100(_43);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	add__mirZmirconstr_617(bu, _44);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	finish__mirZmirconstr_708(bu, savedX60gensym44_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return ;
}
static N_INLINE(NIM_BOOL, isSome__mirZmirgen95blocks_320)(_I6Option_4680843283 self) {
	NIM_BOOL result;
	result = self.has;
	goto LA0_;
	LA0_:;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, incl__mirZmirgen95blocks_325)(_si32* s, NI32 val) {
	NI32 result;
	_si32 a;
	NI32 i;
	NI32 L;
	NI32 _16;
	a = (*s);
	i = ((NI32) 0);
	L = a.len;
	while (1) {
		NIM_BOOL colontmp_;
		NIM_BOOL _10;
		NI32 i_2;
		NI32 _13;
		NI32 it;
		NIM_BOOL _14;
		colontmp_ = (i < L);
		_10 = !(colontmp_);
		if (_10)
		{
			goto LA2_;
		}
		i_2 = i;
		_13 = i;
		it = a.p->data[_13];
		_14 = (it == val);
		if (_14)
		{
			result = i_2;
			goto LA4_;
		}
		i = (NI32)(i + ((NI32) 1));
	}
	LA2_:;
	result = (*s).len;
	_16 = val;
	add__experimentalZdiff_238(s, _16);
	LA4_:;
	return result;
}
static N_INLINE(_G5Value_M13mirZmirconstr*, unsafeGet__mirZmirgen95blocks_347)(_I6Option_4680843283* self) {
	_G5Value_M13mirZmirconstr* result;
	result = (&(*self).val);
	return result;
}
static N_INLINE(NU32, getOrIncl__mirZmirgen95blocks_408)(_G6MirEnv_M10mirZmirenv* env, NI32 v) {
	NU32 result;
	NI64 _3;
	NU32 _4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_3 = ((NI64) (v));
	_4 = getOrIncl__icZic_1904((&(*env).numbers), _3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = _4;
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shrink__mirZmirgen95blocks_470)(_sT2G5Value_M13mirZmirconstrI6Option_4680843275* x, NI32 newLen) {
	_sT2G5Value_M13mirZmirconstrI6Option_4680843275* _3;
	_I8NimSeqV2_4680843623* _4;
	_3 = x;
	_4 = ((_I8NimSeqV2_4680843623*) (_3));
	(*_4).len = ((NI32) (newLen));
	return ;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI32 size) {
	size_t _4;
	void* _5;
	_4 = ((size_t) (size));
	_5 = memset(a, v, _4);
	return ;
}
static N_INLINE(void, nimZeroMem)(void* p, NI32 size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	return ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_4132);
	return result;
}
static N_INLINE(_G5Block_M18mirZmirgen95blocks, pop__mirZmirgen95blocks_661)(_sG5Block_M18mirZmirgen95blocks* s) {
	_G5Block_M18mirZmirgen95blocks result;
	NI32 _4;
	NI32 L;
	NI32 _6;
	_G5Block_M18mirZmirgen95blocks* _5;
	_G5Block_M18mirZmirgen95blocks _7;
	NI32 _8;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	_4 = (*s).len;
	L = (NI32)(_4 - ((NI32) 1));
	_6 = L;
	_5 = (&(*s).p->data[_6]);
	_7 = (*_5);
	nimZeroMem((void*)(&(*_5)), sizeof(_G5Block_M18mirZmirgen95blocks));
	result = _7;
	_8 = ((NI32) (L));
	shrink__mirZmirgen95blocks_184(s, _8);
	if (NIM_UNLIKELY(*nimErr_)) goto LA0_;
	goto LA1_;
	LA0_: {
		*nimErr_ = NIM_FALSE;
		eqdestroy___mirZmirgen95blocks_124((&result));
		*nimErr_ = NIM_TRUE;
		goto BeforeRet_;
	}
	LA1_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU32*, unsafeGet__mirZmirgen95blocks_64)(_I6Option_4680843275* self) {
	NU32* result;
	result = (&(*self).val);
	return result;
}
static N_INLINE(NIM_BOOL, isSome__mirZmirgen95blocks_68)(_I6Option_4680843275 self) {
	NIM_BOOL result;
	result = self.has;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(void, add__mirZmirconstr_617)(_G10MirBuilder_M13mirZmirconstr* bu, _G7MirNode_M12mirZmirtrees n) {
	NI32* _3;
	_G7MirNode_M12mirZmirtrees _4;
	_3 = (&(*bu).front.num);
	(*_3) = (NI32)((*_3) + ((NI32) 1));
	_4 = n;
	add__mirZmirconstr_624((&(*bu).front.nodes), _4);
	return ;
}
static N_INLINE(NI32, len__mirZmirconstr_216)(_L9MirBuffer_12_M13mirZmirconstr b) {
	NI32 result;
	result = b.nodes.len;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(_G7Context_M13mirZmirconstr, start__mirZmirconstr_692)(_G10MirBuilder_M13mirZmirconstr* bu, _G7MirNode_M12mirZmirtrees n) {
	_G7Context_M13mirZmirconstr result;
	_G7MirNode_M12mirZmirtrees _3;
	NI32 _4;
	NI32 _6;
	NI32 _7;
	NU32 _8;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(_G7Context_M13mirZmirconstr));
	_3 = n;
	add__mirZmirconstr_617(bu, _3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_4 = (*bu).front.num;
	_6 = len__mirZmirconstr_216((*bu).front);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_7 = (NI32)(_6 - ((NI32) 1));
	_8 = ((NU32) (_7));
	nimZeroMem((void*)(&result), sizeof(_G7Context_M13mirZmirconstr));
	result.num = _4;
	result.pos = _8;
	(*bu).front.num = ((NI32) 0);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, finish__mirZmirconstr_708)(_G10MirBuilder_M13mirZmirconstr* bu, _G7Context_M13mirZmirconstr saved) {
	NU32 _4;
	NU32* _3;
	_4 = saved.pos;
	_3 = (&(*bu).front.nodes.p->data[_4]._kind_13.len);
	(*_3) = ((NU32) ((*bu).front.num));
	(*bu).front.num = saved.num;
	return ;
}
static N_INLINE(NI32, minuspercent___system_707)(NI32 x, NI32 y) {
	NI32 result;
	NU32 _3;
	NU32 _4;
	NU32 _5;
	NI32 _6;
	_3 = ((NU32) (x));
	_4 = ((NU32) (y));
	_5 = (NU32)((NU32)(_3) - (NU32)(_4));
	_6 = ((NI32) (_5));
	result = _6;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {
	NIM_BOOL result;
	NIM_BOOL _2;
	NIM_BOOL _3;
	result = 0;
	_2 = (p == NIM_NIL);
	_3 = !(_2);
	if (_3)
	{
		NI32 _5;
		NI32 _6;
		_L9RefHeader_2502_M6system* _7;
		_L9RefHeader_2502_M6system* cell;
		_L9RefHeader_2502_M6system* _8;
		NI32 _9;
		NI32 _10;
		NIM_BOOL _11;
		_L9RefHeader_2502_M6system* _12;
		NI32* _13;
		TNimTypeV2** _16;
		_5 = ((NI32) (ptrdiff_t) (p));
		_6 = minuspercent___system_707(_5, ((NI32) 8));
		_7 = ((_L9RefHeader_2502_M6system*) (_6));
		cell = _7;
		_8 = cell;
		_9 = (*_8).rc;
		_10 = (NI32)(_9 & ((NI32) -16));
		_11 = (_10 == ((NI32) 0));
		if (_11)
		{
			result = NIM_TRUE;
			goto LA2_;
		}
		_12 = cell;
		_13 = (&(*_12).rc);
		(*_13) = (NI32)((*_13) - ((NI32) 16));
		LA2_:;
		_16 = ((TNimTypeV2**) (p));
		rememberCycle__system_3135(result, cell, (*_16));
	}
	return result;
}
static N_INLINE(NIM_BOOL, isSome__mirZmirconstr_763)(NU32 i) {
	NIM_BOOL result;
	NI32 _2;
	NIM_BOOL _3;
	_2 = i;
	_3 = (_2 == ((NI32) 0));
	result = !(_3);
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NU32, X5BX5D___mirZmirconstr_771)(NU32 i) {
	NU32 result;
	NU32 _2;
	_2 = (NU32)((NU32)(i) - (NU32)(((NU32) 1)));
	result = ((NU32) (_2));
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(void, use__mirZmirconstr_760)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Value_M13mirZmirconstr val) {
	NIM_BOOL _4;
	_G7MirNode_M12mirZmirtrees _8;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	_4 = isSome__mirZmirconstr_763(val.info);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (_4)
	{
		NU32 _6;
		_G7MirNode_M12mirZmirtrees _7;
		_6 = X5BX5D___mirZmirconstr_771(val.info);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_7 = val.node;
		add__mirZmirconstr_644(bu, _6, _7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA1_;
	}
	_8 = val.node;
	add__mirZmirconstr_617(bu, _8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	LA1_:;
	}BeforeRet_: ;
	return ;
}
static N_INLINE(NU32, getOrIncl__mirZinjecthooks_481)(_G6MirEnv_M10mirZmirenv* env, NI64 v) {
	NU32 result;
	NI64 _3;
	NU32 _4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_3 = ((NI64) (v));
	_4 = getOrIncl__icZic_1904((&(*env).numbers), _3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = _4;
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU32, addLocal__mirZmirconstr_565)(_G10MirBuilder_M13mirZmirconstr* bu, _G5Local_M13mirZmirbodies data) {
	NU32 result;
	_G5Local_M13mirZmirbodies _3;
	NU32 _4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_3 = data;
	_4 = add__mirZmirconstr_569((&(*bu).locals), _3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA0_;
	result = _4;
	goto LA1_;
	LA0_: {
		*nimErr_ = NIM_FALSE;
		*nimErr_ = NIM_TRUE;
		goto BeforeRet_;
	}
	LA1_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(_G7MirNode_M12mirZmirtrees, procNode__mirZmirconstr_74)(NU32 id) {
	_G7MirNode_M12mirZmirtrees result;
	NU32 _2;
	_2 = id;
	nimZeroMem((void*)(&result), sizeof(_G7MirNode_M12mirZmirtrees));
	result.kind = ((NU8) 1);
	result._kind_1.prc = _2;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(void, zeroMem__system_1704)(void* p, NI32 size) {
	nimZeroMem(p, size);
	return ;
}
