/* Generated by Nim Compiler v0.1.0-dev.21456 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct _G9LocHandle_M8vmZvmdef _G9LocHandle_M8vmZvmdef;
typedef struct _G6VmType_M8vmZvmdef _G6VmType_M8vmZvmdef;
typedef struct _G6VmCell_M8vmZvmdef _G6VmCell_M8vmZvmdef;
typedef struct _G11VmAllocator_M8vmZvmdef _G11VmAllocator_M8vmZvmdef;
typedef struct _sG6VmCell_M8vmZvmdef _sG6VmCell_M8vmZvmdef;
typedef struct _T2i32aG6VmCell_M8vmZvmdef _T2i32aG6VmCell_M8vmZvmdef;
typedef struct _ou8 _ou8;
typedef struct NimStringV2 NimStringV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct _T3Si32i32 _T3Si32i32;
typedef struct _sT2i32rG6VmType_M8vmZvmdef _sT2i32rG6VmType_M8vmZvmdef;
typedef struct _T2i32aT2i32rG6VmType_M8vmZvmdef _T2i32aT2i32rG6VmType_M8vmZvmdef;
typedef struct _sG15BranchListEntry_M8vmZvmdef _sG15BranchListEntry_M8vmZvmdef;
typedef struct _T2i32aG15BranchListEntry_M8vmZvmdef _T2i32aG15BranchListEntry_M8vmZvmdef;
typedef struct _T2i32rG6VmType_M8vmZvmdef _T2i32rG6VmType_M8vmZvmdef;
typedef struct _G19VariantFieldIterCtx_M12vmZvmobjects _G19VariantFieldIterCtx_M12vmZvmobjects;
typedef struct _T2bu32 _T2bu32;
struct _G9LocHandle_M8vmZvmdef {
NI32 cell;
NU8* p;
_G6VmType_M8vmZvmdef* typ;
};
struct _G6VmCell_M8vmZvmdef {
NI32 count;
NI32 sizeInBytes;
NU8* p;
_G6VmType_M8vmZvmdef* typ;
};
struct _sG6VmCell_M8vmZvmdef {
NI32 len;
_T2i32aG6VmCell_M8vmZvmdef* p;
};
struct _G11VmAllocator_M8vmZvmdef {
_sG6VmCell_M8vmZvmdef cells;
NI32 freeHead;
NI32 freeTail;
_G6VmType_M8vmZvmdef* byteType;
};
struct _T2i32aG6VmCell_M8vmZvmdef {
NI32 cap;
_G6VmCell_M8vmZvmdef data[SEQ_DECL_SIZE];
};
struct _ou8 {
NU8* Field0;
NI32 Field1;
};
struct NimStringV2 {
NI32 len;
NimStrPayload* p;
};
struct _T3Si32i32 {
NimStringV2 Field0;
NI32 Field1;
NI32 Field2;
};
struct NimStrPayload {
NI32 cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct _sT2i32rG6VmType_M8vmZvmdef {
NI32 len;
_T2i32aT2i32rG6VmType_M8vmZvmdef* p;
};
struct _sG15BranchListEntry_M8vmZvmdef {
NI32 len;
_T2i32aG15BranchListEntry_M8vmZvmdef* p;
};
struct _G6VmType_M8vmZvmdef {
NU8 kind;
union {
struct {
} _kind_1;
struct {
_G6VmType_M8vmZvmdef* targetType;
} _kind_2;
struct {
NI32 setLength;
} _kind_3;
struct {
NI32 seqElemStride;
_G6VmType_M8vmZvmdef* seqElemType;
} _kind_4;
struct {
NI32 routineSig;
} _kind_5;
struct {
NI32 numBits;
} _kind_6;
struct {
NU32 relFieldStart;
_sT2i32rG6VmType_M8vmZvmdef objFields;
_sG15BranchListEntry_M8vmZvmdef branches;
} _kind_7;
struct {
NI32 elementCount;
NI32 elementStride;
_G6VmType_M8vmZvmdef* elementType;
} _kind_8;
};
NU32 sizeInBytes;
NU8 alignment;
};
struct _T2i32rG6VmType_M8vmZvmdef {
NI32 Field0;
_G6VmType_M8vmZvmdef* Field1;
};
struct _T2i32aT2i32rG6VmType_M8vmZvmdef {
NI32 cap;
_T2i32rG6VmType_M8vmZvmdef data[SEQ_DECL_SIZE];
};
struct _G19VariantFieldIterCtx_M12vmZvmobjects {
NI32 i;
NI32 L;
NU32 last;
NU32 nextDiscField;
NU32 bI;
};
struct _T2bu32 {
NIM_BOOL Field0;
NU32 Field1;
};
N_LIB_PRIVATE N_NIMCALL(NU8, checkValid__vmZvmchecks_126)(NU8* p, _G6VmType_M8vmZvmdef* typ, _G6VmCell_M8vmZvmdef cell);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NU8, testLocationType__vmZvmchecks_25)(_G6VmType_M8vmZvmdef* locType, _G6VmType_M8vmZvmdef* t);
static N_INLINE(NU32, alignedSize__vmZvmtypes_23)(_G6VmType_M8vmZvmdef* t);
N_LIB_PRIVATE N_NIMCALL(NU8, searchInArray__vmZvmchecks_28)(NU8* h, NI hLen_0, _G6VmType_M8vmZvmdef* etyp, _G6VmType_M8vmZvmdef* t, NI32 len, NI32 stride, NI32 o);
N_LIB_PRIVATE N_NOINLINE(void, unreachableImpl__utilsZidioms_15)(NimStringV2 str, _T3Si32i32 loc);
N_LIB_PRIVATE N_NIMCALL(NU8, getTypeRel__vmZvmtypes_179)(_G6VmType_M8vmZvmdef* a, _G6VmType_M8vmZvmdef* b);
static N_INLINE(NI32, slashpercent___system_747)(NI32 x, NI32 y);
N_LIB_PRIVATE N_NIMCALL(NU8, searchInObject__vmZvmchecks_20)(NU8* h, NI hLen_0, _G6VmType_M8vmZvmdef* otyp, _G6VmType_M8vmZvmdef* t, NI32 o);
static N_INLINE(void, nimZeroMem)(void* p, NI32 size);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___vmZvmdef_889)(_T2i32rG6VmType_M8vmZvmdef* dest, _T2i32rG6VmType_M8vmZvmdef src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vmZvmdef_886)(_T2i32rG6VmType_M8vmZvmdef* dest);
N_LIB_PRIVATE N_NIMCALL(void, setup__vmZvmobjects_422)(_G19VariantFieldIterCtx_M12vmZvmobjects* ctx, _G6VmType_M8vmZvmdef* typ, NU32 branch);
N_LIB_PRIVATE N_NIMCALL(_T2bu32, get__vmZvmobjects_438)(_G19VariantFieldIterCtx_M12vmZvmobjects ctx);
N_LIB_PRIVATE N_NIMCALL(void, next__vmZvmobjects_455)(_G19VariantFieldIterCtx_M12vmZvmobjects* ctx, NU8* src, NI srcLen_0, _G6VmType_M8vmZvmdef* typ);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI32 size);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__NRD09bQfzs6lKgwkQvHxUKA_1 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__NRD09bQfzs6lKgwkQvHxUKA_2 = {0, (NimStrPayload*)&TM__NRD09bQfzs6lKgwkQvHxUKA_1};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__NRD09bQfzs6lKgwkQvHxUKA_4 = { 12 | NIM_STRLIT_FLAG, "vmchecks.nim" };
static NIM_CONST _T3Si32i32 TM__NRD09bQfzs6lKgwkQvHxUKA_3 = {{12, (NimStrPayload*)&TM__NRD09bQfzs6lKgwkQvHxUKA_4},
((NI32) 119),
((NI32) 17)}
;
extern NIM_BOOL nimInErrorMode__system_4132;
N_LIB_PRIVATE N_NIMCALL(NU8, checkValid__vmZvmchecks_152)(_G11VmAllocator_M8vmZvmdef al, _G9LocHandle_M8vmZvmdef h) {
	NU8 result;
	NIM_BOOL _3;
	NIM_BOOL _4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_3 = (h.cell == ((NI32) -1));
	_4 = !(_3);
	if (_4)
	{
		NI32 _5;
		_5 = h.cell;
		result = checkValid__vmZvmchecks_126(h.p, h.typ, al.cells.p->data[_5]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA1_;
	}
	result = ((NU8) 1);
	LA1_:;
	goto LA2_;
	LA2_:;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, checkValid__vmZvmchecks_126)(NU8* p, _G6VmType_M8vmZvmdef* typ, _G6VmCell_M8vmZvmdef cell) {
	NU8 result;
	NIM_BOOL _4;
	NIM_BOOL _5;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_4 = (p == cell.p);
	if (_4)
	{
		result = testLocationType__vmZvmchecks_25(cell.typ, typ);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA1_;
	}
	_5 = (cell.p < p);
	if (_5)
	{
		NI32 _7;
		NI32 _8;
		NI32 off;
		NIM_BOOL _9;
		NIM_BOOL _10;
		NIM_BOOL _11;
		_7 = ((NI32) (ptrdiff_t) (p));
		_8 = ((NI32) (ptrdiff_t) (cell.p));
		off = (NI32)(_7 - _8);
		_9 = (cell.sizeInBytes <= off);
		if (_9)
		{
			result = ((NU8) 1);
			goto LA4_;
		}
		_10 = (typ == ((_G6VmType_M8vmZvmdef*) NIM_NIL));
		_11 = !(_10);
		if (_11)
		{
			NU32 _13;
			NI32 stride;
			NI32 _14;
			_ou8 _15;
			_13 = alignedSize__vmZvmtypes_23(cell.typ);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			stride = ((NI32) (_13));
			_14 = (NI32)(cell.sizeInBytes - ((NI32) 1));
			_15.Field0 = (NU8*)(cell.p)+(((NI32) 0)); _15.Field1 = (_14)-(((NI32) 0))+1;
			result = searchInArray__vmZvmchecks_28(_15.Field0, _15.Field1, cell.typ, typ, cell.count, stride, off);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA4_;
		}
		unreachableImpl__utilsZidioms_15(TM__NRD09bQfzs6lKgwkQvHxUKA_2, TM__NRD09bQfzs6lKgwkQvHxUKA_3);
		goto BeforeRet_;
		LA4_:;
		goto LA1_;
	}
	result = ((NU8) 1);
	LA1_:;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, testLocationType__vmZvmchecks_25)(_G6VmType_M8vmZvmdef* locType, _G6VmType_M8vmZvmdef* t) {
	NU8 result;
	NIM_BOOL _3;
	_G6VmType_M8vmZvmdef* it;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = ((NU8) 0);
	_3 = (locType == t);
	if (_3)
	{
		goto LA1_;
	}
	it = locType;
	while (1) {
		NIM_BOOL _7;
		NIM_BOOL colontmp_;
		NIM_BOOL _9;
		_G6VmType_M8vmZvmdef* _10;
		_G6VmType_M8vmZvmdef* _12;
		NI32 _14;
		NIM_BOOL _15;
		_G6VmType_M8vmZvmdef* _17;
		NIM_BOOL _19;
		NU8 _22;
		NIM_BOOL _23;
		NIM_BOOL _24;
		_7 = (it == t);
		colontmp_ = !(_7);
		_9 = !(colontmp_);
		if (_9)
		{
			goto LA4_;
		}
		_10 = it;
		switch ((*_10).kind) {
		case ((NU8) 10):
		goto LA5_;
		case ((NU8) 11):
		goto LA6_;
		case ((NU8) 6):
		case ((NU8) 2):
		goto LA7_;
		default:
		goto LA8_;
		}
		LA5_:;
		_12 = it;
		_14 = (*_12)._kind_7.objFields.len;
		_15 = (((NI32) 0) < _14);
		if (_15)
		{
			_G6VmType_M8vmZvmdef* _16;
			_16 = it;
			it = (*_16)._kind_7.objFields.p->data[((NI32) 0)].Field1;
			goto LA10_;
		}
		result = ((NU8) 2);
		goto LA1_;
		LA10_:;
		goto LA11_;
		LA6_:;
		_17 = it;
		_19 = (((NI32) 0) < (*_17)._kind_8.elementCount);
		if (_19)
		{
			_G6VmType_M8vmZvmdef* _20;
			_20 = it;
			it = (*_20)._kind_8.elementType;
			goto LA13_;
		}
		result = ((NU8) 2);
		goto LA1_;
		LA13_:;
		goto LA11_;
		LA7_:;
		_22 = getTypeRel__vmZvmtypes_179(t, it);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_23 = (_22 == ((NU8) 0));
		_24 = !(_23);
		if (_24)
		{
			goto LA4_;
		}
		result = ((NU8) 2);
		goto LA1_;
		LA8_:;
		result = ((NU8) 2);
		goto LA1_;
		LA11_:;
	}
	LA4_:;
	LA1_:;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, searchInArray__vmZvmchecks_28)(NU8* h, NI hLen_0, _G6VmType_M8vmZvmdef* etyp, _G6VmType_M8vmZvmdef* t, NI32 len, NI32 stride, NI32 o) {
	NU8 result;
	NI32 i;
	NI32 _8;
	NIM_BOOL _9;
	NI32 _11;
	NI32 _12;
	_ou8 _13;
	NI32 _14;
	NI32 _15;
	NI32 _16;
	NI32 _17;
	_ou8 _18;
	NI32 _20;
	NI32 _21;
	NI32 _22;
	NI32 _23;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	i = slashpercent___system_747(o, stride);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_8 = (NI32)(i * stride);
	_9 = (o == _8);
	if (_9)
	{
		result = testLocationType__vmZvmchecks_25(etyp, t);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA1_;
	}
	switch ((*etyp).kind) {
	case ((NU8) 0) ... ((NU8) 9):
	goto LA2_;
	case ((NU8) 10):
	goto LA3_;
	case ((NU8) 11):
	goto LA4_;
	}
	LA2_:;
	result = ((NU8) 3);
	goto LA5_;
	LA3_:;
	_11 = (NI32)(i * stride);
	_12 = (hLen_0-1);
	_13.Field0 = (NU8*)(h)+(_11); _13.Field1 = (_12)-(_11)+1;
	_14 = (NI32)(i * stride);
	_15 = (NI32)(o - _14);
	result = searchInObject__vmZvmchecks_20(_13.Field0, _13.Field1, etyp, t, _15);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto LA5_;
	LA4_:;
	_16 = (NI32)(i * stride);
	_17 = (hLen_0-1);
	_18.Field0 = (NU8*)(h)+(_16); _18.Field1 = (_17)-(_16)+1;
	_20 = (*etyp)._kind_8.elementCount;
	_21 = (*etyp)._kind_8.elementStride;
	_22 = (NI32)(i * stride);
	_23 = (NI32)(o - _22);
	result = searchInArray__vmZvmchecks_28(_18.Field0, _18.Field1, (*etyp)._kind_8.elementType, t, _20, _21, _23);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto LA5_;
	LA5_:;
	LA1_:;
	goto LA6_;
	LA6_:;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, searchInObject__vmZvmchecks_20)(NU8* h, NI hLen_0, _G6VmType_M8vmZvmdef* otyp, _G6VmType_M8vmZvmdef* t, NI32 o) {
	NU8 result;
	_ou8 p;
	_G6VmType_M8vmZvmdef* t_2;
	_G6VmType_M8vmZvmdef* _7;
	NI32 _9;
	NIM_BOOL _10;
	_ou8 src;
	_G6VmType_M8vmZvmdef* typ;
	NU32 branch;
	_G19VariantFieldIterCtx_M12vmZvmobjects ctx;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	p.Field0 = h; p.Field1 = hLen_0;
	t_2 = otyp;
	_7 = t_2;
	_9 = (*_7)._kind_7.branches.len;
	_10 = (_9 == ((NI32) 0));
	if (_10)
	{
		NI32 a;
		_G6VmType_M8vmZvmdef* _13;
		NI32 b;
		NI32 i;
		a = ((NI32) 0);
		_13 = t_2;
		b = (*_13)._kind_7.objFields.len;
		i = a;
		while (1) {
			NIM_BOOL colontmp_;
			NIM_BOOL _19;
			NI32 i_2;
			NU32 i_3;
			_T2i32rG6VmType_M8vmZvmdef f;
			NIM_BOOL _24;
			_G6VmType_M8vmZvmdef* _27;
			NI32 _28;
			NI32 _29;
			NIM_BOOL _30;
			colontmp_ = (i < b);
			_19 = !(colontmp_);
			if (_19)
			{
				goto LA3_;
			}
			i_2 = i;
			i_3 = ((NU32) (i_2));
			nimZeroMem((void*)(&f), sizeof(_T2i32rG6VmType_M8vmZvmdef));
			eqcopy___vmZvmdef_889((&f), (*otyp)._kind_7.objFields.p->data[i_3]);
			_24 = (f.Field0 == o);
			if (_24)
			{
				NU8 _89;
				_89 = testLocationType__vmZvmchecks_25(f.Field1, t);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				result = _89;
				eqdestroy___vmZvmdef_886((&f));
				goto LA6_;
			}
			_27 = f.Field1;
			_28 = ((NI32) ((*_27).sizeInBytes));
			_29 = (NI32)(f.Field0 + _28);
			_30 = (o < _29);
			if (_30)
			{
				_G6VmType_M8vmZvmdef* _31;
				NI32 _34;
				_ou8 _35;
				NI32 _38;
				NU8 _90;
				NI32 _40;
				_ou8 _41;
				_G6VmType_M8vmZvmdef* _42;
				_G6VmType_M8vmZvmdef* _43;
				_G6VmType_M8vmZvmdef* _44;
				NI32 _45;
				_G6VmType_M8vmZvmdef* _46;
				NI32 _47;
				NI32 _49;
				NU8 _91;
				_31 = f.Field1;
				switch ((*_31).kind) {
				case ((NU8) 10):
				goto LA8_;
				case ((NU8) 11):
				goto LA9_;
				default:
				goto LA10_;
				}
				LA8_:;
				_34 = (hLen_0-1);
				_35.Field0 = (NU8*)(h)+(f.Field0); _35.Field1 = (_34)-(f.Field0)+1;
				_38 = (NI32)(o - f.Field0);
				_90 = searchInObject__vmZvmchecks_20(_35.Field0, _35.Field1, f.Field1, t, _38);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				result = _90;
				eqdestroy___vmZvmdef_886((&f));
				goto LA6_;
				LA9_:;
				_40 = (hLen_0-1);
				_41.Field0 = (NU8*)(h)+(f.Field0); _41.Field1 = (_40)-(f.Field0)+1;
				_42 = f.Field1;
				_43 = (*_42)._kind_8.elementType;
				_44 = f.Field1;
				_45 = (*_44)._kind_8.elementCount;
				_46 = f.Field1;
				_47 = (*_46)._kind_8.elementStride;
				_49 = (NI32)(o - f.Field0);
				_91 = searchInArray__vmZvmchecks_28(_41.Field0, _41.Field1, _43, t, _45, _47, _49);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				result = _91;
				eqdestroy___vmZvmdef_886((&f));
				goto LA6_;
				LA10_:;
				result = ((NU8) 3);
				eqdestroy___vmZvmdef_886((&f));
				goto LA6_;
			}
			eqdestroy___vmZvmdef_886((&f));
			goto LA11_;
			LA5_: {
				*nimErr_ = NIM_FALSE;
				eqdestroy___vmZvmdef_886((&f));
				*nimErr_ = NIM_TRUE;
				goto BeforeRet_;
			}
			LA11_:;
			i = (NI32)(i + ((NI32) 1));
		}
		LA3_:;
		goto LA12_;
	}
	src.Field0 = p.Field0; src.Field1 = p.Field1;
	typ = t_2;
	branch = ((NU32) 0);
	nimZeroMem((void*)(&ctx), sizeof(_G19VariantFieldIterCtx_M12vmZvmobjects));
	setup__vmZvmobjects_422((&ctx), typ, branch);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	while (1) {
		_T2bu32 r;
		r = get__vmZvmobjects_438(ctx);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (r.Field0)
		{
			NU32 i_4;
			NU32 i_5;
			_T2i32rG6VmType_M8vmZvmdef f_2;
			NIM_BOOL _62;
			_G6VmType_M8vmZvmdef* _65;
			NI32 _66;
			NI32 _67;
			NIM_BOOL _68;
			i_4 = r.Field1;
			i_5 = i_4;
			nimZeroMem((void*)(&f_2), sizeof(_T2i32rG6VmType_M8vmZvmdef));
			eqcopy___vmZvmdef_889((&f_2), (*otyp)._kind_7.objFields.p->data[i_5]);
			_62 = (f_2.Field0 == o);
			if (_62)
			{
				NU8 _92;
				_92 = testLocationType__vmZvmchecks_25(f_2.Field1, t);
				if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				result = _92;
				eqdestroy___vmZvmdef_886((&f_2));
				goto LA6_;
			}
			_65 = f_2.Field1;
			_66 = ((NI32) ((*_65).sizeInBytes));
			_67 = (NI32)(f_2.Field0 + _66);
			_68 = (o < _67);
			if (_68)
			{
				_G6VmType_M8vmZvmdef* _69;
				NI32 _72;
				_ou8 _73;
				NI32 _76;
				NU8 _93;
				NI32 _78;
				_ou8 _79;
				_G6VmType_M8vmZvmdef* _80;
				_G6VmType_M8vmZvmdef* _81;
				_G6VmType_M8vmZvmdef* _82;
				NI32 _83;
				_G6VmType_M8vmZvmdef* _84;
				NI32 _85;
				NI32 _87;
				NU8 _94;
				_69 = f_2.Field1;
				switch ((*_69).kind) {
				case ((NU8) 10):
				goto LA18_;
				case ((NU8) 11):
				goto LA19_;
				default:
				goto LA20_;
				}
				LA18_:;
				_72 = (hLen_0-1);
				_73.Field0 = (NU8*)(h)+(f_2.Field0); _73.Field1 = (_72)-(f_2.Field0)+1;
				_76 = (NI32)(o - f_2.Field0);
				_93 = searchInObject__vmZvmchecks_20(_73.Field0, _73.Field1, f_2.Field1, t, _76);
				if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				result = _93;
				eqdestroy___vmZvmdef_886((&f_2));
				goto LA6_;
				LA19_:;
				_78 = (hLen_0-1);
				_79.Field0 = (NU8*)(h)+(f_2.Field0); _79.Field1 = (_78)-(f_2.Field0)+1;
				_80 = f_2.Field1;
				_81 = (*_80)._kind_8.elementType;
				_82 = f_2.Field1;
				_83 = (*_82)._kind_8.elementCount;
				_84 = f_2.Field1;
				_85 = (*_84)._kind_8.elementStride;
				_87 = (NI32)(o - f_2.Field0);
				_94 = searchInArray__vmZvmchecks_28(_79.Field0, _79.Field1, _81, t, _83, _85, _87);
				if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				result = _94;
				eqdestroy___vmZvmdef_886((&f_2));
				goto LA6_;
				LA20_:;
				result = ((NU8) 3);
				eqdestroy___vmZvmdef_886((&f_2));
				goto LA6_;
			}
			eqdestroy___vmZvmdef_886((&f_2));
			goto LA21_;
			LA16_: {
				*nimErr_ = NIM_FALSE;
				eqdestroy___vmZvmdef_886((&f_2));
				*nimErr_ = NIM_TRUE;
				goto BeforeRet_;
			}
			LA21_:;
			next__vmZvmobjects_455((&ctx), src.Field0, src.Field1, typ);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA22_;
		}
		goto LA23_;
		LA22_:;
	}
	LA23_:;
	LA12_:;
	LA6_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_4132);
	return result;
}
static N_INLINE(NU32, alignedSize__vmZvmtypes_23)(_G6VmType_M8vmZvmdef* t) {
	NU32 result;
	NU32 s;
	NU32 a;
	NU32 _5;
	NU32 _6;
	NU32 _7;
	NU32 _8;
	s = (*t).sizeInBytes;
	a = (NU32)((NU32)(((NU32) 1)) << (NU32)((*t).alignment));
	_5 = (NU32)((NU32)(a) - (NU32)(((NU32) 1)));
	_6 = (NU32)((NU32)(s) + (NU32)(_5));
	_7 = (NU32)((NU32)(a) - (NU32)(((NU32) 1)));
	_8 = (NU32)((NU32) ~(_7));
	result = (NU32)(_6 & _8);
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NI32, slashpercent___system_747)(NI32 x, NI32 y) {
	NI32 result;
	NU32 _3;
	NU32 _4;
	NU32 _5;
	NI32 _6;
	_3 = ((NU32) (x));
	_4 = ((NU32) (y));
	_5 = (NU32)((NU32)(_3) / (NU32)(_4));
	_6 = ((NI32) (_5));
	result = _6;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI32 size) {
	size_t _4;
	void* _5;
	_4 = ((size_t) (size));
	_5 = memset(a, v, _4);
	return ;
}
static N_INLINE(void, nimZeroMem)(void* p, NI32 size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	return ;
}
