/* Generated by Nim Compiler v0.1.0-dev.21456 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <stdio.h>
#include <io.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct _L25PTerminalcolonObjectType__14_M13pureZterminal _L25PTerminalcolonObjectType__14_M13pureZterminal;
typedef struct _L9RefHeader_2502_M6system _L9RefHeader_2502_M6system;
struct _L9RefHeader_2502_M6system {
NI32 rc;
NI32 rootIdx;
};
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZterminal_17)(_L25PTerminalcolonObjectType__14_M13pureZterminal** dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZterminal_29)(_L25PTerminalcolonObjectType__14_M13pureZterminal* dest);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI32 alignment);
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle__systemZio_309)(FILE* f);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NI32, minuspercent___system_707)(NI32 x, NI32 y);
N_LIB_PRIVATE NI16 defaultForegroundColor__pureZterminal_523;
N_LIB_PRIVATE NI16 defaultBackgroundColor__pureZterminal_524;
N_LIB_PRIVATE _L25PTerminalcolonObjectType__14_M13pureZterminal* gTerm__pureZterminal_15;
extern NIM_BOOL nimInErrorMode__system_4132;
N_LIB_PRIVATE N_NIMCALL(void, stdlibatppure__terminalInit000)(void) {
	gTerm__pureZterminal_15 = NIM_NIL;
	defaultForegroundColor__pureZterminal_523 = ((NI16) -1);
	defaultBackgroundColor__pureZterminal_524 = ((NI16) -1);
	nimTestErrorFlag();
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, terminalThreadDeinit__pureZterminal_856)(void) {
	eqdestroy___pureZterminal_17((&gTerm__pureZterminal_15));
	return ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZterminal_17)(_L25PTerminalcolonObjectType__14_M13pureZterminal** dest) {
	NIM_BOOL _3;
	_3 = nimDecRefIsLast((*dest));
	if (_3)
	{
		_L25PTerminalcolonObjectType__14_M13pureZterminal* _4;
		_4 = (*dest);
		eqdestroy___pureZterminal_29(_4);
		nimRawDispose((*dest), ((NI32) 4));
	}
	return ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isatty__pureZterminal_680)(FILE* f) {
	NIM_BOOL result;
	int _2;
	int _3;
	NIM_BOOL _4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_2 = getFileHandle__systemZio_309(f);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_3 = _isatty(_2);
	_4 = (_3 == ((NI32) 0));
	result = !(_4);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZterminal_29)(_L25PTerminalcolonObjectType__14_M13pureZterminal* dest) {
	return ;
}
static N_INLINE(NI32, minuspercent___system_707)(NI32 x, NI32 y) {
	NI32 result;
	NU32 _3;
	NU32 _4;
	NU32 _5;
	NI32 _6;
	_3 = ((NU32) (x));
	_4 = ((NU32) (y));
	_5 = (NU32)((NU32)(_3) - (NU32)(_4));
	_6 = ((NI32) (_5));
	result = _6;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	NIM_BOOL _2;
	NIM_BOOL _3;
	result = 0;
	_2 = (p == NIM_NIL);
	_3 = !(_2);
	if (_3)
	{
		NI32 _5;
		NI32 _6;
		_L9RefHeader_2502_M6system* _7;
		_L9RefHeader_2502_M6system* cell;
		_L9RefHeader_2502_M6system* _8;
		NI32 _9;
		NI32 _10;
		NIM_BOOL _11;
		_L9RefHeader_2502_M6system* _12;
		NI32* _13;
		_5 = ((NI32) (ptrdiff_t) (p));
		_6 = minuspercent___system_707(_5, ((NI32) 8));
		_7 = ((_L9RefHeader_2502_M6system*) (_6));
		cell = _7;
		_8 = cell;
		_9 = (*_8).rc;
		_10 = (NI32)((NI32)(_9) >> (NU32)(((NI32) 4)));
		_11 = (_10 == ((NI32) 0));
		if (_11)
		{
			result = NIM_TRUE;
			goto LA2_;
		}
		_12 = cell;
		_13 = (&(*_12).rc);
		(*_13) = (NI32)((*_13) - ((NI32) 16));
		LA2_:;
	}
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_4132);
	return result;
}
