/* Generated by Nim Compiler v0.1.0-dev.21456 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct _oc _oc;
typedef struct NimStringV2 NimStringV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct _G6Double_M16systemZdragonbox _G6Double_M16systemZdragonbox;
typedef struct _G17FloatingDecimal64_M16systemZdragonbox _G17FloatingDecimal64_M16systemZdragonbox;
typedef struct _G8uint64x2_M16systemZdragonbox _G8uint64x2_M16systemZdragonbox;
typedef struct _L6MulCmp_163_M16systemZdragonbox _L6MulCmp_163_M16systemZdragonbox;
typedef struct _L6Single_6_M16systemZschubfach _L6Single_6_M16systemZschubfach;
typedef struct _L17FloatingDecimal32_130_M16systemZschubfach _L17FloatingDecimal32_130_M16systemZschubfach;
struct _oc {
NIM_CHAR* Field0;
NI32 Field1;
};
struct NimStringV2 {
NI32 len;
NimStrPayload* p;
};
struct NimStrPayload {
NI32 cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 _e256[32];
struct _G6Double_M16systemZdragonbox {
NU64 bits;
};
struct _G17FloatingDecimal64_M16systemZdragonbox {
NU64 significand;
NI32 exponent;
};
struct _G8uint64x2_M16systemZdragonbox {
NU64 hi;
NU64 lo;
};
typedef NIM_CHAR _A16c[16];
typedef _G8uint64x2_M16systemZdragonbox _A619G8uint64x2_M16systemZdragonbox[619];
typedef NIM_CHAR _A200c[200];
struct _L6MulCmp_163_M16systemZdragonbox {
NU64 mul;
NU64 cmp;
};
typedef _L6MulCmp_163_M16systemZdragonbox _A25L6MulCmp_163_M16systemZdragonbox[25];
typedef NI8 _A100i8[100];
struct _L6Single_6_M16systemZschubfach {
NU32 bits;
};
struct _L17FloatingDecimal32_130_M16systemZschubfach {
NU32 digits;
NI32 exponent;
};
typedef NU64 _A77u64[77];
static N_INLINE(NI32, toChars__systemZdragonbox_700)(NIM_CHAR* buffer, NI bufferLen_0, NF64 v, NIM_BOOL forceTrailingDotZero);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI32 newLen);
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__systemZformatfloat_65)(NIM_CHAR* buf, NCSTRING value);
N_LIB_PRIVATE N_NIMCALL(_G6Double_M16systemZdragonbox, constructDouble__systemZdragonbox_31)(NF64 value);
N_LIB_PRIVATE N_NIMCALL(NU64, physicalSignificand__systemZdragonbox_34)(_G6Double_M16systemZdragonbox this_0);
N_LIB_PRIVATE N_NIMCALL(NU64, physicalExponent__systemZdragonbox_37)(_G6Double_M16systemZdragonbox this_0);
N_LIB_PRIVATE N_NIMCALL(NI32, signBit__systemZdragonbox_56)(_G6Double_M16systemZdragonbox this_0);
static N_INLINE(_G17FloatingDecimal64_M16systemZdragonbox, toDecimal64__systemZdragonbox_357)(NU64 ieeeSignificand, NU64 ieeeExponent);
static N_INLINE(NI32, formatDigits__systemZdragonbox_570)(NIM_CHAR* buffer, NI bufferLen_0, NI32 pos, NU64 digits, NI32 decimalExponent, NIM_BOOL forceTrailingDotZero);
static N_INLINE(void, nimZeroMem)(void* p, NI32 size);
static N_INLINE(NIM_BOOL, multipleOfPow2__systemZdragonbox_148)(NU64 value, NI32 e2);
static N_INLINE(_G17FloatingDecimal64_M16systemZdragonbox, toDecimal64AsymmetricInterval__systemZdragonbox_213)(NI32 e2);
static N_INLINE(NI32, floorLog10Pow2__systemZdragonbox_79)(NI32 e);
static N_INLINE(NI32, floorLog2Pow10__systemZdragonbox_70)(NI32 e);
static N_INLINE(_G8uint64x2_M16systemZdragonbox, computePow10__systemZdragonbox_100)(NI32 k);
static N_INLINE(NU32, computeDelta__systemZdragonbox_272)(_G8uint64x2_M16systemZdragonbox pow10, NI32 betaMinus1);
static N_INLINE(NU64, mulShift__systemZdragonbox_312)(NU64 x, _G8uint64x2_M16systemZdragonbox y);
static N_INLINE(NIM_BOOL, isIntegralEndpoint__systemZdragonbox_347)(NU64 twoF, NI32 e2, NI32 minusK);
static N_INLINE(NIM_BOOL, mulParity__systemZdragonbox_329)(NU64 twoF, _G8uint64x2_M16systemZdragonbox pow10, NI32 betaMinus1);
static N_INLINE(NIM_BOOL, isIntegralMidpoint__systemZdragonbox_352)(NU64 twoF, NI32 e2, NI32 minusK);
static N_INLINE(NI32, decimalLength__systemZdragonbox_556)(NU64 v);
static N_INLINE(NI32, printDecimalDigitsBackwards__systemZdragonbox_438)(NIM_CHAR* buf, NI bufLen_0, NI32 pos, NU64 output64);
static N_INLINE(void, utoa2Digits__stdZprivateZdigitsutils_27)(NIM_CHAR* buf, NI bufLen_0, NI32 pos, NU32 digits);
static N_INLINE(NI32, floorLog10ThreeQuartersPow2__systemZdragonbox_88)(NI32 e);
static N_INLINE(NI32, floorDivPow2__systemZdragonbox_62)(NI32 x, NI32 n);
static N_INLINE(_G8uint64x2_M16systemZdragonbox, mul128__systemZdragonbox_296)(NU64 a, NU64 b);
static N_INLINE(NIM_BOOL, multipleOfPow5__systemZdragonbox_159)(NU64 value, NI32 e5);
static N_INLINE(NI32, utoa8DigitsSkipTrailingZeros__systemZdragonbox_421)(NIM_CHAR* buf, NI bufLen_0, NI32 pos, NU32 digits);
static N_INLINE(NI32, trailingZeros2Digits__stdZprivateZdigitsutils_43)(NU32 digits);
static N_INLINE(NU32, lo32__systemZdragonbox_286)(NU64 x);
static N_INLINE(NU32, hi32__systemZdragonbox_289)(NU64 x);
static N_INLINE(NI32, float32ToChars__systemZschubfach_365)(NIM_CHAR* buffer, NI bufferLen_0, NF32 v, NIM_BOOL forceTrailingDotZero);
N_LIB_PRIVATE N_NIMCALL(_L6Single_6_M16systemZschubfach, constructSingle__systemZschubfach_28)(NF32 value);
N_LIB_PRIVATE N_NIMCALL(NU32, physicalSignificand__systemZschubfach_31)(_L6Single_6_M16systemZschubfach this_0);
N_LIB_PRIVATE N_NIMCALL(NU32, physicalExponent__systemZschubfach_34)(_L6Single_6_M16systemZschubfach this_0);
N_LIB_PRIVATE N_NIMCALL(NI32, signBit__systemZschubfach_41)(_L6Single_6_M16systemZschubfach this_0);
static N_INLINE(_L17FloatingDecimal32_130_M16systemZschubfach, toDecimal32__systemZschubfach_133)(NU32 ieeeSignificand, NU32 ieeeExponent);
static N_INLINE(NI32, formatDigits__systemZschubfach_280)(NIM_CHAR* buffer, NI bufferLen_0, NI32 pos, NU32 digits, NI32 decimalExponent, NIM_BOOL forceTrailingDotZero);
static N_INLINE(NIM_BOOL, multipleOfPow2__systemZschubfach_116)(NU32 value, NI32 e2);
static N_INLINE(NI32, floorDivPow2__systemZschubfach_44)(NI32 x, NI32 n);
static N_INLINE(NI32, floorLog2Pow10__systemZschubfach_52)(NI32 e);
static N_INLINE(NU64, computePow10Single__systemZschubfach_76)(NI32 k);
static N_INLINE(NU32, roundToOdd__systemZschubfach_107)(NU64 g, NU32 cp);
static N_INLINE(NI32, decimalLength__systemZschubfach_271)(NU32 v);
static N_INLINE(NI32, printDecimalDigitsBackwards__systemZschubfach_200)(NIM_CHAR* buf, NI bufLen_0, NI32 pos, NU32 output);
static N_INLINE(NU32, lo32__systemZschubfach_97)(NU64 x);
static N_INLINE(NU32, hi32__systemZschubfach_100)(NU64 x);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI32 size);
static NIM_CONST _e256 TM__4A5tjg38HjlzLf9bEp3IRRA_1 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00,
0xfe, 0xff, 0xff, 0x07, 0xfe, 0xff, 0xff, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST _e256 TM__4A5tjg38HjlzLf9bEp3IRRA_2 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00,
0x10, 0x40, 0x00, 0x00, 0x10, 0x40, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
extern NIM_CONST _A619G8uint64x2_M16systemZdragonbox pow10__systemZdragonbox_105;
extern NIM_CONST _A200c digits100__stdZprivateZdigitsutils_2;
extern NIM_CONST _A25L6MulCmp_163_M16systemZdragonbox mod5__systemZdragonbox_166;
extern NIM_CONST _A100i8 trailingZeros100__stdZprivateZdigitsutils_1;
extern NIM_CONST _A77u64 g__systemZschubfach_63;
extern NIM_BOOL nimInErrorMode__system_4132;
N_LIB_PRIVATE N_NIMCALL(NI32, writeFloatToBufferRoundtrip__systemZformatfloat_18)(NIM_CHAR* buf, NF64 value) {
	NI32 result;
	_oc _3;
	NI32 _4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_3.Field0 = buf; _3.Field1 = 65;
	result = toChars__systemZdragonbox_700(_3.Field0, _3.Field1, value, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_4 = result;
	buf[(_4)- 0] = 0;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, addStringN__systemZformatfloat_5)(NimStringV2* result, NIM_CHAR* buf, NI bufLen_0, NI32 buflen) {
	NI32 oldLen;
	NI32 newLen;
	NI32 _7;
	NIM_CHAR* _8;
	void* _9;
	NIM_CHAR* _10;
	void* _11;
	size_t _12;
	void* T1_;
	oldLen = (*result).len;
	newLen = (NI32)(oldLen + buflen);
	_7 = ((NI32) (newLen));
	setLengthStrV2((&(*result)), _7);
	_8 = (&(*result).p->data[oldLen]);
	_9 = ((void*) (_8));
	_10 = (&buf[((NI32) 0)]);
	_11 = ((void*) (_10));
	_12 = ((size_t) (buflen));
	T1_ = memcpy(_9, _11, _12);
	(void)(T1_);
	return ;
}
N_LIB_PRIVATE N_NIMCALL(NI32, writeFloatToBufferSprintf__systemZformatfloat_73)(NIM_CHAR* buf, NF64 value) {
	NI32 result;
	NIM_CHAR* _4;
	NCSTRING _5;
	int _6;
	NI32 n;
	NIM_BOOL hasDot;
	NI32 a;
	NI32 b;
	NI32 res;
	NIM_BOOL _22;
	NI32 _30;
	NIM_BOOL _32;
	NI32 _34;
	NIM_BOOL _36;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	_4 = buf;
	_5 = ((NCSTRING) (_4));
	_6 = sprintf(_5, "%.16g", value);
	n = ((NI32) (_6));
	hasDot = NIM_FALSE;
	a = ((NI32) 0);
	b = (NI32)(n - ((NI32) 1));
	res = a;
	while (1) {
		NIM_BOOL colontmp_;
		NIM_BOOL _15;
		NI32 i;
		NIM_BOOL _18;
		NIM_BOOL _20;
		colontmp_ = (res <= b);
		_15 = !(colontmp_);
		if (_15)
		{
			goto LA2_;
		}
		i = res;
		_18 = ((NU8)(buf[(i)- 0]) == (NU8)(44));
		if (_18)
		{
			buf[(i)- 0] = 46;
			hasDot = NIM_TRUE;
			goto LA4_;
		}
		_20 = ((TM__4A5tjg38HjlzLf9bEp3IRRA_1[(NU)(((NU8)(buf[(i)- 0])))>>3] &(1U<<((NU)(((NU8)(buf[(i)- 0])))&7U)))!=0);
		if (_20)
		{
			hasDot = NIM_TRUE;
			goto LA4_;
		}
		LA4_:;
		res = (NI32)(res + ((NI32) 1));
	}
	LA2_:;
	_22 = !(hasDot);
	if (_22)
	{
		NI32 _23;
		NI32 _25;
		NI32 _27;
		_23 = n;
		buf[(_23)- 0] = 46;
		_25 = (NI32)(n + ((NI32) 1));
		buf[(_25)- 0] = 48;
		_27 = (NI32)(n + ((NI32) 2));
		buf[(_27)- 0] = 0;
		result = (NI32)(n + ((NI32) 2));
		goto LA7_;
	}
	result = n;
	LA7_:;
	_30 = (NI32)(n - ((NI32) 1));
	_32 = ((TM__4A5tjg38HjlzLf9bEp3IRRA_2[(NU)(((NU8)(buf[(_30)- 0])))>>3] &(1U<<((NU)(((NU8)(buf[(_30)- 0])))&7U)))!=0);
	if (_32)
	{
		writeToBuffer__systemZformatfloat_65(buf, "nan");
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = ((NI32) 3);
		goto LA9_;
	}
	_34 = (NI32)(n - ((NI32) 1));
	_36 = ((NU8)(buf[(_34)- 0]) == (NU8)(70));
	if (_36)
	{
		NIM_BOOL _38;
		_38 = ((NU8)(buf[(((NI32) 0))- 0]) == (NU8)(45));
		if (_38)
		{
			writeToBuffer__systemZformatfloat_65(buf, "-inf");
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			result = ((NI32) 4);
			goto LA12_;
		}
		writeToBuffer__systemZformatfloat_65(buf, "inf");
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = ((NI32) 3);
		LA12_:;
		goto LA9_;
	}
	LA9_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, toChars__systemZdragonbox_700)(NIM_CHAR* buffer, NI bufferLen_0, NF64 v, NIM_BOOL forceTrailingDotZero) {
	NI32 result;
	NI32 pos;
	_G6Double_M16systemZdragonbox _6;
	NU64 significand;
	_G6Double_M16systemZdragonbox _8;
	NU64 exponent;
	NIM_BOOL _9;
	NIM_BOOL _10;
	NIM_BOOL _28;
	NI32 _40;
	NI32 _42;
	NI32 _44;
	NI32 _46;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	pos = ((NI32) 0);
	_6 = constructDouble__systemZdragonbox_31(v);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	significand = physicalSignificand__systemZdragonbox_34(_6);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_8 = constructDouble__systemZdragonbox_31(v);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	exponent = physicalExponent__systemZdragonbox_37(_8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_9 = (exponent == 2047ULL);
	_10 = !(_9);
	if (_10)
	{
		NI32 _11;
		_G6Double_M16systemZdragonbox _12;
		NI32 _13;
		NIM_BOOL _14;
		NIM_BOOL _15;
		NIM_BOOL _16;
		NI32 _20;
		NI32 _22;
		NI32 _24;
		NI32 _26;
		NI32 _27;
		_11 = pos;
		buffer[_11] = 45;
		_12 = constructDouble__systemZdragonbox_31(v);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_13 = signBit__systemZdragonbox_56(_12);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		pos = (NI32)(pos + _13);
		_14 = 0;
		_15 = (exponent == 0ULL);
		_14 = !(_15);
		_16 = !(_14);
		if (_16)
		{
			NIM_BOOL _17;
			_17 = (significand == 0ULL);
			_14 = !(_17);
		}
		if (_14)
		{
			_G17FloatingDecimal64_M16systemZdragonbox dec;
			dec = toDecimal64__systemZdragonbox_357(significand, exponent);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			result = formatDigits__systemZdragonbox_570(buffer, bufferLen_0, pos, dec.significand, dec.exponent, forceTrailingDotZero);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA3_;
		}
		_20 = pos;
		buffer[_20] = 48;
		_22 = (NI32)(pos + ((NI32) 1));
		buffer[_22] = 46;
		_24 = (NI32)(pos + ((NI32) 2));
		buffer[_24] = 48;
		_26 = (NI32)(pos + ((NI32) 3));
		buffer[_26] = 32;
		_27 = 0;
		if (forceTrailingDotZero)
		{
			_27 = ((NI32) 3);
			goto LA5_;
		}
		_27 = ((NI32) 1);
		LA5_:;
		pos = (NI32)(pos + _27);
		result = pos;
		goto LA3_;
	}
	_28 = (significand == 0ULL);
	if (_28)
	{
		NI32 _29;
		_G6Double_M16systemZdragonbox _30;
		NI32 _31;
		NI32 _32;
		NI32 _34;
		NI32 _36;
		NI32 _38;
		_29 = pos;
		buffer[_29] = 45;
		_30 = constructDouble__systemZdragonbox_31(v);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_31 = signBit__systemZdragonbox_56(_30);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		pos = (NI32)(pos + _31);
		_32 = pos;
		buffer[_32] = 105;
		_34 = (NI32)(pos + ((NI32) 1));
		buffer[_34] = 110;
		_36 = (NI32)(pos + ((NI32) 2));
		buffer[_36] = 102;
		_38 = (NI32)(pos + ((NI32) 3));
		buffer[_38] = 32;
		result = (NI32)(pos + ((NI32) 3));
		goto LA3_;
	}
	_40 = pos;
	buffer[_40] = 110;
	_42 = (NI32)(pos + ((NI32) 1));
	buffer[_42] = 97;
	_44 = (NI32)(pos + ((NI32) 2));
	buffer[_44] = 110;
	_46 = (NI32)(pos + ((NI32) 3));
	buffer[_46] = 32;
	result = (NI32)(pos + ((NI32) 3));
	goto LA3_;
	LA3_:;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__systemZformatfloat_65)(NIM_CHAR* buf, NCSTRING value) {
	NI32 i;
	i = ((NI32) 0);
	while (1) {
		NI32 _5;
		NIM_BOOL _6;
		NIM_BOOL colontmp_;
		NIM_BOOL _8;
		NI32 _9;
		NI32 _10;
		_5 = i;
		_6 = ((NU8)(value[_5]) == (NU8)(0));
		colontmp_ = !(_6);
		_8 = !(colontmp_);
		if (_8)
		{
			goto LA2_;
		}
		_9 = i;
		_10 = i;
		buf[(_9)- 0] = value[_10];
		i = (NI32)(i + ((NI32) 1));
	}
	LA2_:;
	return ;
}
static N_INLINE(_G17FloatingDecimal64_M16systemZdragonbox, toDecimal64__systemZdragonbox_357)(NU64 ieeeSignificand, NU64 ieeeExponent) {
	_G17FloatingDecimal64_M16systemZdragonbox result;
	NU64 m2;
	NI32 e2;
	NIM_BOOL _5;
	NIM_BOOL _6;
	NU64 _21;
	NIM_BOOL isEven;
	NIM_BOOL acceptLower;
	NIM_BOOL acceptUpper;
	NI32 _26;
	NI32 minusK;
	NI32 _29;
	NI32 _30;
	NI32 betaMinus1;
	NI32 _32;
	_G8uint64x2_M16systemZdragonbox pow10;
	NU32 delta;
	NU64 _36;
	NU64 twoFl;
	NU64 twoFc;
	NU64 _41;
	NU64 twoFr;
	NU64 _43;
	NU64 zi;
	NU64 q;
	NU32 _46;
	NU32 _47;
	NU32 _48;
	NU32 r;
	NIM_BOOL _50;
	NIM_BOOL _63;
	NU64 _71;
	NU32 _74;
	NU32 _75;
	NU32 dist;
	NU32 distQ;
	NU64 _77;
	NU32 _78;
	NIM_BOOL _79;
	NU64 _91;
	NI32 _92;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(_G17FloatingDecimal64_M16systemZdragonbox));
	m2 = 0;
	e2 = 0;
	_5 = (ieeeExponent == 0ULL);
	_6 = !(_5);
	if (_6)
	{
		NI32 _7;
		NIM_BOOL _8;
		NIM_BOOL _9;
		NI32 _10;
		NIM_BOOL _17;
		m2 = (NU64)(4503599627370496ULL | ieeeSignificand);
		_7 = ((NI32) (ieeeExponent));
		e2 = (NI32)(_7 - ((NI32) 1075));
		_8 = 0;
		_9 = 0;
		_10 = ((NI32)-(e2));
		_9 = (((NI32) 0) <= _10);
		if (_9)
		{
			NI32 _11;
			_11 = ((NI32)-(e2));
			_9 = (_11 < ((NI32) 53));
		}
		_8 = _9;
		if (_8)
		{
			NI32 _13;
			_13 = ((NI32)-(e2));
			_8 = multipleOfPow2__systemZdragonbox_148(m2, _13);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		if (_8)
		{
			NI32 _15;
			NU64 _16;
			_15 = ((NI32)-(e2));
			_16 = (NU64)((NU64)(m2) >> (NU64)(_15));
			nimZeroMem((void*)(&result), sizeof(_G17FloatingDecimal64_M16systemZdragonbox));
			result.significand = _16;
			result.exponent = ((NI32) 0);
			goto LA4_;
		}
		_17 = 0;
		_17 = (ieeeSignificand == 0ULL);
		if (_17)
		{
			_17 = ((NU64)(1ULL) < (NU64)(ieeeExponent));
		}
		if (_17)
		{
			result = toDecimal64AsymmetricInterval__systemZdragonbox_213(e2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA4_;
		}
		goto LA7_;
	}
	m2 = ieeeSignificand;
	e2 = ((NI32) -1074);
	LA7_:;
	_21 = (NU64)((NU64)(m2) % (NU64)(2ULL));
	isEven = (_21 == 0ULL);
	acceptLower = isEven;
	acceptUpper = isEven;
	_26 = floorLog10Pow2__systemZdragonbox_79(e2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	minusK = (NI32)(_26 - ((NI32) 2));
	_29 = ((NI32)-(minusK));
	_30 = floorLog2Pow10__systemZdragonbox_70(_29);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	betaMinus1 = (NI32)(e2 + _30);
	_32 = ((NI32)-(minusK));
	pow10 = computePow10__systemZdragonbox_100(_32);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	delta = computeDelta__systemZdragonbox_272(pow10, betaMinus1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_36 = (NU64)((NU64)(2ULL) * (NU64)(m2));
	twoFl = (NU64)((NU64)(_36) - (NU64)(1ULL));
	twoFc = (NU64)((NU64)(2ULL) * (NU64)(m2));
	_41 = (NU64)((NU64)(2ULL) * (NU64)(m2));
	twoFr = (NU64)((NU64)(_41) + (NU64)(1ULL));
	_43 = (NU64)((NU64)(twoFr) << (NU64)(betaMinus1));
	zi = mulShift__systemZdragonbox_312(_43, pow10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	q = (NU64)((NU64)(zi) / (NU64)(1000ULL));
	_46 = ((NU32) (zi));
	_47 = ((NU32) (q));
	_48 = (NU32)((NU32)(((NU32) 1000)) * (NU32)(_47));
	r = (NU32)((NU32)(_46) - (NU32)(_48));
	_50 = ((NU32)(r) < (NU32)(delta));
	if (_50)
	{
		NIM_BOOL _51;
		NIM_BOOL _52;
		NIM_BOOL _54;
		NIM_BOOL _55;
		NIM_BOOL _56;
		_51 = 0;
		_52 = 0;
		_54 = (r == ((NU32) 0));
		_52 = !(_54);
		_55 = !(_52);
		if (_55)
		{
			_52 = acceptUpper;
		}
		_51 = _52;
		_56 = !(_51);
		if (_56)
		{
			NIM_BOOL _58;
			_58 = isIntegralEndpoint__systemZdragonbox_347(twoFr, e2, minusK);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_51 = !(_58);
		}
		if (_51)
		{
			NU64 _59;
			NI32 _60;
			NI32 _61;
			_59 = q;
			_60 = (NI32)(minusK + ((NI32) 2));
			_61 = (NI32)(_60 + ((NI32) 1));
			nimZeroMem((void*)(&result), sizeof(_G17FloatingDecimal64_M16systemZdragonbox));
			result.significand = _59;
			result.exponent = _61;
			goto LA4_;
		}
		q = (NU64)((NU64)(q) - (NU64)(((NI32) 1)));
		r = ((NU32) 1000);
		goto LA12_;
	}
	_63 = (r == delta);
	if (_63)
	{
		NIM_BOOL _64;
		NIM_BOOL _65;
		NIM_BOOL _67;
		_64 = 0;
		_65 = 0;
		_65 = acceptLower;
		if (_65)
		{
			_65 = isIntegralEndpoint__systemZdragonbox_347(twoFl, e2, minusK);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		_64 = _65;
		_67 = !(_64);
		if (_67)
		{
			_64 = mulParity__systemZdragonbox_329(twoFl, pow10, betaMinus1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		if (_64)
		{
			NU64 _68;
			NI32 _69;
			NI32 _70;
			_68 = q;
			_69 = (NI32)(minusK + ((NI32) 2));
			_70 = (NI32)(_69 + ((NI32) 1));
			nimZeroMem((void*)(&result), sizeof(_G17FloatingDecimal64_M16systemZdragonbox));
			result.significand = _68;
			result.exponent = _70;
			goto LA4_;
		}
		goto LA12_;
	}
	LA12_:;
	_71 = q;
	q = (NU64)((NU64)(_71) * (NU64)(10ULL));
	_74 = (NU32)((NU32)(delta) / (NU32)(((NU32) 2)));
	_75 = (NU32)((NU32)(r) - (NU32)(_74));
	dist = (NU32)((NU32)(_75) + (NU32)(((NU32) 50)));
	distQ = (NU32)((NU32)(dist) / (NU32)(((NU32) 100)));
	_77 = ((NU64) (distQ));
	q = (NU64)((NU64)(q) + (NU64)(_77));
	_78 = (NU32)((NU32)(distQ) * (NU32)(((NU32) 100)));
	_79 = (dist == _78);
	if (_79)
	{
		NU32 _81;
		NIM_BOOL _82;
		NIM_BOOL approxYParity;
		NIM_BOOL _83;
		NIM_BOOL _84;
		NIM_BOOL _85;
		NIM_BOOL _86;
		NU64 _88;
		NIM_BOOL _89;
		_81 = (NU32)(dist & ((NU32) 1));
		_82 = (_81 == ((NU32) 0));
		approxYParity = !(_82);
		_83 = mulParity__systemZdragonbox_329(twoFc, pow10, betaMinus1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_84 = (_83 == approxYParity);
		_85 = !(_84);
		if (_85)
		{
			q = (NU64)((NU64)(q) - (NU64)(((NI32) 1)));
			goto LA19_;
		}
		_86 = 0;
		_88 = (NU64)((NU64)(q) % (NU64)(2ULL));
		_89 = (_88 == 0ULL);
		_86 = !(_89);
		if (_86)
		{
			_86 = isIntegralMidpoint__systemZdragonbox_352(twoFc, e2, minusK);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		if (_86)
		{
			q = (NU64)((NU64)(q) - (NU64)(((NI32) 1)));
			goto LA19_;
		}
		LA19_:;
	}
	_91 = q;
	_92 = (NI32)(minusK + ((NI32) 2));
	nimZeroMem((void*)(&result), sizeof(_G17FloatingDecimal64_M16systemZdragonbox));
	result.significand = _91;
	result.exponent = _92;
	goto LA4_;
	LA4_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, formatDigits__systemZdragonbox_570)(NIM_CHAR* buffer, NI bufferLen_0, NI32 pos, NU64 digits, NI32 decimalExponent, NIM_BOOL forceTrailingDotZero) {
	NI32 result;
	NI32 pos_2;
	NI32 numDigits;
	NI32 decimalPoint;
	NIM_BOOL _11;
	NIM_BOOL useFixed;
	NI32 a;
	NI32 b;
	NI32 i;
	NI32 decimalDigitsPosition;
	NI32 _28;
	NI32 _29;
	NI32 digitsEnd;
	NI32 tz;
	NI32 _32;
	NI32 _33;
	NI32 _73;
	NI32 _75;
	NIM_BOOL _77;
	NI32 _79;
	NI32 scientificExponent;
	NI32 _81;
	NI32 _83;
	NIM_CHAR* _84;
	NIM_BOOL _85;
	NI32 _87;
	NIM_BOOL _88;
	NU32 _89;
	NU32 k;
	NIM_BOOL _90;
	NIM_BOOL _94;
	NU32 q;
	NU32 r;
	NI32 _98;
	NU32 _99;
	NI32 _100;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	pos_2 = pos;
	numDigits = decimalLength__systemZdragonbox_556(digits);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	decimalPoint = (NI32)(numDigits + decimalExponent);
	_11 = 0;
	_11 = (((NI32) -6) <= decimalPoint);
	if (_11)
	{
		_11 = (decimalPoint <= ((NI32) 17));
	}
	useFixed = _11;
	a = ((NI32) 0);
	b = ((NI32) 32);
	i = a;
	while (1) {
		NIM_BOOL colontmp_;
		NIM_BOOL _18;
		NI32 i_2;
		NI32 _21;
		colontmp_ = (i < b);
		_18 = !(colontmp_);
		if (_18)
		{
			goto LA3_;
		}
		i_2 = i;
		_21 = (NI32)(pos_2 + i_2);
		buffer[_21] = 48;
		i = (NI32)(i + ((NI32) 1));
	}
	LA3_:;
	decimalDigitsPosition = 0;
	if (useFixed)
	{
		NIM_BOOL _23;
		_23 = (decimalPoint <= ((NI32) 0));
		if (_23)
		{
			decimalDigitsPosition = (NI32)(((NI32) 2) - decimalPoint);
			goto LA6_;
		}
		decimalDigitsPosition = ((NI32) 0);
		LA6_:;
		goto LA7_;
	}
	decimalDigitsPosition = ((NI32) 1);
	LA7_:;
	_28 = (NI32)(decimalDigitsPosition + numDigits);
	_29 = ((NI32) (_28));
	digitsEnd = (NI32)(pos_2 + _29);
	tz = printDecimalDigitsBackwards__systemZdragonbox_438(buffer, bufferLen_0, digitsEnd, digits);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_32 = ((NI32) (tz));
	digitsEnd = (NI32)(digitsEnd - _32);
	_33 = ((NI32) (tz));
	numDigits = (NI32)(numDigits - _33);
	if (useFixed)
	{
		NIM_BOOL _34;
		NIM_BOOL _38;
		NI32 _69;
		_34 = (decimalPoint <= ((NI32) 0));
		if (_34)
		{
			NI32 _36;
			_36 = (NI32)(pos_2 + ((NI32) 1));
			buffer[_36] = 46;
			pos_2 = digitsEnd;
			goto LA10_;
		}
		_38 = (decimalPoint < numDigits);
		if (_38)
		{
			_A16c tmp;
			NI32 a_2;
			NI32 b_2;
			NI32 i_3;
			NI32 a_3;
			NI32 b_3;
			NI32 i_5;
			NI32 _66;
			NI32 _67;
			nimZeroMem((void*)tmp, sizeof(_A16c));
			a_2 = ((NI32) 0);
			b_2 = ((NI32) 16);
			i_3 = a_2;
			while (1) {
				NIM_BOOL colontmp__2;
				NIM_BOOL _46;
				NI32 i_4;
				NI32 _49;
				NI32 _50;
				NI32 _51;
				colontmp__2 = (i_3 < b_2);
				_46 = !(colontmp__2);
				if (_46)
				{
					goto LA14_;
				}
				i_4 = i_3;
				_49 = (NI32)(i_4 + pos_2);
				_50 = ((NI32) (decimalPoint));
				_51 = (NI32)(_49 + _50);
				tmp[(i_4)- 0] = buffer[_51];
				i_3 = (NI32)(i_3 + ((NI32) 1));
			}
			LA14_:;
			a_3 = ((NI32) 0);
			b_3 = ((NI32) 16);
			i_5 = a_3;
			while (1) {
				NIM_BOOL colontmp__3;
				NIM_BOOL _58;
				NI32 i_6;
				NI32 _61;
				NI32 _62;
				NI32 _63;
				NI32 _64;
				colontmp__3 = (i_5 < b_3);
				_58 = !(colontmp__3);
				if (_58)
				{
					goto LA17_;
				}
				i_6 = i_5;
				_61 = (NI32)(i_6 + pos_2);
				_62 = ((NI32) (decimalPoint));
				_63 = (NI32)(_61 + _62);
				_64 = (NI32)(_63 + ((NI32) 1));
				buffer[_64] = tmp[(i_6)- 0];
				i_5 = (NI32)(i_5 + ((NI32) 1));
			}
			LA17_:;
			_66 = ((NI32) (decimalPoint));
			_67 = (NI32)(pos_2 + _66);
			buffer[_67] = 46;
			pos_2 = (NI32)(digitsEnd + ((NI32) 1));
			goto LA10_;
		}
		_69 = ((NI32) (decimalPoint));
		pos_2 = (NI32)(pos_2 + _69);
		if (forceTrailingDotZero)
		{
			NI32 _70;
			NI32 _72;
			_70 = pos_2;
			buffer[_70] = 46;
			_72 = (NI32)(pos_2 + ((NI32) 1));
			buffer[_72] = 48;
			pos_2 = (NI32)(pos_2 + ((NI32) 2));
		}
		LA10_:;
		goto LA19_;
	}
	_73 = pos_2;
	_75 = (NI32)(pos_2 + ((NI32) 1));
	buffer[_73] = buffer[_75];
	_77 = (numDigits == ((NI32) 1));
	if (_77)
	{
		pos_2 = (NI32)(pos_2 + ((NI32) 1));
		goto LA21_;
	}
	_79 = (NI32)(pos_2 + ((NI32) 1));
	buffer[_79] = 46;
	pos_2 = digitsEnd;
	LA21_:;
	scientificExponent = (NI32)(decimalPoint - ((NI32) 1));
	_81 = pos_2;
	buffer[_81] = 101;
	_83 = (NI32)(pos_2 + ((NI32) 1));
	_84 = (&buffer[_83]);
	_85 = (scientificExponent < ((NI32) 0));
	if (_85)
	{
		(*_84) = 45;
		goto LA23_;
	}
	(*_84) = 43;
	LA23_:;
	pos_2 = (NI32)(pos_2 + ((NI32) 2));
	_87 = 0;
	_88 = (scientificExponent < ((NI32) 0));
	if (_88)
	{
		_87 = ((NI32)-(scientificExponent));
		goto LA25_;
	}
	_87 = scientificExponent;
	LA25_:;
	_89 = ((NU32) (_87));
	k = _89;
	_90 = ((NU32)(k) < (NU32)(((NU32) 10)));
	if (_90)
	{
		NI32 _91;
		NU32 _92;
		NI32 _93;
		_91 = pos_2;
		_92 = (NU32)((NU32)(((NU32) 48)) + (NU32)(k));
		_93 = ((NI32) (_92));
		buffer[_91] = ((NIM_CHAR) (_93));
		pos_2 = (NI32)(pos_2 + ((NI32) 1));
		goto LA27_;
	}
	_94 = ((NU32)(k) < (NU32)(((NU32) 100)));
	if (_94)
	{
		utoa2Digits__stdZprivateZdigitsutils_27(buffer, bufferLen_0, pos_2, k);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		pos_2 = (NI32)(pos_2 + ((NI32) 2));
		goto LA27_;
	}
	q = (NU32)((NU32)(k) / (NU32)(((NU32) 100)));
	r = (NU32)((NU32)(k) % (NU32)(((NU32) 100)));
	_98 = pos_2;
	_99 = (NU32)((NU32)(((NU32) 48)) + (NU32)(q));
	_100 = ((NI32) (_99));
	buffer[_98] = ((NIM_CHAR) (_100));
	pos_2 = (NI32)(pos_2 + ((NI32) 1));
	utoa2Digits__stdZprivateZdigitsutils_27(buffer, bufferLen_0, pos_2, r);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	pos_2 = (NI32)(pos_2 + ((NI32) 2));
	LA27_:;
	LA19_:;
	result = pos_2;
	goto LA29_;
	LA29_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, multipleOfPow2__systemZdragonbox_148)(NU64 value, NI32 e2) {
	NIM_BOOL result;
	NIM_BOOL _3;
	_3 = 0;
	_3 = (e2 < ((NI32) 64));
	if (_3)
	{
		NU64 _4;
		NU64 _5;
		NU64 _6;
		_4 = (NU64)((NU64)(1ULL) << (NU64)(e2));
		_5 = (NU64)((NU64)(_4) - (NU64)(1ULL));
		_6 = (NU64)(value & _5);
		_3 = (_6 == 0ULL);
	}
	result = _3;
	goto LA1_;
	LA1_:;
	return result;
}
static N_INLINE(_G17FloatingDecimal64_M16systemZdragonbox, toDecimal64AsymmetricInterval__systemZdragonbox_213)(NI32 e2) {
	_G17FloatingDecimal64_M16systemZdragonbox result;
	NI32 minusK;
	NI32 _4;
	NI32 _5;
	NI32 betaMinus1;
	NI32 _7;
	_G8uint64x2_M16systemZdragonbox pow10;
	NU64 _9;
	NU64 _10;
	NI32 _11;
	NU64 lowerEndpoint;
	NU64 _13;
	NU64 _14;
	NI32 _15;
	NU64 upperEndpoint;
	NIM_BOOL _17;
	NIM_BOOL lowerEndpointIsInteger;
	NIM_BOOL _19;
	NU64 _20;
	NU64 xi;
	NU64 zi;
	NU64 q;
	NU64 _24;
	NIM_BOOL _25;
	NI32 _28;
	NU64 _29;
	NU64 _30;
	NIM_BOOL _31;
	NIM_BOOL _38;
	NI32 _39;
	NU64 _40;
	NI32 _41;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(_G17FloatingDecimal64_M16systemZdragonbox));
	minusK = floorLog10ThreeQuartersPow2__systemZdragonbox_88(e2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_4 = ((NI32)-(minusK));
	_5 = floorLog2Pow10__systemZdragonbox_70(_4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	betaMinus1 = (NI32)(e2 + _5);
	_7 = ((NI32)-(minusK));
	pow10 = computePow10__systemZdragonbox_100(_7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_9 = (NU64)((NU64)(pow10.hi) >> (NU64)(((NI32) 54)));
	_10 = (NU64)((NU64)(pow10.hi) - (NU64)(_9));
	_11 = (NI32)(((NI32) 11) - betaMinus1);
	lowerEndpoint = (NU64)((NU64)(_10) >> (NU64)(_11));
	_13 = (NU64)((NU64)(pow10.hi) >> (NU64)(((NI32) 53)));
	_14 = (NU64)((NU64)(pow10.hi) + (NU64)(_13));
	_15 = (NI32)(((NI32) 11) - betaMinus1);
	upperEndpoint = (NU64)((NU64)(_14) >> (NU64)(_15));
	_17 = 0;
	_17 = (((NI32) 2) <= e2);
	if (_17)
	{
		_17 = (e2 <= ((NI32) 3));
	}
	lowerEndpointIsInteger = _17;
	_19 = !(lowerEndpointIsInteger);
	_20 = ((NU64) (_19));
	xi = (NU64)((NU64)(lowerEndpoint) + (NU64)(_20));
	zi = upperEndpoint;
	q = (NU64)((NU64)(zi) / (NU64)(10ULL));
	_24 = (NU64)((NU64)(q) * (NU64)(10ULL));
	_25 = ((NU64)(xi) <= (NU64)(_24));
	if (_25)
	{
		NU64 _26;
		NI32 _27;
		_26 = q;
		_27 = (NI32)(minusK + ((NI32) 1));
		nimZeroMem((void*)(&result), sizeof(_G17FloatingDecimal64_M16systemZdragonbox));
		result.significand = _26;
		result.exponent = _27;
		goto LA2_;
	}
	_28 = (NI32)(((NI32) 10) - betaMinus1);
	_29 = (NU64)((NU64)(pow10.hi) >> (NU64)(_28));
	_30 = (NU64)((NU64)(_29) + (NU64)(1ULL));
	q = (NU64)((NU64)(_30) / (NU64)(2ULL));
	_31 = (e2 == ((NI32) -77));
	if (_31)
	{
		NU64 _33;
		NIM_BOOL _34;
		NIM_BOOL _35;
		NI32 _36;
		_33 = (NU64)((NU64)(q) % (NU64)(2ULL));
		_34 = (_33 == 0ULL);
		_35 = !(_34);
		_36 = _35;
		q = (NU64)((NU64)(q) - (NU64)(_36));
		goto LA4_;
	}
	_38 = ((NU64)(q) < (NU64)(xi));
	_39 = _38;
	q = (NU64)((NU64)(q) + (NU64)(_39));
	LA4_:;
	_40 = q;
	_41 = minusK;
	nimZeroMem((void*)(&result), sizeof(_G17FloatingDecimal64_M16systemZdragonbox));
	result.significand = _40;
	result.exponent = _41;
	goto LA2_;
	LA2_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, floorLog10Pow2__systemZdragonbox_79)(NI32 e) {
	NI32 result;
	NI32 _2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_2 = (NI32)(e * ((NI32) 1262611));
	result = floorDivPow2__systemZdragonbox_62(_2, ((NI32) 22));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, floorLog2Pow10__systemZdragonbox_70)(NI32 e) {
	NI32 result;
	NI32 _2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_2 = (NI32)(e * ((NI32) 1741647));
	result = floorDivPow2__systemZdragonbox_62(_2, ((NI32) 19));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(_G8uint64x2_M16systemZdragonbox, computePow10__systemZdragonbox_100)(NI32 k) {
	_G8uint64x2_M16systemZdragonbox result;
	NI32 _2;
	_2 = (NI32)(k - ((NI32) -292));
	result = pow10__systemZdragonbox_105[(_2)- 0];
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NU32, computeDelta__systemZdragonbox_272)(_G8uint64x2_M16systemZdragonbox pow10, NI32 betaMinus1) {
	NU32 result;
	NI32 _3;
	NU64 _4;
	NU32 _5;
	_3 = (NI32)(((NI32) 63) - betaMinus1);
	_4 = (NU64)((NU64)(pow10.hi) >> (NU64)(_3));
	_5 = ((NU32) (_4));
	result = _5;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NU64, mulShift__systemZdragonbox_312)(NU64 x, _G8uint64x2_M16systemZdragonbox y) {
	NU64 result;
	_G8uint64x2_M16systemZdragonbox p1;
	_G8uint64x2_M16systemZdragonbox p0;
	NU64* _5;
	NU64* _7;
	NIM_BOOL _10;
	NI32 _11;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	p1 = mul128__systemZdragonbox_296(x, y.hi);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	p0 = mul128__systemZdragonbox_296(x, y.lo);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_5 = (&p1.lo);
	(*_5) = (NU64)((NU64)((*_5)) + (NU64)(p0.hi));
	_7 = (&p1.hi);
	_10 = ((NU64)(p1.lo) < (NU64)(p0.hi));
	_11 = _10;
	(*_7) = (NU64)((NU64)((*_7)) + (NU64)(_11));
	result = p1.hi;
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, isIntegralEndpoint__systemZdragonbox_347)(NU64 twoF, NI32 e2, NI32 minusK) {
	NIM_BOOL result;
	NIM_BOOL _4;
	NIM_BOOL _5;
	NIM_BOOL _6;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_4 = (e2 < ((NI32) -2));
	if (_4)
	{
		result = NIM_FALSE;
		goto LA1_;
	}
	_5 = (e2 <= ((NI32) 9));
	if (_5)
	{
		result = NIM_TRUE;
		goto LA1_;
	}
	_6 = (e2 <= ((NI32) 86));
	if (_6)
	{
		result = multipleOfPow5__systemZdragonbox_159(twoF, minusK);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA1_;
	}
	result = NIM_FALSE;
	goto LA1_;
	LA1_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mulParity__systemZdragonbox_329)(NU64 twoF, _G8uint64x2_M16systemZdragonbox pow10, NI32 betaMinus1) {
	NIM_BOOL result;
	NU64 p01;
	_G8uint64x2_M16systemZdragonbox _6;
	NU64 p10;
	NU64 mid;
	NI32 _8;
	NU64 _9;
	NU64 _10;
	NIM_BOOL _11;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	p01 = (NU64)((NU64)(twoF) * (NU64)(pow10.hi));
	_6 = mul128__systemZdragonbox_296(twoF, pow10.lo);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	p10 = _6.hi;
	mid = (NU64)((NU64)(p01) + (NU64)(p10));
	_8 = (NI32)(((NI32) 64) - betaMinus1);
	_9 = (NU64)((NU64)(1ULL) << (NU64)(_8));
	_10 = (NU64)(mid & _9);
	_11 = (_10 == 0ULL);
	result = !(_11);
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, isIntegralMidpoint__systemZdragonbox_352)(NU64 twoF, NI32 e2, NI32 minusK) {
	NIM_BOOL result;
	NIM_BOOL _4;
	NIM_BOOL _7;
	NIM_BOOL _8;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_4 = (e2 < ((NI32) -4));
	if (_4)
	{
		NI32 _5;
		NI32 _6;
		_5 = (NI32)(minusK - e2);
		_6 = (NI32)(_5 + ((NI32) 1));
		result = multipleOfPow2__systemZdragonbox_148(twoF, _6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA1_;
	}
	_7 = (e2 <= ((NI32) 9));
	if (_7)
	{
		result = NIM_TRUE;
		goto LA1_;
	}
	_8 = (e2 <= ((NI32) 86));
	if (_8)
	{
		result = multipleOfPow5__systemZdragonbox_159(twoF, minusK);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto LA1_;
	}
	result = NIM_FALSE;
	goto LA1_;
	LA1_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, decimalLength__systemZdragonbox_556)(NU64 v) {
	NI32 result;
	NU64 _2;
	NU32 _3;
	NIM_BOOL _4;
	NIM_BOOL _5;
	NU32 _14;
	NU32 v32;
	NU32 _15;
	NIM_BOOL _16;
	NU32 _17;
	NIM_BOOL _18;
	NU32 _19;
	NIM_BOOL _20;
	NU32 _21;
	NIM_BOOL _22;
	NU32 _23;
	NIM_BOOL _24;
	NU32 _25;
	NIM_BOOL _26;
	NU32 _27;
	NIM_BOOL _28;
	NU32 _29;
	NIM_BOOL _30;
	NU32 _31;
	NIM_BOOL _32;
	_2 = (NU64)((NU64)(v) >> (NU64)(((NI32) 32)));
	_3 = ((NU32) (_2));
	_4 = (_3 == ((NU32) 0));
	_5 = !(_4);
	if (_5)
	{
		NIM_BOOL _6;
		NIM_BOOL _7;
		NIM_BOOL _8;
		NIM_BOOL _9;
		NIM_BOOL _10;
		NIM_BOOL _11;
		NIM_BOOL _12;
		_6 = ((NU64)(10000000000000000ULL) <= (NU64)(v));
		if (_6)
		{
			result = ((NI32) 17);
			goto LA2_;
		}
		_7 = ((NU64)(1000000000000000ULL) <= (NU64)(v));
		if (_7)
		{
			result = ((NI32) 16);
			goto LA2_;
		}
		_8 = ((NU64)(100000000000000ULL) <= (NU64)(v));
		if (_8)
		{
			result = ((NI32) 15);
			goto LA2_;
		}
		_9 = ((NU64)(10000000000000ULL) <= (NU64)(v));
		if (_9)
		{
			result = ((NI32) 14);
			goto LA2_;
		}
		_10 = ((NU64)(1000000000000ULL) <= (NU64)(v));
		if (_10)
		{
			result = ((NI32) 13);
			goto LA2_;
		}
		_11 = ((NU64)(100000000000ULL) <= (NU64)(v));
		if (_11)
		{
			result = ((NI32) 12);
			goto LA2_;
		}
		_12 = ((NU64)(10000000000ULL) <= (NU64)(v));
		if (_12)
		{
			result = ((NI32) 11);
			goto LA2_;
		}
		result = ((NI32) 10);
		goto LA2_;
	}
	_14 = ((NU32) (v));
	v32 = _14;
	_15 = ((NU32) (v32));
	_16 = ((NU32)(((NU32) 1000000000)) <= (NU32)(_15));
	if (_16)
	{
		result = ((NI32) 10);
		goto LA2_;
	}
	_17 = ((NU32) (v32));
	_18 = ((NU32)(((NU32) 100000000)) <= (NU32)(_17));
	if (_18)
	{
		result = ((NI32) 9);
		goto LA2_;
	}
	_19 = ((NU32) (v32));
	_20 = ((NU32)(((NU32) 10000000)) <= (NU32)(_19));
	if (_20)
	{
		result = ((NI32) 8);
		goto LA2_;
	}
	_21 = ((NU32) (v32));
	_22 = ((NU32)(((NU32) 1000000)) <= (NU32)(_21));
	if (_22)
	{
		result = ((NI32) 7);
		goto LA2_;
	}
	_23 = ((NU32) (v32));
	_24 = ((NU32)(((NU32) 100000)) <= (NU32)(_23));
	if (_24)
	{
		result = ((NI32) 6);
		goto LA2_;
	}
	_25 = ((NU32) (v32));
	_26 = ((NU32)(((NU32) 10000)) <= (NU32)(_25));
	if (_26)
	{
		result = ((NI32) 5);
		goto LA2_;
	}
	_27 = ((NU32) (v32));
	_28 = ((NU32)(((NU32) 1000)) <= (NU32)(_27));
	if (_28)
	{
		result = ((NI32) 4);
		goto LA2_;
	}
	_29 = ((NU32) (v32));
	_30 = ((NU32)(((NU32) 100)) <= (NU32)(_29));
	if (_30)
	{
		result = ((NI32) 3);
		goto LA2_;
	}
	_31 = ((NU32) (v32));
	_32 = ((NU32)(((NU32) 10)) <= (NU32)(_31));
	if (_32)
	{
		result = ((NI32) 2);
		goto LA2_;
	}
	result = ((NI32) 1);
	goto LA2_;
	LA2_:;
	return result;
}
static N_INLINE(NI32, printDecimalDigitsBackwards__systemZdragonbox_438)(NIM_CHAR* buf, NI bufLen_0, NI32 pos, NU64 output64) {
	NI32 result;
	NI32 pos_2;
	NU64 output64_2;
	NI32 tz;
	NI32 nd;
	NIM_BOOL _9;
	NU32 _20;
	NU32 output;
	NIM_BOOL _22;
	NIM_BOOL _59;
	NIM_BOOL _83;
	NU32 q_5;
	NI32 _92;
	NU32 _93;
	NI32 _94;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	pos_2 = pos;
	output64_2 = output64;
	tz = ((NI32) 0);
	nd = ((NI32) 0);
	_9 = ((NU64)(100000000ULL) <= (NU64)(output64_2));
	if (_9)
	{
		NU64 q;
		NU64 _14;
		NU32 _15;
		NU32 r;
		NIM_BOOL _16;
		NIM_BOOL _17;
		q = (NU64)((NU64)(output64_2) / (NU64)(100000000ULL));
		_14 = (NU64)((NU64)(output64_2) % (NU64)(100000000ULL));
		_15 = ((NU32) (_14));
		r = _15;
		output64_2 = q;
		pos_2 = (NI32)(pos_2 - ((NI32) 8));
		_16 = (r == ((NU32) 0));
		_17 = !(_16);
		if (_17)
		{
			tz = utoa8DigitsSkipTrailingZeros__systemZdragonbox_421(buf, bufLen_0, pos_2, r);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA2_;
		}
		tz = ((NI32) 8);
		LA2_:;
		nd = ((NI32) 8);
	}
	_20 = ((NU32) (output64_2));
	output = _20;
	_22 = ((NU32)(((NU32) 10000)) <= (NU32)(output));
	if (_22)
	{
		NU32 q_2;
		NU32 r_2;
		NIM_BOOL _27;
		NIM_BOOL _28;
		NIM_BOOL _47;
		NI32 a;
		NI32 b;
		NI32 res;
		q_2 = (NU32)((NU32)(output) / (NU32)(((NU32) 10000)));
		r_2 = (NU32)((NU32)(output) % (NU32)(((NU32) 10000)));
		output = q_2;
		pos_2 = (NI32)(pos_2 - ((NI32) 4));
		_27 = (r_2 == ((NU32) 0));
		_28 = !(_27);
		if (_28)
		{
			NU32 rH;
			NU32 rL;
			NI32 _33;
			NIM_BOOL _36;
			rH = (NU32)((NU32)(r_2) / (NU32)(((NU32) 100)));
			rL = (NU32)((NU32)(r_2) % (NU32)(((NU32) 100)));
			utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos_2, rH);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_33 = (NI32)(pos_2 + ((NI32) 2));
			utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, _33, rL);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_36 = (tz == nd);
			if (_36)
			{
				NU32 _37;
				NIM_BOOL _38;
				NI32 _39;
				NI32 _40;
				NIM_BOOL _41;
				NI32 _42;
				NI32 _43;
				NI32 _44;
				_37 = 0;
				_38 = (rL == ((NU32) 0));
				if (_38)
				{
					_37 = rH;
					goto LA7_;
				}
				_37 = rL;
				LA7_:;
				_39 = trailingZeros2Digits__stdZprivateZdigitsutils_43(_37);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				_40 = 0;
				_41 = (rL == ((NU32) 0));
				if (_41)
				{
					_40 = ((NI32) 2);
					goto LA9_;
				}
				_40 = ((NI32) 0);
				LA9_:;
				_42 = ((NI32) (_40));
				_43 = (NI32)(_39 + _42);
				_44 = ((NI32) (_43));
				tz = (NI32)(tz + _44);
			}
			goto LA10_;
		}
		_47 = (tz == nd);
		if (_47)
		{
			tz = (NI32)(tz + ((NI32) 4));
			goto LA12_;
		}
		a = ((NI32) 0);
		b = ((NI32) 3);
		res = a;
		while (1) {
			NIM_BOOL colontmp_;
			NIM_BOOL _54;
			NI32 i;
			NI32 _57;
			colontmp_ = (res <= b);
			_54 = !(colontmp_);
			if (_54)
			{
				goto LA15_;
			}
			i = res;
			_57 = (NI32)(pos_2 + i);
			buf[_57] = 48;
			res = (NI32)(res + ((NI32) 1));
		}
		LA15_:;
		LA12_:;
		LA10_:;
		nd = (NI32)(nd + ((NI32) 4));
	}
	_59 = ((NU32)(((NU32) 100)) <= (NU32)(output));
	if (_59)
	{
		NU32 q_3;
		NU32 r_3;
		NIM_BOOL _67;
		NIM_BOOL _71;
		q_3 = (NU32)((NU32)(output) / (NU32)(((NU32) 100)));
		r_3 = (NU32)((NU32)(output) % (NU32)(((NU32) 100)));
		output = q_3;
		pos_2 = (NI32)(pos_2 - ((NI32) 2));
		utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos_2, r_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_67 = (tz == nd);
		if (_67)
		{
			NI32 _68;
			NI32 _69;
			_68 = trailingZeros2Digits__stdZprivateZdigitsutils_43(r_3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_69 = ((NI32) (_68));
			tz = (NI32)(tz + _69);
		}
		nd = (NI32)(nd + ((NI32) 2));
		_71 = ((NU32)(((NU32) 100)) <= (NU32)(output));
		if (_71)
		{
			NU32 q2;
			NU32 r2;
			NIM_BOOL _79;
			q2 = (NU32)((NU32)(output) / (NU32)(((NU32) 100)));
			r2 = (NU32)((NU32)(output) % (NU32)(((NU32) 100)));
			output = q2;
			pos_2 = (NI32)(pos_2 - ((NI32) 2));
			utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos_2, r2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_79 = (tz == nd);
			if (_79)
			{
				NI32 _80;
				NI32 _81;
				_80 = trailingZeros2Digits__stdZprivateZdigitsutils_43(r2);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				_81 = ((NI32) (_80));
				tz = (NI32)(tz + _81);
			}
			nd = (NI32)(nd + ((NI32) 2));
		}
	}
	_83 = ((NU32)(((NU32) 10)) <= (NU32)(output));
	if (_83)
	{
		NU32 q_4;
		NIM_BOOL _88;
		q_4 = output;
		pos_2 = (NI32)(pos_2 - ((NI32) 2));
		utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos_2, q_4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_88 = (tz == nd);
		if (_88)
		{
			NI32 _89;
			NI32 _90;
			_89 = trailingZeros2Digits__stdZprivateZdigitsutils_43(q_4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_90 = ((NI32) (_89));
			tz = (NI32)(tz + _90);
		}
		goto LA22_;
	}
	q_5 = output;
	pos_2 = (NI32)(pos_2 - ((NI32) 1));
	_92 = pos_2;
	_93 = (NU32)((NU32)(((NU32) 48)) + (NU32)(q_5));
	_94 = ((NI32) (_93));
	buf[_92] = ((NIM_CHAR) (_94));
	LA22_:;
	result = tz;
	goto LA23_;
	LA23_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, utoa2Digits__stdZprivateZdigitsutils_27)(NIM_CHAR* buf, NI bufLen_0, NI32 pos, NU32 digits) {
	NU32 _4;
	NI32 _5;
	NU32 _6;
	NU32 _7;
	_4 = (NU32)((NU32)(((NU32) 2)) * (NU32)(digits));
	buf[pos] = digits100__stdZprivateZdigitsutils_2[(_4)- 0];
	_5 = (NI32)(pos + ((NI32) 1));
	_6 = (NU32)((NU32)(((NU32) 2)) * (NU32)(digits));
	_7 = (NU32)((NU32)(_6) + (NU32)(((NU32) 1)));
	buf[_5] = digits100__stdZprivateZdigitsutils_2[(_7)- 0];
	return ;
}
static N_INLINE(NI32, floorLog10ThreeQuartersPow2__systemZdragonbox_88)(NI32 e) {
	NI32 result;
	NI32 _2;
	NI32 _3;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_2 = (NI32)(e * ((NI32) 1262611));
	_3 = (NI32)(_2 - ((NI32) 524031));
	result = floorDivPow2__systemZdragonbox_62(_3, ((NI32) 22));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, floorDivPow2__systemZdragonbox_62)(NI32 x, NI32 n) {
	NI32 result;
	result = (NI32)((NI32)(x) >> (NU32)(n));
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(_G8uint64x2_M16systemZdragonbox, mul128__systemZdragonbox_296)(NU64 a, NU64 b) {
	_G8uint64x2_M16systemZdragonbox result;
	NU32 _4;
	NU64 _5;
	NU32 _6;
	NU64 _7;
	NU64 b00;
	NU32 _9;
	NU64 _10;
	NU32 _11;
	NU64 _12;
	NU64 b01;
	NU32 _14;
	NU64 _15;
	NU32 _16;
	NU64 _17;
	NU64 b10;
	NU32 _19;
	NU64 _20;
	NU32 _21;
	NU64 _22;
	NU64 b11;
	NU32 _24;
	NU64 _25;
	NU64 mid1;
	NU32 _27;
	NU64 _28;
	NU64 mid2;
	NU32 _30;
	NU64 _31;
	NU64 _32;
	NU32 _33;
	NU64 _34;
	NU64 hi;
	NU32 _36;
	NU64 _37;
	NU32 _38;
	NU64 _39;
	NU64 _40;
	NU64 lo;
	NU64 _41;
	NU64 _42;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(_G8uint64x2_M16systemZdragonbox));
	_4 = lo32__systemZdragonbox_286(a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_5 = ((NU64) (_4));
	_6 = lo32__systemZdragonbox_286(b);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_7 = ((NU64) (_6));
	b00 = (NU64)((NU64)(_5) * (NU64)(_7));
	_9 = lo32__systemZdragonbox_286(a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_10 = ((NU64) (_9));
	_11 = hi32__systemZdragonbox_289(b);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_12 = ((NU64) (_11));
	b01 = (NU64)((NU64)(_10) * (NU64)(_12));
	_14 = hi32__systemZdragonbox_289(a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_15 = ((NU64) (_14));
	_16 = lo32__systemZdragonbox_286(b);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_17 = ((NU64) (_16));
	b10 = (NU64)((NU64)(_15) * (NU64)(_17));
	_19 = hi32__systemZdragonbox_289(a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_20 = ((NU64) (_19));
	_21 = hi32__systemZdragonbox_289(b);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_22 = ((NU64) (_21));
	b11 = (NU64)((NU64)(_20) * (NU64)(_22));
	_24 = hi32__systemZdragonbox_289(b00);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_25 = ((NU64) (_24));
	mid1 = (NU64)((NU64)(b10) + (NU64)(_25));
	_27 = lo32__systemZdragonbox_286(mid1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_28 = ((NU64) (_27));
	mid2 = (NU64)((NU64)(b01) + (NU64)(_28));
	_30 = hi32__systemZdragonbox_289(mid1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_31 = ((NU64) (_30));
	_32 = (NU64)((NU64)(b11) + (NU64)(_31));
	_33 = hi32__systemZdragonbox_289(mid2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_34 = ((NU64) (_33));
	hi = (NU64)((NU64)(_32) + (NU64)(_34));
	_36 = lo32__systemZdragonbox_286(b00);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_37 = ((NU64) (_36));
	_38 = lo32__systemZdragonbox_286(mid2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_39 = ((NU64) (_38));
	_40 = (NU64)((NU64)(_39) << (NU64)(((NI32) 32)));
	lo = (NU64)(_37 | _40);
	_41 = hi;
	_42 = lo;
	nimZeroMem((void*)(&result), sizeof(_G8uint64x2_M16systemZdragonbox));
	result.hi = _41;
	result.lo = _42;
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, multipleOfPow5__systemZdragonbox_159)(NU64 value, NI32 e5) {
	NIM_BOOL result;
	_L6MulCmp_163_M16systemZdragonbox m5;
	NU64 _4;
	m5 = mod5__systemZdragonbox_166[(e5)- 0];
	_4 = (NU64)((NU64)(value) * (NU64)(m5.mul));
	result = ((NU64)(_4) <= (NU64)(m5.cmp));
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NI32, utoa8DigitsSkipTrailingZeros__systemZdragonbox_421)(NIM_CHAR* buf, NI bufLen_0, NI32 pos, NU32 digits) {
	NI32 result;
	NU32 q;
	NU32 r;
	NU32 qH;
	NU32 qL;
	NI32 _8;
	NIM_BOOL _9;
	NU32 rH;
	NU32 rL;
	NI32 _18;
	NI32 _19;
	NU32 _20;
	NIM_BOOL _21;
	NI32 _22;
	NI32 _23;
	NIM_BOOL _24;
	NI32 _25;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	q = (NU32)((NU32)(digits) / (NU32)(((NU32) 10000)));
	r = (NU32)((NU32)(digits) % (NU32)(((NU32) 10000)));
	qH = (NU32)((NU32)(q) / (NU32)(((NU32) 100)));
	qL = (NU32)((NU32)(q) % (NU32)(((NU32) 100)));
	utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos, qH);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_8 = (NI32)(pos + ((NI32) 2));
	utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, _8, qL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_9 = (r == ((NU32) 0));
	if (_9)
	{
		NU32 _10;
		NIM_BOOL _11;
		NI32 _12;
		NI32 _13;
		NIM_BOOL _14;
		NI32 _15;
		_10 = 0;
		_11 = (qL == ((NU32) 0));
		if (_11)
		{
			_10 = qH;
			goto LA2_;
		}
		_10 = qL;
		LA2_:;
		_12 = trailingZeros2Digits__stdZprivateZdigitsutils_43(_10);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_13 = 0;
		_14 = (qL == ((NU32) 0));
		if (_14)
		{
			_13 = ((NI32) 6);
			goto LA4_;
		}
		_13 = ((NI32) 4);
		LA4_:;
		_15 = ((NI32) (_13));
		result = (NI32)(_12 + _15);
		goto LA5_;
	}
	rH = (NU32)((NU32)(r) / (NU32)(((NU32) 100)));
	rL = (NU32)((NU32)(r) % (NU32)(((NU32) 100)));
	_18 = (NI32)(pos + ((NI32) 4));
	utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, _18, rH);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_19 = (NI32)(pos + ((NI32) 6));
	utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, _19, rL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_20 = 0;
	_21 = (rL == ((NU32) 0));
	if (_21)
	{
		_20 = rH;
		goto LA7_;
	}
	_20 = rL;
	LA7_:;
	_22 = trailingZeros2Digits__stdZprivateZdigitsutils_43(_20);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_23 = 0;
	_24 = (rL == ((NU32) 0));
	if (_24)
	{
		_23 = ((NI32) 2);
		goto LA9_;
	}
	_23 = ((NI32) 0);
	LA9_:;
	_25 = ((NI32) (_23));
	result = (NI32)(_22 + _25);
	goto LA5_;
	LA5_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, trailingZeros2Digits__stdZprivateZdigitsutils_43)(NU32 digits) {
	NI32 result;
	result = ((NI32) (trailingZeros100__stdZprivateZdigitsutils_1[(digits)- 0]));
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NU32, lo32__systemZdragonbox_286)(NU64 x) {
	NU32 result;
	NU32 _2;
	_2 = ((NU32) (x));
	result = _2;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NU32, hi32__systemZdragonbox_289)(NU64 x) {
	NU32 result;
	NU64 _2;
	NU32 _3;
	_2 = (NU64)((NU64)(x) >> (NU64)(((NI32) 32)));
	_3 = ((NU32) (_2));
	result = _3;
	goto LA0_;
	LA0_:;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI32, writeFloatToBufferRoundtrip__systemZformatfloat_58)(NIM_CHAR* buf, NF32 value) {
	NI32 result;
	_oc _3;
	NI32 _4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_3.Field0 = buf; _3.Field1 = 65;
	result = float32ToChars__systemZschubfach_365(_3.Field0, _3.Field1, value, NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_4 = result;
	buf[(_4)- 0] = 0;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, float32ToChars__systemZschubfach_365)(NIM_CHAR* buffer, NI bufferLen_0, NF32 v, NIM_BOOL forceTrailingDotZero) {
	NI32 result;
	_L6Single_6_M16systemZschubfach _5;
	NU32 significand;
	_L6Single_6_M16systemZschubfach _7;
	NU32 exponent;
	NI32 pos;
	NIM_BOOL _9;
	NIM_BOOL _10;
	NIM_BOOL _28;
	NI32 _40;
	NI32 _42;
	NI32 _44;
	NI32 _46;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_5 = constructSingle__systemZschubfach_28(v);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	significand = physicalSignificand__systemZschubfach_31(_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_7 = constructSingle__systemZschubfach_28(v);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	exponent = physicalExponent__systemZschubfach_34(_7);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	pos = ((NI32) 0);
	_9 = (exponent == ((NU32) 255));
	_10 = !(_9);
	if (_10)
	{
		NI32 _11;
		_L6Single_6_M16systemZschubfach _12;
		NI32 _13;
		NIM_BOOL _14;
		NIM_BOOL _15;
		NIM_BOOL _16;
		NI32 _20;
		NI32 _22;
		NI32 _24;
		NI32 _26;
		NI32 _27;
		_11 = pos;
		buffer[_11] = 45;
		_12 = constructSingle__systemZschubfach_28(v);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_13 = signBit__systemZschubfach_41(_12);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		pos = (NI32)(pos + _13);
		_14 = 0;
		_15 = (exponent == ((NU32) 0));
		_14 = !(_15);
		_16 = !(_14);
		if (_16)
		{
			NIM_BOOL _17;
			_17 = (significand == ((NU32) 0));
			_14 = !(_17);
		}
		if (_14)
		{
			_L17FloatingDecimal32_130_M16systemZschubfach dec;
			dec = toDecimal32__systemZschubfach_133(significand, exponent);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			result = formatDigits__systemZschubfach_280(buffer, bufferLen_0, pos, dec.digits, dec.exponent, forceTrailingDotZero);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA3_;
		}
		_20 = pos;
		buffer[_20] = 48;
		_22 = (NI32)(pos + ((NI32) 1));
		buffer[_22] = 46;
		_24 = (NI32)(pos + ((NI32) 2));
		buffer[_24] = 48;
		_26 = (NI32)(pos + ((NI32) 3));
		buffer[_26] = 32;
		_27 = 0;
		if (forceTrailingDotZero)
		{
			_27 = ((NI32) 3);
			goto LA5_;
		}
		_27 = ((NI32) 1);
		LA5_:;
		pos = (NI32)(pos + _27);
		result = pos;
		goto LA3_;
	}
	_28 = (significand == ((NU32) 0));
	if (_28)
	{
		NI32 _29;
		_L6Single_6_M16systemZschubfach _30;
		NI32 _31;
		NI32 _32;
		NI32 _34;
		NI32 _36;
		NI32 _38;
		_29 = pos;
		buffer[_29] = 45;
		_30 = constructSingle__systemZschubfach_28(v);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_31 = signBit__systemZschubfach_41(_30);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		pos = (NI32)(pos + _31);
		_32 = pos;
		buffer[_32] = 105;
		_34 = (NI32)(pos + ((NI32) 1));
		buffer[_34] = 110;
		_36 = (NI32)(pos + ((NI32) 2));
		buffer[_36] = 102;
		_38 = (NI32)(pos + ((NI32) 3));
		buffer[_38] = 32;
		result = (NI32)(pos + ((NI32) 3));
		goto LA3_;
	}
	_40 = pos;
	buffer[_40] = 110;
	_42 = (NI32)(pos + ((NI32) 1));
	buffer[_42] = 97;
	_44 = (NI32)(pos + ((NI32) 2));
	buffer[_44] = 110;
	_46 = (NI32)(pos + ((NI32) 3));
	buffer[_46] = 32;
	result = (NI32)(pos + ((NI32) 3));
	goto LA3_;
	LA3_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(_L17FloatingDecimal32_130_M16systemZschubfach, toDecimal32__systemZschubfach_133)(NU32 ieeeSignificand, NU32 ieeeExponent) {
	_L17FloatingDecimal32_130_M16systemZschubfach result;
	NU32 c;
	NI32 q;
	NIM_BOOL _5;
	NIM_BOOL _6;
	NU32 _19;
	NIM_BOOL isEven;
	NIM_BOOL _21;
	NIM_BOOL lowerBoundaryIsCloser;
	NU32 _24;
	NU32 _25;
	NU32 _26;
	NU32 cbl;
	NU32 cb;
	NU32 _31;
	NU32 cbr;
	NI32 _34;
	NI32 _35;
	NI32 _36;
	NI32 _37;
	NI32 k;
	NI32 _40;
	NI32 _41;
	NI32 _42;
	NI32 h;
	NI32 _44;
	NU64 pow10;
	NU32 _46;
	NU32 vbl;
	NU32 _48;
	NU32 vb;
	NU32 _50;
	NU32 vbr;
	NIM_BOOL _52;
	NU32 _53;
	NU32 lower;
	NIM_BOOL _55;
	NU32 _56;
	NU32 upper;
	NU32 s;
	NIM_BOOL _58;
	NU32 _71;
	NIM_BOOL uInside;
	NU32 _73;
	NU32 _74;
	NIM_BOOL wInside;
	NIM_BOOL _75;
	NIM_BOOL _76;
	NU32 _81;
	NU32 mid;
	NIM_BOOL _83;
	NIM_BOOL _84;
	NIM_BOOL roundUp;
	NU32 _88;
	NU32 _89;
	NI32 _90;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(_L17FloatingDecimal32_130_M16systemZschubfach));
	c = 0;
	q = 0;
	_5 = (ieeeExponent == ((NU32) 0));
	_6 = !(_5);
	if (_6)
	{
		NI32 _7;
		NIM_BOOL _8;
		NIM_BOOL _9;
		NI32 _10;
		c = (NU32)(((NU32) 8388608) | ieeeSignificand);
		_7 = ((NI32) (ieeeExponent));
		q = (NI32)(_7 - ((NI32) 150));
		_8 = 0;
		_9 = 0;
		_10 = ((NI32)-(q));
		_9 = (((NI32) 0) <= _10);
		if (_9)
		{
			NI32 _11;
			_11 = ((NI32)-(q));
			_9 = (_11 < ((NI32) 24));
		}
		_8 = _9;
		if (_8)
		{
			NI32 _13;
			_13 = ((NI32)-(q));
			_8 = multipleOfPow2__systemZschubfach_116(c, _13);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		if (_8)
		{
			NI32 _15;
			NU32 _16;
			_15 = ((NI32)-(q));
			_16 = (NU32)((NU32)(c) >> (NU32)(_15));
			nimZeroMem((void*)(&result), sizeof(_L17FloatingDecimal32_130_M16systemZschubfach));
			result.digits = _16;
			result.exponent = ((NI32) 0);
			goto LA4_;
		}
		goto LA5_;
	}
	c = ieeeSignificand;
	q = ((NI32) -149);
	LA5_:;
	_19 = (NU32)((NU32)(c) % (NU32)(((NU32) 2)));
	isEven = (_19 == ((NU32) 0));
	_21 = 0;
	_21 = (ieeeSignificand == ((NU32) 0));
	if (_21)
	{
		_21 = ((NU32)(((NU32) 1)) < (NU32)(ieeeExponent));
	}
	lowerBoundaryIsCloser = _21;
	_24 = (NU32)((NU32)(((NU32) 4)) * (NU32)(c));
	_25 = (NU32)((NU32)(_24) - (NU32)(((NU32) 2)));
	_26 = ((NU32) (lowerBoundaryIsCloser));
	cbl = (NU32)((NU32)(_25) + (NU32)(_26));
	cb = (NU32)((NU32)(((NU32) 4)) * (NU32)(c));
	_31 = (NU32)((NU32)(((NU32) 4)) * (NU32)(c));
	cbr = (NU32)((NU32)(_31) + (NU32)(((NU32) 2)));
	_34 = (NI32)(q * ((NI32) 1262611));
	_35 = 0;
	if (lowerBoundaryIsCloser)
	{
		_35 = ((NI32) 524031);
		goto LA8_;
	}
	_35 = ((NI32) 0);
	LA8_:;
	_36 = ((NI32) (_35));
	_37 = (NI32)(_34 - _36);
	k = floorDivPow2__systemZschubfach_44(_37, ((NI32) 22));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_40 = ((NI32)-(k));
	_41 = floorLog2Pow10__systemZschubfach_52(_40);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_42 = (NI32)(q + _41);
	h = (NI32)(_42 + ((NI32) 1));
	_44 = ((NI32)-(k));
	pow10 = computePow10Single__systemZschubfach_76(_44);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_46 = (NU32)((NU32)(cbl) << (NU32)(h));
	vbl = roundToOdd__systemZschubfach_107(pow10, _46);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_48 = (NU32)((NU32)(cb) << (NU32)(h));
	vb = roundToOdd__systemZschubfach_107(pow10, _48);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_50 = (NU32)((NU32)(cbr) << (NU32)(h));
	vbr = roundToOdd__systemZschubfach_107(pow10, _50);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_52 = !(isEven);
	_53 = ((NU32) (_52));
	lower = (NU32)((NU32)(vbl) + (NU32)(_53));
	_55 = !(isEven);
	_56 = ((NU32) (_55));
	upper = (NU32)((NU32)(vbr) - (NU32)(_56));
	s = (NU32)((NU32)(vb) / (NU32)(((NU32) 4)));
	_58 = ((NU32)(((NU32) 10)) <= (NU32)(s));
	if (_58)
	{
		NU32 sp;
		NU32 _61;
		NIM_BOOL upInside;
		NU32 _63;
		NU32 _64;
		NIM_BOOL wpInside;
		NIM_BOOL _65;
		NIM_BOOL _66;
		sp = (NU32)((NU32)(s) / (NU32)(((NU32) 10)));
		_61 = (NU32)((NU32)(((NU32) 40)) * (NU32)(sp));
		upInside = ((NU32)(lower) <= (NU32)(_61));
		_63 = (NU32)((NU32)(((NU32) 40)) * (NU32)(sp));
		_64 = (NU32)((NU32)(_63) + (NU32)(((NU32) 40)));
		wpInside = ((NU32)(_64) <= (NU32)(upper));
		_65 = (upInside == wpInside);
		_66 = !(_65);
		if (_66)
		{
			NU32 _67;
			NU32 _68;
			NI32 _69;
			_67 = ((NU32) (wpInside));
			_68 = (NU32)((NU32)(sp) + (NU32)(_67));
			_69 = (NI32)(k + ((NI32) 1));
			nimZeroMem((void*)(&result), sizeof(_L17FloatingDecimal32_130_M16systemZschubfach));
			result.digits = _68;
			result.exponent = _69;
			goto LA4_;
		}
	}
	_71 = (NU32)((NU32)(((NU32) 4)) * (NU32)(s));
	uInside = ((NU32)(lower) <= (NU32)(_71));
	_73 = (NU32)((NU32)(((NU32) 4)) * (NU32)(s));
	_74 = (NU32)((NU32)(_73) + (NU32)(((NU32) 4)));
	wInside = ((NU32)(_74) <= (NU32)(upper));
	_75 = (uInside == wInside);
	_76 = !(_75);
	if (_76)
	{
		NU32 _77;
		NU32 _78;
		NI32 _79;
		_77 = ((NU32) (wInside));
		_78 = (NU32)((NU32)(s) + (NU32)(_77));
		_79 = k;
		nimZeroMem((void*)(&result), sizeof(_L17FloatingDecimal32_130_M16systemZschubfach));
		result.digits = _78;
		result.exponent = _79;
		goto LA4_;
	}
	_81 = (NU32)((NU32)(((NU32) 4)) * (NU32)(s));
	mid = (NU32)((NU32)(_81) + (NU32)(((NU32) 2)));
	_83 = 0;
	_83 = ((NU32)(mid) < (NU32)(vb));
	_84 = !(_83);
	if (_84)
	{
		NIM_BOOL _85;
		_85 = 0;
		_85 = (vb == mid);
		if (_85)
		{
			NU32 _86;
			NIM_BOOL _87;
			_86 = (NU32)(s & ((NU32) 1));
			_87 = (_86 == ((NU32) 0));
			_85 = !(_87);
		}
		_83 = _85;
	}
	roundUp = _83;
	_88 = ((NU32) (roundUp));
	_89 = (NU32)((NU32)(s) + (NU32)(_88));
	_90 = k;
	nimZeroMem((void*)(&result), sizeof(_L17FloatingDecimal32_130_M16systemZschubfach));
	result.digits = _89;
	result.exponent = _90;
	goto LA4_;
	LA4_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, formatDigits__systemZschubfach_280)(NIM_CHAR* buffer, NI bufferLen_0, NI32 pos, NU32 digits, NI32 decimalExponent, NIM_BOOL forceTrailingDotZero) {
	NI32 result;
	NI32 pos_2;
	NI32 numDigits;
	NI32 decimalPoint;
	NIM_BOOL _11;
	NIM_BOOL useFixed;
	NI32 a;
	NI32 b;
	NI32 i;
	NI32 decimalDigitsPosition;
	NI32 _26;
	NI32 _27;
	NI32 _28;
	NI32 digitsEnd;
	NI32 tz;
	NI32 _31;
	NI32 _32;
	NI32 _61;
	NI32 _63;
	NIM_BOOL _65;
	NI32 _67;
	NI32 scientificExponent;
	NI32 _69;
	NI32 _71;
	NIM_CHAR* _72;
	NIM_BOOL _73;
	NI32 _75;
	NIM_BOOL _76;
	NU32 _77;
	NU32 k;
	NIM_BOOL _78;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	pos_2 = pos;
	numDigits = decimalLength__systemZschubfach_271(digits);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	decimalPoint = (NI32)(numDigits + decimalExponent);
	_11 = 0;
	_11 = (((NI32) -4) <= decimalPoint);
	if (_11)
	{
		_11 = (decimalPoint <= ((NI32) 9));
	}
	useFixed = _11;
	a = ((NI32) 0);
	b = ((NI32) 32);
	i = a;
	while (1) {
		NIM_BOOL colontmp_;
		NIM_BOOL _18;
		NI32 i_2;
		NI32 _21;
		colontmp_ = (i < b);
		_18 = !(colontmp_);
		if (_18)
		{
			goto LA3_;
		}
		i_2 = i;
		_21 = (NI32)(pos_2 + i_2);
		buffer[_21] = 48;
		i = (NI32)(i + ((NI32) 1));
	}
	LA3_:;
	decimalDigitsPosition = 0;
	if (useFixed)
	{
		NIM_BOOL _23;
		_23 = (decimalPoint <= ((NI32) 0));
		if (_23)
		{
			decimalDigitsPosition = (NI32)(((NI32) 2) - decimalPoint);
			goto LA6_;
		}
		decimalDigitsPosition = ((NI32) 0);
		LA6_:;
		goto LA7_;
	}
	decimalDigitsPosition = ((NI32) 1);
	LA7_:;
	_26 = ((NI32) (decimalDigitsPosition));
	_27 = (NI32)(pos_2 + _26);
	_28 = ((NI32) (numDigits));
	digitsEnd = (NI32)(_27 + _28);
	tz = printDecimalDigitsBackwards__systemZschubfach_200(buffer, bufferLen_0, digitsEnd, digits);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_31 = ((NI32) (tz));
	digitsEnd = (NI32)(digitsEnd - _31);
	_32 = ((NI32) (tz));
	numDigits = (NI32)(numDigits - _32);
	if (useFixed)
	{
		NIM_BOOL _33;
		NIM_BOOL _37;
		NI32 _57;
		_33 = (decimalPoint <= ((NI32) 0));
		if (_33)
		{
			NI32 _35;
			_35 = (NI32)(pos_2 + ((NI32) 1));
			buffer[_35] = 46;
			pos_2 = digitsEnd;
			goto LA10_;
		}
		_37 = (decimalPoint < numDigits);
		if (_37)
		{
			NI32 a_2;
			NI32 b_2;
			NI32 step;
			NI32 res;
			NI32 _54;
			NI32 _55;
			a_2 = ((NI32) 7);
			b_2 = ((NI32) 0);
			step = ((NI32) 1);
			res = a_2;
			while (1) {
				NIM_BOOL colontmp__2;
				NIM_BOOL _45;
				NI32 i_3;
				NI32 _47;
				NI32 _48;
				NI32 _49;
				NI32 _50;
				NI32 _51;
				NI32 _52;
				colontmp__2 = (b_2 <= res);
				_45 = !(colontmp__2);
				if (_45)
				{
					goto LA14_;
				}
				i_3 = res;
				_47 = ((NI32) (decimalPoint));
				_48 = (NI32)(i_3 + _47);
				_49 = (NI32)(_48 + ((NI32) 1));
				_50 = ((NI32) (decimalPoint));
				_51 = (NI32)(i_3 + _50);
				buffer[_49] = buffer[_51];
				_52 = ((NI32) (step));
				res = (NI32)(res - _52);
			}
			LA14_:;
			_54 = ((NI32) (decimalPoint));
			_55 = (NI32)(pos_2 + _54);
			buffer[_55] = 46;
			pos_2 = (NI32)(digitsEnd + ((NI32) 1));
			goto LA10_;
		}
		_57 = ((NI32) (decimalPoint));
		pos_2 = (NI32)(pos_2 + _57);
		if (forceTrailingDotZero)
		{
			NI32 _58;
			NI32 _60;
			_58 = pos_2;
			buffer[_58] = 46;
			_60 = (NI32)(pos_2 + ((NI32) 1));
			buffer[_60] = 48;
			pos_2 = (NI32)(pos_2 + ((NI32) 2));
		}
		LA10_:;
		goto LA16_;
	}
	_61 = pos_2;
	_63 = (NI32)(pos_2 + ((NI32) 1));
	buffer[_61] = buffer[_63];
	_65 = (numDigits == ((NI32) 1));
	if (_65)
	{
		pos_2 = (NI32)(pos_2 + ((NI32) 1));
		goto LA18_;
	}
	_67 = (NI32)(pos_2 + ((NI32) 1));
	buffer[_67] = 46;
	pos_2 = digitsEnd;
	LA18_:;
	scientificExponent = (NI32)(decimalPoint - ((NI32) 1));
	_69 = pos_2;
	buffer[_69] = 101;
	_71 = (NI32)(pos_2 + ((NI32) 1));
	_72 = (&buffer[_71]);
	_73 = (scientificExponent < ((NI32) 0));
	if (_73)
	{
		(*_72) = 45;
		goto LA20_;
	}
	(*_72) = 43;
	LA20_:;
	pos_2 = (NI32)(pos_2 + ((NI32) 2));
	_75 = 0;
	_76 = (scientificExponent < ((NI32) 0));
	if (_76)
	{
		_75 = ((NI32)-(scientificExponent));
		goto LA22_;
	}
	_75 = scientificExponent;
	LA22_:;
	_77 = ((NU32) (_75));
	k = _77;
	_78 = ((NU32)(k) < (NU32)(((NU32) 10)));
	if (_78)
	{
		NI32 _79;
		NU32 _80;
		NI32 _81;
		_79 = pos_2;
		_80 = (NU32)((NU32)(((NU32) 48)) + (NU32)(k));
		_81 = ((NI32) (_80));
		buffer[_79] = ((NIM_CHAR) (_81));
		pos_2 = (NI32)(pos_2 + ((NI32) 1));
		goto LA24_;
	}
	utoa2Digits__stdZprivateZdigitsutils_27(buffer, bufferLen_0, pos_2, k);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	pos_2 = (NI32)(pos_2 + ((NI32) 2));
	LA24_:;
	LA16_:;
	result = pos_2;
	goto LA25_;
	LA25_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, multipleOfPow2__systemZschubfach_116)(NU32 value, NI32 e2) {
	NIM_BOOL result;
	NU32 _3;
	NU32 _4;
	NU32 _5;
	_3 = (NU32)((NU32)(((NU32) 1)) << (NU32)(e2));
	_4 = (NU32)((NU32)(_3) - (NU32)(((NU32) 1)));
	_5 = (NU32)(value & _4);
	result = (_5 == ((NU32) 0));
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NI32, floorDivPow2__systemZschubfach_44)(NI32 x, NI32 n) {
	NI32 result;
	result = (NI32)((NI32)(x) >> (NU32)(n));
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NI32, floorLog2Pow10__systemZschubfach_52)(NI32 e) {
	NI32 result;
	NI32 _2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_2 = (NI32)(e * ((NI32) 1741647));
	result = floorDivPow2__systemZschubfach_44(_2, ((NI32) 19));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU64, computePow10Single__systemZschubfach_76)(NI32 k) {
	NU64 result;
	NI32 _2;
	_2 = (NI32)(k - ((NI32) -31));
	result = g__systemZschubfach_63[(_2)- 0];
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NU32, roundToOdd__systemZschubfach_107)(NU64 g, NU32 cp) {
	NU32 result;
	NU32 _4;
	NU64 _5;
	NU64 _6;
	NU64 b01;
	NU32 _8;
	NU64 _9;
	NU64 _10;
	NU64 b11;
	NU32 _12;
	NU64 _13;
	NU64 hi;
	NU32 y1;
	NU32 y0;
	NIM_BOOL _16;
	NU32 _17;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	_4 = lo32__systemZschubfach_97(g);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_5 = ((NU64) (_4));
	_6 = ((NU64) (cp));
	b01 = (NU64)((NU64)(_5) * (NU64)(_6));
	_8 = hi32__systemZschubfach_100(g);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_9 = ((NU64) (_8));
	_10 = ((NU64) (cp));
	b11 = (NU64)((NU64)(_9) * (NU64)(_10));
	_12 = hi32__systemZschubfach_100(b01);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_13 = ((NU64) (_12));
	hi = (NU64)((NU64)(b11) + (NU64)(_13));
	y1 = hi32__systemZschubfach_100(hi);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	y0 = lo32__systemZschubfach_97(hi);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	_16 = ((NU32)(((NU32) 1)) < (NU32)(y0));
	_17 = ((NU32) (_16));
	result = (NU32)(y1 | _17);
	goto LA0_;
	LA0_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI32, decimalLength__systemZschubfach_271)(NU32 v) {
	NI32 result;
	NU32 _2;
	NIM_BOOL _3;
	NU32 _4;
	NIM_BOOL _5;
	NU32 _6;
	NIM_BOOL _7;
	NU32 _8;
	NIM_BOOL _9;
	NU32 _10;
	NIM_BOOL _11;
	NU32 _12;
	NIM_BOOL _13;
	NU32 _14;
	NIM_BOOL _15;
	NU32 _16;
	NIM_BOOL _17;
	_2 = ((NU32) (v));
	_3 = ((NU32)(((NU32) 100000000)) <= (NU32)(_2));
	if (_3)
	{
		result = ((NI32) 9);
		goto LA1_;
	}
	_4 = ((NU32) (v));
	_5 = ((NU32)(((NU32) 10000000)) <= (NU32)(_4));
	if (_5)
	{
		result = ((NI32) 8);
		goto LA1_;
	}
	_6 = ((NU32) (v));
	_7 = ((NU32)(((NU32) 1000000)) <= (NU32)(_6));
	if (_7)
	{
		result = ((NI32) 7);
		goto LA1_;
	}
	_8 = ((NU32) (v));
	_9 = ((NU32)(((NU32) 100000)) <= (NU32)(_8));
	if (_9)
	{
		result = ((NI32) 6);
		goto LA1_;
	}
	_10 = ((NU32) (v));
	_11 = ((NU32)(((NU32) 10000)) <= (NU32)(_10));
	if (_11)
	{
		result = ((NI32) 5);
		goto LA1_;
	}
	_12 = ((NU32) (v));
	_13 = ((NU32)(((NU32) 1000)) <= (NU32)(_12));
	if (_13)
	{
		result = ((NI32) 4);
		goto LA1_;
	}
	_14 = ((NU32) (v));
	_15 = ((NU32)(((NU32) 100)) <= (NU32)(_14));
	if (_15)
	{
		result = ((NI32) 3);
		goto LA1_;
	}
	_16 = ((NU32) (v));
	_17 = ((NU32)(((NU32) 10)) <= (NU32)(_16));
	if (_17)
	{
		result = ((NI32) 2);
		goto LA1_;
	}
	result = ((NI32) 1);
	goto LA1_;
	LA1_:;
	return result;
}
static N_INLINE(NI32, printDecimalDigitsBackwards__systemZschubfach_200)(NIM_CHAR* buf, NI bufLen_0, NI32 pos, NU32 output) {
	NI32 result;
	NU32 output_2;
	NI32 pos_2;
	NI32 tz;
	NI32 nd;
	NIM_BOOL _9;
	NIM_BOOL _28;
	NIM_BOOL _52;
	NU32 q_4;
	NI32 _61;
	NU32 _62;
	NI32 _63;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0;
	output_2 = output;
	pos_2 = pos;
	tz = ((NI32) 0);
	nd = ((NI32) 0);
	_9 = ((NU32)(((NU32) 10000)) <= (NU32)(output_2));
	if (_9)
	{
		NU32 q;
		NU32 r;
		NIM_BOOL _14;
		NIM_BOOL _15;
		q = (NU32)((NU32)(output_2) / (NU32)(((NU32) 10000)));
		r = (NU32)((NU32)(output_2) % (NU32)(((NU32) 10000)));
		output_2 = q;
		pos_2 = (NI32)(pos_2 - ((NI32) 4));
		_14 = (r == ((NU32) 0));
		_15 = !(_14);
		if (_15)
		{
			NU32 rH;
			NU32 rL;
			NI32 _20;
			NU32 _21;
			NIM_BOOL _22;
			NI32 _23;
			NI32 _24;
			NIM_BOOL _25;
			NI32 _26;
			rH = (NU32)((NU32)(r) / (NU32)(((NU32) 100)));
			rL = (NU32)((NU32)(r) % (NU32)(((NU32) 100)));
			utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos_2, rH);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_20 = (NI32)(pos_2 + ((NI32) 2));
			utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, _20, rL);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_21 = 0;
			_22 = (rL == ((NU32) 0));
			if (_22)
			{
				_21 = rH;
				goto LA3_;
			}
			_21 = rL;
			LA3_:;
			_23 = trailingZeros2Digits__stdZprivateZdigitsutils_43(_21);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_24 = 0;
			_25 = (rL == ((NU32) 0));
			if (_25)
			{
				_24 = ((NI32) 2);
				goto LA5_;
			}
			_24 = ((NI32) 0);
			LA5_:;
			_26 = ((NI32) (_24));
			tz = (NI32)(_23 + _26);
			goto LA6_;
		}
		tz = ((NI32) 4);
		LA6_:;
		nd = ((NI32) 4);
	}
	_28 = ((NU32)(((NU32) 100)) <= (NU32)(output_2));
	if (_28)
	{
		NU32 q_2;
		NU32 r_2;
		NIM_BOOL _36;
		NIM_BOOL _40;
		q_2 = (NU32)((NU32)(output_2) / (NU32)(((NU32) 100)));
		r_2 = (NU32)((NU32)(output_2) % (NU32)(((NU32) 100)));
		output_2 = q_2;
		pos_2 = (NI32)(pos_2 - ((NI32) 2));
		utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos_2, r_2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_36 = (tz == nd);
		if (_36)
		{
			NI32 _37;
			NI32 _38;
			_37 = trailingZeros2Digits__stdZprivateZdigitsutils_43(r_2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_38 = ((NI32) (_37));
			tz = (NI32)(tz + _38);
		}
		nd = (NI32)(nd + ((NI32) 2));
		_40 = ((NU32)(((NU32) 100)) <= (NU32)(output_2));
		if (_40)
		{
			NU32 q2;
			NU32 r2;
			NIM_BOOL _48;
			q2 = (NU32)((NU32)(output_2) / (NU32)(((NU32) 100)));
			r2 = (NU32)((NU32)(output_2) % (NU32)(((NU32) 100)));
			output_2 = q2;
			pos_2 = (NI32)(pos_2 - ((NI32) 2));
			utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos_2, r2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_48 = (tz == nd);
			if (_48)
			{
				NI32 _49;
				NI32 _50;
				_49 = trailingZeros2Digits__stdZprivateZdigitsutils_43(r2);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				_50 = ((NI32) (_49));
				tz = (NI32)(tz + _50);
			}
			nd = (NI32)(nd + ((NI32) 2));
		}
	}
	_52 = ((NU32)(((NU32) 10)) <= (NU32)(output_2));
	if (_52)
	{
		NU32 q_3;
		NIM_BOOL _57;
		q_3 = output_2;
		pos_2 = (NI32)(pos_2 - ((NI32) 2));
		utoa2Digits__stdZprivateZdigitsutils_27(buf, bufLen_0, pos_2, q_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		_57 = (tz == nd);
		if (_57)
		{
			NI32 _58;
			NI32 _59;
			_58 = trailingZeros2Digits__stdZprivateZdigitsutils_43(q_3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			_59 = ((NI32) (_58));
			tz = (NI32)(tz + _59);
		}
		goto LA13_;
	}
	q_4 = output_2;
	pos_2 = (NI32)(pos_2 - ((NI32) 1));
	_61 = pos_2;
	_62 = (NU32)((NU32)(((NU32) 48)) + (NU32)(q_4));
	_63 = ((NI32) (_62));
	buf[_61] = ((NIM_CHAR) (_63));
	LA13_:;
	result = tz;
	goto LA14_;
	LA14_:;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU32, lo32__systemZschubfach_97)(NU64 x) {
	NU32 result;
	NU32 _2;
	_2 = ((NU32) (x));
	result = _2;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NU32, hi32__systemZschubfach_100)(NU64 x) {
	NU32 result;
	NU64 _2;
	NU32 _3;
	_2 = (NU64)((NU64)(x) >> (NU64)(((NI32) 32)));
	_3 = ((NU32) (_2));
	result = _3;
	goto LA0_;
	LA0_:;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_4132);
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI32 size) {
	size_t _4;
	void* _5;
	_4 = ((size_t) (size));
	_5 = memset(a, v, _4);
	return ;
}
static N_INLINE(void, nimZeroMem)(void* p, NI32 size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	return ;
}
