/* Generated by Nim Compiler v0.1.0-dev.20827 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ;
typedef struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ;
typedef struct tyTuple__0F3Kz25HWtRatQmCDVHWEA tyTuple__0F3Kz25HWtRatQmCDVHWEA;
typedef struct tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg;
typedef struct tySequence__xv3aaFd3JCw8NbmALHiezQ tySequence__xv3aaFd3JCw8NbmALHiezQ;
typedef struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content tySequence__xv3aaFd3JCw8NbmALHiezQ_Content;
typedef struct tyTuple__sPaDkVPSC0MkcoXCxPH9ccA tyTuple__sPaDkVPSC0MkcoXCxPH9ccA;
typedef struct tyObject_NimSeqV2__Yc9cU9agg3xM9abj4BkJ7E2Ew tyObject_NimSeqV2__Yc9cU9agg3xM9abj4BkJ7E2Ew;
typedef struct tyObject_NimSeqPayload__o16XxZeeToQysG5CEWXEzg tyObject_NimSeqPayload__o16XxZeeToQysG5CEWXEzg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
NI rootIdx;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ {
NI len;
NI cap;
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
void** Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyUncheckedArray__sC1L67m2tqEzJLHInkP5AQ[1];
struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ {
NI len;
NI cap;
tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;
};
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ {
tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ traceStack;
tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ toFree;
NI freed;
NI touched;
NI edges;
NI rcSum;
NIM_BOOL keepThreshold;
};
struct tySequence__xv3aaFd3JCw8NbmALHiezQ {
  NI len; tySequence__xv3aaFd3JCw8NbmALHiezQ_Content* p;
};
typedef NU8 tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg {
  RootObj Sup;
NI counter;
tySequence__xv3aaFd3JCw8NbmALHiezQ data;
tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct tyTuple__sPaDkVPSC0MkcoXCxPH9ccA {
NimStringV2 Field0;
NimStringV2 Field1;
NIM_BOOL Field2;
};
struct tyObject_NimSeqV2__Yc9cU9agg3xM9abj4BkJ7E2Ew {
NI len;
tyObject_NimSeqPayload__o16XxZeeToQysG5CEWXEzg* p;
};
struct tyObject_NimSeqPayload__o16XxZeeToQysG5CEWXEzg {
NI cap;
tyTuple__sPaDkVPSC0MkcoXCxPH9ccA data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyEnum_FormatFlag__F4vlKAV4d0Kt9aXmu9cVNBrg;
typedef NU8 tyEnum_FormatFlag__F4vlKAV4d0Kt9aXmu9cVNBrg;
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__xv3aaFd3JCw8NbmALHiezQ_Content_PP
#define tySequence__xv3aaFd3JCw8NbmALHiezQ_Content_PP
struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content { NI cap; tyTuple__sPaDkVPSC0MkcoXCxPH9ccA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__xv3aaFd3JCw8NbmALHiezQ_Content_PP
#define tySequence__xv3aaFd3JCw8NbmALHiezQ_Content_PP
struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content { NI cap; tyTuple__sPaDkVPSC0MkcoXCxPH9ccA data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___system_704)(NI x, NI y);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3163)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3228)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3266)(tySequence__uB9b75OUPRENsBAu4AnoePA* dest);
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env);
static N_INLINE(void, add__system_2722)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ* s, void** c, TNimTypeV2* t);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__system_1724)(NI size);
static N_INLINE(void, copyMem__system_1708)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZstrtabs_249)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key);
N_LIB_PRIVATE N_NIMCALL(NI, myhash__pureZstrtabs_229)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_279)(NimStringV2 x);
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase__pureZhashes_353)(NimStringV2 x);
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle__pureZhashes_290)(NimStringV2 x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, myCmp__pureZstrtabs_233)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 a, NimStringV2 b);
N_LIB_PRIVATE N_NIMCALL(NI, cmp__system_1540)(NimStringV2 x, NimStringV2 y);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringV2 a, NimStringV2 b);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NI, nextTry__pureZstrtabs_245)(NI h, NI maxHash);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_3234)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mustRehash__pureZstrtabs_238)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZstrtabs_352)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZstrtabs_358)(tySequence__xv3aaFd3JCw8NbmALHiezQ* s, NI len);
N_LIB_PRIVATE N_NIMCALL(void, shrink__pureZstrtabs_106)(tySequence__xv3aaFd3JCw8NbmALHiezQ* x, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, reset__pureZstrtabs_126)(tyTuple__sPaDkVPSC0MkcoXCxPH9ccA* obj);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZstrtabs_140)(tyTuple__sPaDkVPSC0MkcoXCxPH9ccA* dest, tyTuple__sPaDkVPSC0MkcoXCxPH9ccA src);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZstrtabs_98)(tySequence__xv3aaFd3JCw8NbmALHiezQ* s, NI newlen);
N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd)(NI len, void* p, NI addlen, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZstrtabs_340)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, tySequence__xv3aaFd3JCw8NbmALHiezQ* data, NimStringV2 key, NimStringV2 val);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrtabs_81)(tySequence__xv3aaFd3JCw8NbmALHiezQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrtabs_428)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrtabs_411)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* dest);
static N_INLINE(void, nimIncRefCyclic)(void* p, NIM_BOOL cyclic);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsthasKey)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3231)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getValue__pureZstrtabs_481)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, tySet_tyEnum_FormatFlag__F4vlKAV4d0Kt9aXmu9cVNBrg flags, NimStringV2 key);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getOrDefault__pureZstrtabs_326)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key, NimStringV2 default_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__pureZos_459)(NimStringV2 key, NimStringV2 default_0);
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, raiseFormatException__pureZstrtabs_475)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_7563)(NimStringV2 s, NI first, NI last);
extern TNimTypeV2 NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_;
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__ZT9crccxweoChVXn9cHcxIXQ_2 = { 15 | NIM_STRLIT_FLAG, "key not found: " };
static const NimStringV2 TM__ZT9crccxweoChVXn9cHcxIXQ_3 = {15, (NimStrPayload*)&TM__ZT9crccxweoChVXn9cHcxIXQ_2};
N_LIB_PRIVATE TNimTypeV2 NTIv2__V5PVrt9bIxZEeV7lfvqqtNg_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__ZT9crccxweoChVXn9cHcxIXQ_4 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__ZT9crccxweoChVXn9cHcxIXQ_5 = {0, (NimStrPayload*)&TM__ZT9crccxweoChVXn9cHcxIXQ_4};
static const NimStringV2 TM__ZT9crccxweoChVXn9cHcxIXQ_6 = {0, (NimStrPayload*)&TM__ZT9crccxweoChVXn9cHcxIXQ_4};
static const NimStringV2 TM__ZT9crccxweoChVXn9cHcxIXQ_7 = {0, (NimStrPayload*)&TM__ZT9crccxweoChVXn9cHcxIXQ_4};
static const NimStringV2 TM__ZT9crccxweoChVXn9cHcxIXQ_8 = {0, (NimStrPayload*)&TM__ZT9crccxweoChVXn9cHcxIXQ_4};
static const NimStringV2 TM__ZT9crccxweoChVXn9cHcxIXQ_9 = {0, (NimStrPayload*)&TM__ZT9crccxweoChVXn9cHcxIXQ_4};
static const NimStringV2 TM__ZT9crccxweoChVXn9cHcxIXQ_10 = {0, (NimStrPayload*)&TM__ZT9crccxweoChVXn9cHcxIXQ_4};
extern TNimTypeV2 NTIv2__yoNlBGx0D2tRizIdhQuENw_;
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__ZT9crccxweoChVXn9cHcxIXQ_11 = { 30 | NIM_STRLIT_FLAG, "format string: key not found: " };
static const NimStringV2 TM__ZT9crccxweoChVXn9cHcxIXQ_12 = {30, (NimStrPayload*)&TM__ZT9crccxweoChVXn9cHcxIXQ_11};
extern NIM_BOOL nimInErrorMode__system_4174;
static N_INLINE(NI, minuspercent___system_704)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_704(((NI) (ptrdiff_t) (p)), ((NI) 8));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			{
				if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA9_;
				result = NIM_TRUE;
				goto LA6;
			}
			LA9_: ;
			(*cell).rc -= ((NI) 16);
		} LA6: ;
		rememberCycle__system_3163(result, cell, (*((TNimTypeV2**) (p))));
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrtabs_289)(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___system_3228((&(*dest).Sup.Sup.Sup.message));
	eqdestroy___system_3266((&(*dest).Sup.Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.up);
	}
	LA9_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
	(void)(T1_);
}
static N_INLINE(void, copyMem__system_1708)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4174);
	return result;
}
static N_INLINE(void, add__system_2722)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ* s, void** c, TNimTypeV2* t) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
		void* T5_;
		if (!((*s).cap <= (*s).len)) goto LA3_;
		(*s).cap = (NI)((NI)((*s).cap * ((NI) 3)) / ((NI) 2));
		T5_ = (void*)0;
		T5_ = allocImpl__system_1724(((NI) ((NI)((*s).cap * ((NI) 8)))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		d = ((tyTuple__N4J9cV4JZGem3ljqqj5rT0Q*) (T5_));
		copyMem__system_1708(((void*) (d)), ((void*) ((*s).d)), ((NI) ((NI)((*s).len * ((NI) 8)))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		dealloc(((void*) ((*s).d)));
		(*s).d = d;
	}
	LA3_: ;
	colontmp_ = c;
	colontmp__2 = t;
	(*s).d[(*s).len].Field0 = colontmp_;
	(*s).d[(*s).len].Field1 = colontmp__2;
	(*s).len += ((NI) 1);
	}BeforeRet_: ;
}
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env) {
	void** p;
	p = ((void**) (q));
	{
		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j;
		if (!!(((*p) == NIM_NIL))) goto LA3_;
		j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env));
		add__system_2722((&(*j).traceStack), p, (*((TNimTypeV2**) ((*p)))));
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZstrtabs_298)(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* dest, void* env) {
	nimTraceRefDyn(&(*dest).Sup.Sup.Sup.parent, env);
	nimTraceRefDyn(&(*dest).Sup.Sup.Sup.up, env);
}
N_LIB_PRIVATE N_NIMCALL(NI, myhash__pureZstrtabs_229)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	switch ((*t).mode) {
	case ((tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ) 0):
	{
		result = hash__pureZhashes_279(key);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ) 1):
	{
		result = hashIgnoreCase__pureZhashes_353(key);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ) 2):
	{
		result = hashIgnoreStyle__pureZhashes_290(key);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, myCmp__pureZstrtabs_233)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 a, NimStringV2 b) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	switch ((*t).mode) {
	case ((tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ) 0):
	{
		NI T2_;
		T2_ = (NI)0;
		T2_ = cmp__system_1540(a, b);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = (T2_ == ((NI) 0));
	}
	break;
	case ((tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ) 1):
	{
		NI T4_;
		T4_ = (NI)0;
		T4_ = nsuCmpIgnoreCase(a, b);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = (T4_ == ((NI) 0));
	}
	break;
	case ((tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ) 2):
	{
		NI T6_;
		T6_ = (NI)0;
		T6_ = nsuCmpIgnoreStyle(a, b);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = (T6_ == ((NI) 0));
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZstrtabs_245)(NI h, NI maxHash) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)(h + ((NI) 1)) & maxHash);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZstrtabs_249)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key) {
	NI result;
	NI h;
	NI T1_;
	NI T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = myhash__pureZstrtabs_229(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = ((*t).data.len-1);
	h = (NI)(T1_ & T2_);
	{
		while (1) {
			NI T14_;
			{
				if (!!((*t).data.p->data[h].Field2)) goto LA7_;
				goto LA4;
			}
			LA7_: ;
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				T11_ = myCmp__pureZstrtabs_233(t, (*t).data.p->data[h].Field0, key);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!T11_) goto LA12_;
				result = h;
				goto BeforeRet_;
			}
			LA12_: ;
			T14_ = ((*t).data.len-1);
			h = nextTry__pureZstrtabs_245(h, T14_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA4: ;
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsthasKey)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = rawGet__pureZstrtabs_249(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI) 0) <= T1_);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
	{
		if (!(((NI) 0) < src.len)) goto LA3_;
		copyMem__system_1708(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(src.len + ((NI) 1)))));
		(*dest).len += src.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2*, nstTake)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key) {
	NimStringV2* result;
	NI indexX60gensym3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NimStringV2*)0;
	indexX60gensym3_ = rawGet__pureZstrtabs_249(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T6_;
		NimStringV2 T7_;
		{
			if (!(((NI) 0) <= indexX60gensym3_)) goto LA4_;
			result = (&(*t).data.p->data[indexX60gensym3_].Field1);
			goto LA1;
		}
		LA4_: ;
		T6_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*)0;
		T6_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) nimNewObj(sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag), NIM_ALIGNOF(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));
		(*T6_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_);
		(*T6_).Sup.Sup.Sup.name = "KeyError";
		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = rawNewString(key.len + 15);
appendString((&T7_), TM__ZT9crccxweoChVXn9cHcxIXQ_3);
appendString((&T7_), key);
		(*T6_).Sup.Sup.Sup.message = T7_;
		(*T6_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "KeyError", "[]", "strtabs.nim", 144);
		goto BeforeRet_;
	} LA1: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mustRehash__pureZstrtabs_238)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL colontmp_;
	result = (NIM_BOOL)0;
	colontmp_ = (NIM_BOOL)0;
	{
		colontmp_ = ((NI)(length * ((NI) 2)) < (NI)(counter * ((NI) 3)));
		{
			if (!colontmp_) goto LA4_;
			goto LA1;
		}
		LA4_: ;
		colontmp_ = ((NI)(length - counter) < ((NI) 4));
	} LA1: ;
	result = colontmp_;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
	(void)(T1_);
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZstrtabs_140)(tyTuple__sPaDkVPSC0MkcoXCxPH9ccA* dest, tyTuple__sPaDkVPSC0MkcoXCxPH9ccA src) {
	if ((*dest).Field0.p != src.Field0.p) {	eqdestroy___system_3228((&(*dest).Field0));
	}
(*dest).Field0.len = src.Field0.len; (*dest).Field0.p = src.Field0.p;
	if ((*dest).Field1.p != src.Field1.p) {	eqdestroy___system_3228((&(*dest).Field1));
	}
(*dest).Field1.len = src.Field1.len; (*dest).Field1.p = src.Field1.p;
	(*dest).Field2 = src.Field2;
}
N_LIB_PRIVATE N_NIMCALL(void, reset__pureZstrtabs_126)(tyTuple__sPaDkVPSC0MkcoXCxPH9ccA* obj) {
	tyTuple__sPaDkVPSC0MkcoXCxPH9ccA* colontmp_;
	tyTuple__sPaDkVPSC0MkcoXCxPH9ccA colontmp__2;
	colontmp_ = obj;
	nimZeroMem((void*)(&colontmp__2), sizeof(tyTuple__sPaDkVPSC0MkcoXCxPH9ccA));
	eqsink___pureZstrtabs_140(colontmp_, colontmp__2);
}
N_LIB_PRIVATE N_NIMCALL(void, shrink__pureZstrtabs_106)(tySequence__xv3aaFd3JCw8NbmALHiezQ* x, NI newLen) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI i;
		NI colontmp_;
		NI colontmp__2;
		NI T2_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp__2 = (NI)0;
		T2_ = (*x).len;
		colontmp_ = (NI)(T2_ - ((NI) 1));
		colontmp__2 = ((NI) (newLen));
		res = colontmp_;
		{
			while (1) {
				{
					if (!!((colontmp__2 <= res))) goto LA7_;
					goto LA4;
				}
				LA7_: ;
				i = res;
				reset__pureZstrtabs_126((&(*x).p->data[i]));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				res -= ((NI) 1);
			} LA4: ;
		}
	}
	(*((tyObject_NimSeqV2__Yc9cU9agg3xM9abj4BkJ7E2Ew*) (x))).len = ((NI) (newLen));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZstrtabs_98)(tySequence__xv3aaFd3JCw8NbmALHiezQ* s, NI newlen) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI oldLen;
		NI T7_;
		tyObject_NimSeqV2__Yc9cU9agg3xM9abj4BkJ7E2Ew* xu;
		NIM_BOOL colontmp_;
		{
			NI T4_;
			T4_ = (*s).len;
			if (!(((NI) (newlen)) < T4_)) goto LA5_;
			shrink__pureZstrtabs_106(s, newlen);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA1;
		}
		LA5_: ;
		T7_ = (*s).len;
		oldLen = T7_;
		{
			if (!(((NI) (newlen)) <= oldLen)) goto LA10_;
			goto BeforeRet_;
		}
		LA10_: ;
		xu = ((tyObject_NimSeqV2__Yc9cU9agg3xM9abj4BkJ7E2Ew*) (s));
		colontmp_ = (NIM_BOOL)0;
		{
			colontmp_ = ((*xu).p == ((tyObject_NimSeqPayload__o16XxZeeToQysG5CEWXEzg*) NIM_NIL));
			{
				if (!colontmp_) goto LA15_;
				goto LA12;
			}
			LA15_: ;
			colontmp_ = ((*(*xu).p).cap < ((NI) (newlen)));
		} LA12: ;
		{
			void* T21_;
			if (!colontmp_) goto LA19_;
			T21_ = (void*)0;
			T21_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), (NI)(((NI) (newlen)) - oldLen), ((NI) 20), ((NI) 4));
			(*xu).p = ((tyObject_NimSeqPayload__o16XxZeeToQysG5CEWXEzg*) (T21_));
		}
		LA19_: ;
		(*xu).len = ((NI) (newlen));
	} LA1: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZstrtabs_358)(tySequence__xv3aaFd3JCw8NbmALHiezQ* s, NI len) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	shrink__pureZstrtabs_106(s, ((NI) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setLen__pureZstrtabs_98(s, len);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZstrtabs_340)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, tySequence__xv3aaFd3JCw8NbmALHiezQ* data, NimStringV2 key, NimStringV2 val) {
	NI h;
	NI T2_;
	NI T3_;
	NimStringV2* colontmp_;
	NimStringV2* colontmp__2;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T2_ = (NI)0;
	T2_ = myhash__pureZstrtabs_229(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_ = ((*data).len-1);
	h = (NI)(T2_ & T3_);
	{
		while (1) {
			NI T10_;
			{
				if (!!((*data).p->data[h].Field2)) goto LA8_;
				goto LA5;
			}
			LA8_: ;
			T10_ = ((*data).len-1);
			h = nextTry__pureZstrtabs_245(h, T10_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		} LA5: ;
	}
	colontmp_ = (&(*data).p->data[h].Field0);
	eqsink___system_3234(colontmp_, key);
	key.len = 0; key.p = NIM_NIL;
	colontmp__2 = (&(*data).p->data[h].Field1);
	eqsink___system_3234(colontmp__2, val);
	val.len = 0; val.p = NIM_NIL;
	(*data).p->data[h].Field2 = NIM_TRUE;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___system_3228((&val));
		eqdestroy___system_3228((&key));
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrtabs_81)(tySequence__xv3aaFd3JCw8NbmALHiezQ* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			{
				NI T5_;
				T5_ = (*dest).len;
				if (!!((colontmp_ < T5_))) goto LA6_;
				goto LA2;
			}
			LA6_: ;
			eqdestroy___system_3228((&(*dest).p->data[colontmp_].Field0));
			eqdestroy___system_3228((&(*dest).p->data[colontmp_].Field1));
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyTuple__sPaDkVPSC0MkcoXCxPH9ccA));
}
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZstrtabs_352)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t) {
	tySequence__xv3aaFd3JCw8NbmALHiezQ n;
	NI T2_;
	tySequence__xv3aaFd3JCw8NbmALHiezQ T17_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n.len = 0; n.p = NIM_NIL;
	T2_ = (*t).data.len;
	newSeq__pureZstrtabs_358((&n), ((NI) ((NI)(T2_ * ((NI) 2)))));
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = ((*t).data.len-1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				{
					if (!!((res <= colontmp_))) goto LA9_;
					goto LA6;
				}
				LA9_: ;
				i = res;
				{
					NimStringV2 T15_;
					NimStringV2 T16_;
					if (!(*t).data.p->data[i].Field2) goto LA13_;
					T15_.len = 0; T15_.p = NIM_NIL;
					T15_ = (*t).data.p->data[i].Field0;
					(*t).data.p->data[i].Field0.len = 0; (*t).data.p->data[i].Field0.p = NIM_NIL;
					T16_.len = 0; T16_.p = NIM_NIL;
					T16_ = (*t).data.p->data[i].Field1;
					(*t).data.p->data[i].Field1.len = 0; (*t).data.p->data[i].Field1.p = NIM_NIL;
					rawInsert__pureZstrtabs_340(t, (&n), T15_, T16_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				LA13_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
	T17_.len = 0; T17_.p = NIM_NIL;
	T17_ = (*t).data;
	(*t).data = n;
	n = T17_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZstrtabs_81((&n));
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key, NimStringV2 val) {
	NI index;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	index = rawGet__pureZstrtabs_249(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2 colontmp__2;
		NimStringV2 colontmp__3;
		tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* T13_;
		{
			NimStringV2* colontmp_;
			if (!(((NI) 0) <= index)) goto LA5_;
			colontmp_ = (&(*t).data.p->data[index].Field1);
			eqsink___system_3234(colontmp_, val);
			val.len = 0; val.p = NIM_NIL;
			goto LA2;
		}
		LA5_: ;
		colontmp__2.len = 0; colontmp__2.p = NIM_NIL;
		colontmp__3.len = 0; colontmp__3.p = NIM_NIL;
		{
			NI T9_;
			NIM_BOOL T10_;
			T9_ = (*t).data.len;
			T10_ = (NIM_BOOL)0;
			T10_ = mustRehash__pureZstrtabs_238(T9_, (*t).counter);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			if (!T10_) goto LA11_;
			enlarge__pureZstrtabs_352(t);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA11_: ;
		T13_ = (tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*)0;
		T13_ = t;
		colontmp__2 = key;
		key.len = 0; key.p = NIM_NIL;
		colontmp__3 = val;
		val.len = 0; val.p = NIM_NIL;
		rawInsert__pureZstrtabs_340(T13_, (&(*t).data), colontmp__2, colontmp__3);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		(*t).counter += ((NI) 1);
	} LA2: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___system_3228((&val));
		eqdestroy___system_3228((&key));
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrtabs_428)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg** dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrtabs_411)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* dest) {
	eqdestroy___pureZstrtabs_81((&(*dest).data));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*, nstnewStringTable)(tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* result;
	result = (tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*)0;
	eqdestroy___pureZstrtabs_428(&result);
	result = (tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*) nimNewObj(sizeof(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg), NIM_ALIGNOF(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg));
	(*result).Sup.m_type = (&NTIv2__V5PVrt9bIxZEeV7lfvqqtNg_);
	(*result).mode = mode;
	(*result).counter = ((NI) 0);
	newSeq__pureZstrtabs_358((&(*result).data), ((NI) 64));
	return result;
}
static N_INLINE(void, nimIncRefCyclic)(void* p, NIM_BOOL cyclic) {
	tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* h;
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_704(((NI) (ptrdiff_t) (p)), ((NI) 8));
	h = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_));
	(*h).rc += ((NI) 16);
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZstrtabs_431)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg** dest, tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* src, NIM_BOOL cyclic) {
	tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* colontmp_;
	colontmp_ = (tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*)0;
	colontmp_ = (*dest);
	{
		if (!src) goto LA3_;
		nimIncRefCyclic(src, cyclic);
	}
	LA3_: ;
	(*dest) = src;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose(colontmp_);
	}
	LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrtabs_336)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	result = nsthasKey(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, del__pureZstrtabs_520)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key) {
	NI i;
	NI msk;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	i = rawGet__pureZstrtabs_249(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = ((*t).data.len-1);
	msk = T1_;
	{
		if (!(((NI) 0) <= i)) goto LA4_;
		(*t).counter -= ((NI) 1);
		{
			{
				while (1) {
					NI j;
					NI r;
					NimStringV2* colontmp_;
					NimStringV2* colontmp__2;
					tyTuple__sPaDkVPSC0MkcoXCxPH9ccA* colontmp__8;
					tyTuple__sPaDkVPSC0MkcoXCxPH9ccA colontmp__9;
					j = i;
					r = j;
					(*t).data.p->data[i].Field2 = NIM_FALSE;
					colontmp_ = (&(*t).data.p->data[i].Field0);
					eqsink___system_3234(colontmp_, TM__ZT9crccxweoChVXn9cHcxIXQ_5);
					colontmp__2 = (&(*t).data.p->data[i].Field1);
					eqsink___system_3234(colontmp__2, TM__ZT9crccxweoChVXn9cHcxIXQ_6);
					{
						while (1) {
							NIM_BOOL colontmp__3;
							NIM_BOOL colontmp__4;
							NIM_BOOL colontmp__5;
							NIM_BOOL colontmp__6;
							NIM_BOOL colontmp__7;
							NI T15_;
							colontmp__3 = (NIM_BOOL)0;
							colontmp__4 = (NIM_BOOL)0;
							colontmp__5 = (NIM_BOOL)0;
							colontmp__6 = (NIM_BOOL)0;
							colontmp__7 = (NIM_BOOL)0;
							i = (NI)((NI)(i + ((NI) 1)) & msk);
							{
								if (!!((*t).data.p->data[i].Field2)) goto LA13_;
								goto LA6;
							}
							LA13_: ;
							T15_ = (NI)0;
							T15_ = myhash__pureZstrtabs_229(t, (*t).data.p->data[i].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							r = (NI)(T15_ & msk);
							{
								{
									{
										{
											colontmp__5 = (r <= i);
											{
												if (!!(colontmp__5)) goto LA23_;
												goto LA20;
											}
											LA23_: ;
											colontmp__5 = (j < r);
										} LA20: ;
										colontmp__4 = colontmp__5;
										{
											if (!colontmp__4) goto LA27_;
											goto LA19;
										}
										LA27_: ;
										{
											colontmp__6 = (j < r);
											{
												if (!!(colontmp__6)) goto LA32_;
												goto LA29;
											}
											LA32_: ;
											colontmp__6 = (i < j);
										} LA29: ;
										colontmp__4 = colontmp__6;
									} LA19: ;
									colontmp__3 = colontmp__4;
									{
										if (!colontmp__3) goto LA36_;
										goto LA18;
									}
									LA36_: ;
									{
										colontmp__7 = (i < j);
										{
											if (!!(colontmp__7)) goto LA41_;
											goto LA38;
										}
										LA41_: ;
										colontmp__7 = (r <= i);
									} LA38: ;
									colontmp__3 = colontmp__7;
								} LA18: ;
								if (!!(colontmp__3)) goto LA43_;
								goto LA9;
							}
							LA43_: ;
						}
					} LA9: ;
					colontmp__8 = (&(*t).data.p->data[j]);
					colontmp__9 = (*t).data.p->data[i];
					nimZeroMem((void*)(&(*t).data.p->data[i]), sizeof(tyTuple__sPaDkVPSC0MkcoXCxPH9ccA));
					eqsink___pureZstrtabs_140(colontmp__8, colontmp__9);
				}
			}
		} LA6: ;
	}
	LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nstlen)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t) {
	NI result;
	result = (NI)0;
	result = (*t).counter;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getOrDefault__pureZstrtabs_326)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, NimStringV2 key, NimStringV2 default_0) {
	NimStringV2 result;
	NI index;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	index = rawGet__pureZstrtabs_249(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		{
			NimStringV2* colontmp_;
			if (!(((NI) 0) <= index)) goto LA4_;
			colontmp_ = (&(*t).data.p->data[index].Field1);
			eqcopy___system_3231((&result), (*colontmp_));
			goto LA1;
		}
		LA4_: ;
		eqcopy___system_3231((&result), default_0);
	} LA1: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {
	prepareAdd(s, ((NI) 1));
	(*(*s).p).data[(*s).len] = c;
	(*(*s).p).data[(NI)((*s).len + ((NI) 1))] = 0;
	(*s).len += ((NI) 1);
}
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c) {
	(*(*dest).p).data[(*dest).len] = c;
	(*(*dest).p).data[(NI)((*dest).len + ((NI) 1))] = 0;
	(*dest).len += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, raiseFormatException__pureZstrtabs_475)(NimStringV2 s) {
	tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T1_;
	NimStringV2 T2_;
{	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*)0;
	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) nimNewObj(sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw), NIM_ALIGNOF(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__yoNlBGx0D2tRizIdhQuENw_);
	(*T1_).Sup.Sup.name = "ValueError";
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(s.len + 30);
appendString((&T2_), TM__ZT9crccxweoChVXn9cHcxIXQ_12);
appendString((&T2_), s);
	(*T1_).Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "ValueError", "raiseFormatException", "strtabs.nim", 299);
	goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getValue__pureZstrtabs_481)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, tySet_tyEnum_FormatFlag__F4vlKAV4d0Kt9aXmu9cVNBrg flags, NimStringV2 key) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nsthasKey(t, key);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		result = getOrDefault__pureZstrtabs_326(t, key, TM__ZT9crccxweoChVXn9cHcxIXQ_8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	LA4_: ;
	{
		{
			if (!((flags &((NU8)1<<((NU)(((tyEnum_FormatFlag__F4vlKAV4d0Kt9aXmu9cVNBrg) 0))&7U)))!=0)) goto LA9_;
			result = getEnv__pureZos_459(key, TM__ZT9crccxweoChVXn9cHcxIXQ_9);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA6;
		}
		LA9_: ;
		result = TM__ZT9crccxweoChVXn9cHcxIXQ_10;
	} LA6: ;
	{
		if (!(result.len == ((NI) 0))) goto LA13_;
		{
			{
				NimStringV2 colontmp_;
				NimStringV2 T20_;
				if (!((flags &((NU8)1<<((NU)(((tyEnum_FormatFlag__F4vlKAV4d0Kt9aXmu9cVNBrg) 2))&7U)))!=0)) goto LA18_;
				T20_.len = 0; T20_.p = NIM_NIL;
				T20_ = rawNewString(key.len + 1);
appendChar((&T20_), 36);
appendString((&T20_), key);
				colontmp_ = T20_;
				eqsink___system_3234((&result), colontmp_);
				goto LA15;
			}
			LA18_: ;
			{
				if (!!(((flags &((NU8)1<<((NU)(((tyEnum_FormatFlag__F4vlKAV4d0Kt9aXmu9cVNBrg) 1))&7U)))!=0))) goto LA23_;
				raiseFormatException__pureZstrtabs_475(key);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				goto LA15;
			}
			LA23_: ;
		} LA15: ;
	}
	LA13_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nstFormat)(NimStringV2 f, tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t, tySet_tyEnum_FormatFlag__F4vlKAV4d0Kt9aXmu9cVNBrg flags) {
	NimStringV2 result;
	NI i;
NIM_BOOL oldNimErrFin14_;
NIM_BOOL oldNimErrFin29_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = TM__ZT9crccxweoChVXn9cHcxIXQ_7;
	i = ((NI) 0);
	{
		while (1) {
			{
				if (!!((i < f.len))) goto LA5_;
				goto LA2;
			}
			LA5_: ;
			{
				{
					if (!((NU8)(f.p->data[i]) == (NU8)(36))) goto LA10_;
					switch (((NU8)(f.p->data[(NI)(i + ((NI) 1))]))) {
					case 36:
					{
						nimAddCharV1((&result), 36);
						i += ((NI) 2);
					}
					break;
					case 123:
					{
						NimStringV2 colontmp_;
						NimStringV2 colontmp__2;
						NI j;
						NimStringV2 colontmp__4;
						NimStringV2 colontmp__5;
						colontmp_.len = 0; colontmp_.p = NIM_NIL;
						colontmp__2.len = 0; colontmp__2.p = NIM_NIL;
						j = (NI)(i + ((NI) 1));
						{
							while (1) {
								NIM_BOOL colontmp__3;
								colontmp__3 = (NIM_BOOL)0;
								{
									colontmp__3 = (j < f.len);
									{
										if (!!(colontmp__3)) goto LA20_;
										goto LA17;
									}
									LA20_: ;
									colontmp__3 = !(((NU8)(f.p->data[j]) == (NU8)(125)));
								} LA17: ;
								{
									if (!!(colontmp__3)) goto LA24_;
									goto LA16;
								}
								LA24_: ;
								j += ((NI) 1);
							} LA16: ;
						}
						colontmp__5 = substr__system_7563(f, (NI)(i + ((NI) 2)), (NI)(j - ((NI) 1)));
						if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
						colontmp_ = colontmp__5;
						colontmp__4 = getValue__pureZstrtabs_481(t, flags, colontmp_);
						if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
						colontmp__2 = colontmp__4;
						prepareAdd((&result), colontmp__2.len + 0);
appendString((&result), colontmp__2);
						i = (NI)(j + ((NI) 1));
						{
							LA14_:;
						}
						{
							oldNimErrFin14_ = *nimErr_; *nimErr_ = NIM_FALSE;
							eqdestroy___system_3228((&colontmp__2));
							eqdestroy___system_3228((&colontmp_));
							*nimErr_ = oldNimErrFin14_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					break;
					case 97 ... 122:
					case 65 ... 90:
					case 128 ... 255:
					case 95:
					{
						NimStringV2 colontmp__6;
						NimStringV2 colontmp__7;
						NI j_2;
						NimStringV2 colontmp__9;
						NimStringV2 colontmp__10;
						colontmp__6.len = 0; colontmp__6.p = NIM_NIL;
						colontmp__7.len = 0; colontmp__7.p = NIM_NIL;
						j_2 = (NI)(i + ((NI) 1));
						{
							while (1) {
								NIM_BOOL colontmp__8;
								colontmp__8 = (NIM_BOOL)0;
								{
									colontmp__8 = (j_2 < f.len);
									{
										if (!!(colontmp__8)) goto LA35_;
										goto LA32;
									}
									LA35_: ;
									colontmp__8 = (((NU8)(f.p->data[j_2])) >= ((NU8)(97)) && ((NU8)(f.p->data[j_2])) <= ((NU8)(122)) || ((NU8)(f.p->data[j_2])) >= ((NU8)(65)) && ((NU8)(f.p->data[j_2])) <= ((NU8)(90)) || ((NU8)(f.p->data[j_2])) >= ((NU8)(48)) && ((NU8)(f.p->data[j_2])) <= ((NU8)(57)) || ((NU8)(f.p->data[j_2])) == ((NU8)(95)) || ((NU8)(f.p->data[j_2])) >= ((NU8)(128)) && ((NU8)(f.p->data[j_2])) <= ((NU8)(255)));
								} LA32: ;
								{
									if (!!(colontmp__8)) goto LA39_;
									goto LA31;
								}
								LA39_: ;
								j_2 += ((NI) 1);
							} LA31: ;
						}
						colontmp__10 = substr__system_7563(f, (NI)(i + ((NI) 1)), (NI)(j_2 - ((NI) 1)));
						if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
						colontmp__6 = colontmp__10;
						colontmp__9 = getValue__pureZstrtabs_481(t, flags, colontmp__6);
						if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
						colontmp__7 = colontmp__9;
						prepareAdd((&result), colontmp__7.len + 0);
appendString((&result), colontmp__7);
						i = j_2;
						{
							LA29_:;
						}
						{
							oldNimErrFin29_ = *nimErr_; *nimErr_ = NIM_FALSE;
							eqdestroy___system_3228((&colontmp__7));
							eqdestroy___system_3228((&colontmp__6));
							*nimErr_ = oldNimErrFin29_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					break;
					default:
					{
						nimAddCharV1((&result), f.p->data[i]);
						i += ((NI) 1);
					}
					break;
					}
					goto LA7;
				}
				LA10_: ;
				nimAddCharV1((&result), f.p->data[i]);
				i += ((NI) 1);
			} LA7: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZstrtabs_435)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg** dest, tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* src) {
	tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* colontmp_;
	colontmp_ = (tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*)0;
	colontmp_ = (*dest);
	(*dest) = src;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strtabsDatInit000)(void) {
NTIv2__V5PVrt9bIxZEeV7lfvqqtNg_.destructor = (void*)eqdestroy___pureZstrtabs_411; NTIv2__V5PVrt9bIxZEeV7lfvqqtNg_.size = sizeof(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg); NTIv2__V5PVrt9bIxZEeV7lfvqqtNg_.align = NIM_ALIGNOF(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg); NTIv2__V5PVrt9bIxZEeV7lfvqqtNg_.name = "|stdlib.strtabs.StringTableObj|RootObj|";
; NTIv2__V5PVrt9bIxZEeV7lfvqqtNg_.traceImpl = (void*)NIM_NIL; NTIv2__V5PVrt9bIxZEeV7lfvqqtNg_.flags = 0;}

