/* Generated by Nim Compiler v0.1.0-dev.20827 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tyObject_NimSeqV2__Q27im4NvCIX735oBXfroyA tyObject_NimSeqV2__Q27im4NvCIX735oBXfroyA;
typedef struct tyObject_NimSeqPayload__hKmcfrIyKucBh7ADIUKy1Q tyObject_NimSeqPayload__hKmcfrIyKucBh7ADIUKy1Q;
typedef struct tySequence__shxop0zPIs5Ec3k71aCLuQ tySequence__shxop0zPIs5Ec3k71aCLuQ;
typedef struct tySequence__shxop0zPIs5Ec3k71aCLuQ_Content tySequence__shxop0zPIs5Ec3k71aCLuQ_Content;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og tySequence__pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ;
typedef struct tyObject_NimSeqV2__WwIxl9cP870j9abb7JNt62Qw tyObject_NimSeqV2__WwIxl9cP870j9abb7JNt62Qw;
typedef struct tyObject_NimSeqPayload__ix0G8Ryw3xjwco1U8sjH5g tyObject_NimSeqPayload__ix0G8Ryw3xjwco1U8sjH5g;
typedef struct tySequence__pYLvFbtgBj9bhL1nOMycYqw tySequence__pYLvFbtgBj9bhL1nOMycYqw;
typedef struct tySequence__pYLvFbtgBj9bhL1nOMycYqw_Content tySequence__pYLvFbtgBj9bhL1nOMycYqw_Content;
typedef struct tyTuple__dPNkpxgceTc63bP5seHZGw tyTuple__dPNkpxgceTc63bP5seHZGw;
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tyObject_NimSeqV2__Q27im4NvCIX735oBXfroyA {
NI len;
tyObject_NimSeqPayload__hKmcfrIyKucBh7ADIUKy1Q* p;
};
struct tyObject_NimSeqPayload__hKmcfrIyKucBh7ADIUKy1Q {
NI cap;
NI data[SEQ_DECL_SIZE];
};
struct tySequence__shxop0zPIs5Ec3k71aCLuQ {
  NI len; tySequence__shxop0zPIs5Ec3k71aCLuQ_Content* p;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og {
  NI len; tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content* p;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringV2 Field1;
NI Field2;
};
struct tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ {
tySequence__pUxI6Ljo6IKKHXKOZkQ7Og data;
NI counter;
};
struct tyObject_NimSeqV2__WwIxl9cP870j9abb7JNt62Qw {
NI len;
tyObject_NimSeqPayload__ix0G8Ryw3xjwco1U8sjH5g* p;
};
struct tyObject_NimSeqPayload__ix0G8Ryw3xjwco1U8sjH5g {
NI cap;
tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];
};
struct tySequence__pYLvFbtgBj9bhL1nOMycYqw {
  NI len; tySequence__pYLvFbtgBj9bhL1nOMycYqw_Content* p;
};
struct tyTuple__dPNkpxgceTc63bP5seHZGw {
NimStringV2 Field0;
NIM_BOOL Field1;
};


#ifndef tySequence__qwqHTkRvwhrRyENtudHQ7g_Content_PP
#define tySequence__qwqHTkRvwhrRyENtudHQ7g_Content_PP
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__shxop0zPIs5Ec3k71aCLuQ_Content_PP
#define tySequence__shxop0zPIs5Ec3k71aCLuQ_Content_PP
struct tySequence__shxop0zPIs5Ec3k71aCLuQ_Content { NI cap; NIM_BOOL data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__shxop0zPIs5Ec3k71aCLuQ_Content_PP
#define tySequence__shxop0zPIs5Ec3k71aCLuQ_Content_PP
struct tySequence__shxop0zPIs5Ec3k71aCLuQ_Content { NI cap; NIM_BOOL data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content_PP
#define tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content_PP
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content { NI cap; tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content_PP
#define tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content_PP
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content { NI cap; tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__pYLvFbtgBj9bhL1nOMycYqw_Content_PP
#define tySequence__pYLvFbtgBj9bhL1nOMycYqw_Content_PP
struct tySequence__pYLvFbtgBj9bhL1nOMycYqw_Content { NI cap; tyTuple__dPNkpxgceTc63bP5seHZGw data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd)(NI len, void* p, NI addlen, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__experimentalZdiff_1745)(tySequence__shxop0zPIs5Ec3k71aCLuQ* s, NI len);
N_LIB_PRIVATE N_NIMCALL(void, shrink__frontZnimconf_244)(tySequence__shxop0zPIs5Ec3k71aCLuQ* x, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, setLen__frontZnimconf_236)(tySequence__shxop0zPIs5Ec3k71aCLuQ* s, NI newlen);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3228)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_43)(NI count);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_183)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__experimentalZdiff_749)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* s, NI len);
N_LIB_PRIVATE N_NIMCALL(void, shrink__experimentalZdiff_405)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* x, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, reset__experimentalZdiff_425)(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ* obj);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___experimentalZdiff_439)(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ* dest, tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ src);
N_LIB_PRIVATE N_NIMCALL(void, setLen__experimentalZdiff_398)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* s, NI newlen);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___experimentalZdiff_381)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* dest);
static N_INLINE(NI, rawGet__experimentalZdiff_145)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ t, NimStringV2 key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_279)(NimStringV2 x);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_32)(NI hcode);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_BOOL, equalMem__system_1716)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_35)(NI h, NI maxHash);
static N_INLINE(NIM_BOOL, mustRehash__experimentalZdiff_875)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__experimentalZdiff_1028)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__experimentalZdiff_1328)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ* t, tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* data, NimStringV2 key, NI val, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3231)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(NI, rawGetKnownHC__experimentalZdiff_1497)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ t, NimStringV2 key, NI hc);
extern NIM_BOOL nimInErrorMode__system_4174;
N_LIB_PRIVATE N_NIMCALL(void, add__experimentalZdiff_630)(tySequence__qwqHTkRvwhrRyENtudHQ7g* x, NI value) {
	NI oldLen;
	NI T1_;
	tyObject_NimSeqV2__Q27im4NvCIX735oBXfroyA* xu;
	NIM_BOOL colontmp_;
	T1_ = (*x).len;
	oldLen = T1_;
	xu = ((tyObject_NimSeqV2__Q27im4NvCIX735oBXfroyA*) (x));
	colontmp_ = (NIM_BOOL)0;
	{
		colontmp_ = ((*xu).p == ((tyObject_NimSeqPayload__hKmcfrIyKucBh7ADIUKy1Q*) NIM_NIL));
		{
			if (!colontmp_) goto LA5_;
			goto LA2;
		}
		LA5_: ;
		colontmp_ = ((*(*xu).p).cap < (NI)(oldLen + ((NI) 1)));
	} LA2: ;
	{
		void* T11_;
		if (!colontmp_) goto LA9_;
		T11_ = (void*)0;
		T11_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), ((NI) 1), ((NI) 4), ((NI) 4));
		(*xu).p = ((tyObject_NimSeqPayload__hKmcfrIyKucBh7ADIUKy1Q*) (T11_));
	}
	LA9_: ;
	(*xu).len = (NI)(oldLen + ((NI) 1));
	(*(*xu).p).data[oldLen] = value;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4174);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, newSeq__experimentalZdiff_1745)(tySequence__shxop0zPIs5Ec3k71aCLuQ* s, NI len) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	shrink__frontZnimconf_244(s, ((NI) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setLen__frontZnimconf_236(s, len);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__shxop0zPIs5Ec3k71aCLuQ, newSeq__experimentalZdiff_1741)(NI len) {
	tySequence__shxop0zPIs5Ec3k71aCLuQ result;
	result.len = 0; result.p = NIM_NIL;
	newSeq__experimentalZdiff_1745((&result), len);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___experimentalZdiff_381)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			{
				NI T5_;
				T5_ = (*dest).len;
				if (!!((colontmp_ < T5_))) goto LA6_;
				goto LA2;
			}
			LA6_: ;
			eqdestroy___system_3228((&(*dest).p->data[colontmp_].Field1));
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ));
}
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
	(void)(T1_);
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_43)(NI count) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = nextPowerOfTwo__pureZmath_183((NI)((NI)((NI)(((NI) (count)) * ((NI) 3)) / ((NI) 2)) + ((NI) 4)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___experimentalZdiff_439)(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ* dest, tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ src) {
	(*dest).Field0 = src.Field0;
	if ((*dest).Field1.p != src.Field1.p) {	eqdestroy___system_3228((&(*dest).Field1));
	}
(*dest).Field1.len = src.Field1.len; (*dest).Field1.p = src.Field1.p;
	(*dest).Field2 = src.Field2;
}
N_LIB_PRIVATE N_NIMCALL(void, reset__experimentalZdiff_425)(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ* obj) {
	tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ* colontmp_;
	tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ colontmp__2;
	colontmp_ = obj;
	nimZeroMem((void*)(&colontmp__2), sizeof(tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ));
	eqsink___experimentalZdiff_439(colontmp_, colontmp__2);
}
N_LIB_PRIVATE N_NIMCALL(void, shrink__experimentalZdiff_405)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* x, NI newLen) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI i;
		NI colontmp_;
		NI colontmp__2;
		NI T2_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp__2 = (NI)0;
		T2_ = (*x).len;
		colontmp_ = (NI)(T2_ - ((NI) 1));
		colontmp__2 = ((NI) (newLen));
		res = colontmp_;
		{
			while (1) {
				{
					if (!!((colontmp__2 <= res))) goto LA7_;
					goto LA4;
				}
				LA7_: ;
				i = res;
				reset__experimentalZdiff_425((&(*x).p->data[i]));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				res -= ((NI) 1);
			} LA4: ;
		}
	}
	(*((tyObject_NimSeqV2__WwIxl9cP870j9abb7JNt62Qw*) (x))).len = ((NI) (newLen));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setLen__experimentalZdiff_398)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* s, NI newlen) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI oldLen;
		NI T7_;
		tyObject_NimSeqV2__WwIxl9cP870j9abb7JNt62Qw* xu;
		NIM_BOOL colontmp_;
		{
			NI T4_;
			T4_ = (*s).len;
			if (!(((NI) (newlen)) < T4_)) goto LA5_;
			shrink__experimentalZdiff_405(s, newlen);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto LA1;
		}
		LA5_: ;
		T7_ = (*s).len;
		oldLen = T7_;
		{
			if (!(((NI) (newlen)) <= oldLen)) goto LA10_;
			goto BeforeRet_;
		}
		LA10_: ;
		xu = ((tyObject_NimSeqV2__WwIxl9cP870j9abb7JNt62Qw*) (s));
		colontmp_ = (NIM_BOOL)0;
		{
			colontmp_ = ((*xu).p == ((tyObject_NimSeqPayload__ix0G8Ryw3xjwco1U8sjH5g*) NIM_NIL));
			{
				if (!colontmp_) goto LA15_;
				goto LA12;
			}
			LA15_: ;
			colontmp_ = ((*(*xu).p).cap < ((NI) (newlen)));
		} LA12: ;
		{
			void* T21_;
			if (!colontmp_) goto LA19_;
			T21_ = (void*)0;
			T21_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), (NI)(((NI) (newlen)) - oldLen), ((NI) 16), ((NI) 4));
			(*xu).p = ((tyObject_NimSeqPayload__ix0G8Ryw3xjwco1U8sjH5g*) (T21_));
		}
		LA19_: ;
		(*xu).len = ((NI) (newlen));
	} LA1: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, newSeq__experimentalZdiff_749)(tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* s, NI len) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	shrink__experimentalZdiff_405(s, ((NI) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	setLen__experimentalZdiff_398(s, len);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ, initTable__experimentalZdiff_2096)(NI initialSize) {
	tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ result;
	NI correctSizeX60gensym23_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ));
	correctSizeX60gensym23_ = slotsNeeded__pureZcollectionsZtables_43(((NI) (initialSize)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.counter = ((NI) 0);
	newSeq__experimentalZdiff_749((&result.data), ((NI) (correctSizeX60gensym23_)));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___experimentalZdiff_2318)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ* dest, tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ src) {
	if ((*dest).data.p != src.data.p) {	eqdestroy___experimentalZdiff_381((&(*dest).data));
	}
(*dest).data.len = src.data.len; (*dest).data.p = src.data.p;
	(*dest).counter = src.counter;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_32)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1716)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = a.len;
	blen = b.len;
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem__system_1716(((void*) ((&a.p->data[((NI) 0)]))), ((void*) ((&b.p->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_35)(NI h, NI maxHash) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)(h + ((NI) 1)) & maxHash);
	return result;
}
static N_INLINE(NI, rawGet__experimentalZdiff_145)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ t, NimStringV2 key, NI* hc) {
	NI result;
	NI T1_;
	NI h;
	NI T11_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash__pureZhashes_279(key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc) = T1_;
	{
		if (!((*hc) == ((NI) 0))) goto LA4_;
		(*hc) = ((NI) 314159265);
	}
	LA4_: ;
	{
		NI T8_;
		T8_ = t.data.len;
		if (!(T8_ == ((NI) 0))) goto LA9_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (t.data.len-1);
	h = (NI)((*hc) & T11_);
	{
		while (1) {
			NIM_BOOL colontmp_;
			NI T28_;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = isFilled__pureZcollectionsZtables_32(t.data.p->data[h].Field0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!!(T16_)) goto LA17_;
				goto LA13;
			}
			LA17_: ;
			colontmp_ = (NIM_BOOL)0;
			{
				colontmp_ = (t.data.p->data[h].Field0 == (*hc));
				{
					if (!!(colontmp_)) goto LA22_;
					goto LA19;
				}
				LA22_: ;
				colontmp_ = eqStrings(t.data.p->data[h].Field1, key);
			} LA19: ;
			{
				if (!colontmp_) goto LA26_;
				result = h;
				goto BeforeRet_;
			}
			LA26_: ;
			T28_ = (t.data.len-1);
			h = nextTry__pureZcollectionsZtables_35(h, T28_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__experimentalZdiff_138)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ t, NimStringV2 key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet__experimentalZdiff_145(t, key, (&hc));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI) 0) <= T1_);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__experimentalZdiff_875)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ t) {
	NIM_BOOL result;
	NIM_BOOL colontmp_;
	result = (NIM_BOOL)0;
	colontmp_ = (NIM_BOOL)0;
	{
		NI T2_;
		NI T7_;
		T2_ = t.data.len;
		colontmp_ = ((NI)(T2_ * ((NI) 2)) < (NI)(t.counter * ((NI) 3)));
		{
			if (!colontmp_) goto LA5_;
			goto LA1;
		}
		LA5_: ;
		T7_ = t.data.len;
		colontmp_ = ((NI)(T7_ - t.counter) < ((NI) 4));
	} LA1: ;
	result = colontmp_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__experimentalZdiff_1328)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ* t, tySequence__pUxI6Ljo6IKKHXKOZkQ7Og* data, NimStringV2 key, NI val, NI hc, NI h) {
	NimStringV2* colontmp_;
	colontmp_ = (&(*data).p->data[h].Field1);
	eqcopy___system_3231(colontmp_, key);
	(*data).p->data[h].Field2 = val;
	(*data).p->data[h].Field0 = hc;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__experimentalZdiff_1028)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ* t) {
	tySequence__pUxI6Ljo6IKKHXKOZkQ7Og n;
	NI T2_;
	tySequence__pUxI6Ljo6IKKHXKOZkQ7Og T3_;
NIM_BOOL oldNimErrFin17_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n.len = 0; n.p = NIM_NIL;
	T2_ = (*t).data.len;
	newSeq__experimentalZdiff_749((&n), ((NI) ((NI)(T2_ * ((NI) 2)))));
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = (*t).data;
	(*t).data = n;
	n = T3_;
	{
		NI i;
		NI colontmp_;
		NI T5_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T5_ = (n.len-1);
		colontmp_ = T5_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				{
					if (!!((res <= colontmp_))) goto LA10_;
					goto LA7;
				}
				LA10_: ;
				i = res;
				eh = n.p->data[i].Field0;
				{
					NIM_BOOL T14_;
					NimStringV2 colontmp__2;
					NI j;
					NI T18_;
					NimStringV2 colontmp__3;
					NI T27_;
					T14_ = (NIM_BOOL)0;
					T14_ = isFilled__pureZcollectionsZtables_32(eh);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T14_) goto LA15_;
					colontmp__2.len = 0; colontmp__2.p = NIM_NIL;
					T18_ = ((*t).data.len-1);
					j = (NI)(eh & T18_);
					{
						while (1) {
							NI T26_;
							{
								NIM_BOOL T23_;
								T23_ = (NIM_BOOL)0;
								T23_ = isFilled__pureZcollectionsZtables_32((*t).data.p->data[j].Field0);
								if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
								if (!!(T23_)) goto LA24_;
								goto LA20;
							}
							LA24_: ;
							T26_ = ((*t).data.len-1);
							j = nextTry__pureZcollectionsZtables_35(j, T26_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
						} LA20: ;
					}
					colontmp__3 = n.p->data[i].Field1;
					n.p->data[i].Field1.len = 0; n.p->data[i].Field1.p = NIM_NIL;
					colontmp__2 = colontmp__3;
					T27_ = (NI)0;
					T27_ = n.p->data[i].Field2;
					n.p->data[i].Field2 = 0;
					rawInsert__experimentalZdiff_1328(t, (&(*t).data), colontmp__2, T27_, eh, j);
					if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
					{
						LA17_:;
					}
					{
						oldNimErrFin17_ = *nimErr_; *nimErr_ = NIM_FALSE;
						eqdestroy___system_3228((&colontmp__2));
						*nimErr_ = oldNimErrFin17_;
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				LA15_: ;
				res += ((NI) 1);
			} LA7: ;
		}
	}
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___experimentalZdiff_381((&n));
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, rawGetKnownHC__experimentalZdiff_1497)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ t, NimStringV2 key, NI hc) {
	NI result;
	NI h;
	NI T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI T3_;
		T3_ = t.data.len;
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = (t.data.len-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL colontmp_;
			NI T23_;
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				T11_ = isFilled__pureZcollectionsZtables_32(t.data.p->data[h].Field0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!!(T11_)) goto LA12_;
				goto LA8;
			}
			LA12_: ;
			colontmp_ = (NIM_BOOL)0;
			{
				colontmp_ = (t.data.p->data[h].Field0 == hc);
				{
					if (!!(colontmp_)) goto LA17_;
					goto LA14;
				}
				LA17_: ;
				colontmp_ = eqStrings(t.data.p->data[h].Field1, key);
			} LA14: ;
			{
				if (!colontmp_) goto LA21_;
				result = h;
				goto BeforeRet_;
			}
			LA21_: ;
			T23_ = (t.data.len-1);
			h = nextTry__pureZcollectionsZtables_35(h, T23_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___experimentalZdiff_694)(tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ* t, NimStringV2 key, NI val) {
	NI hc;
	NI index;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym3_;
		T3_ = (*t).data.len;
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym3_ = slotsNeeded__pureZcollectionsZtables_43(((NI) 32));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*t).counter = ((NI) 0);
		newSeq__experimentalZdiff_749((&(*t).data), ((NI) (correctSizeX60gensym3_)));
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__experimentalZdiff_145((*t), key, (&hc));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		{
			if (!(((NI) 0) <= index)) goto LA9_;
			(*t).data.p->data[index].Field2 = val;
			goto LA6;
		}
		LA9_: ;
		{
			NI T13_;
			NI correctSizeX60gensym5_;
			T13_ = (*t).data.len;
			if (!(T13_ == ((NI) 0))) goto LA14_;
			correctSizeX60gensym5_ = slotsNeeded__pureZcollectionsZtables_43(((NI) 32));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			(*t).counter = ((NI) 0);
			newSeq__experimentalZdiff_749((&(*t).data), ((NI) (correctSizeX60gensym5_)));
		}
		LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__experimentalZdiff_875((*t));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T18_) goto LA19_;
			enlarge__experimentalZdiff_1028(t);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			index = rawGetKnownHC__experimentalZdiff_1497((*t), key, hc);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA19_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert__experimentalZdiff_1328(t, (&(*t).data), key, val, hc, index);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*t).counter += ((NI) 1);
	} LA6: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___experimentalZdiff_2825)(tySequence__pYLvFbtgBj9bhL1nOMycYqw* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			{
				NI T5_;
				T5_ = (*dest).len;
				if (!!((colontmp_ < T5_))) goto LA6_;
				goto LA2;
			}
			LA6_: ;
			eqdestroy___system_3228((&(*dest).p->data[colontmp_].Field0));
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyTuple__dPNkpxgceTc63bP5seHZGw));
}
}
